/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_analytics } from "../app/api/analytics/route";
import type { POST as POST_analytics } from "../app/api/analytics/route";

// Type-only representation of your API routes
export type APIRouter = {
  analytics: {
    get: typeof GET_analytics;
    post: typeof POST_analytics;
  };
};
