
// Auto-generated by Farm.js
// This handler handles all page routes (SSR)
import { defineEventHandler, setResponseStatus, getRequestURL, setHeader } from 'h3';
import type { H3Event } from 'h3';
import { farmRegistry } from '../farm-registry';
import React from 'react';
import { renderToString } from 'react-dom/server';

export default defineEventHandler(async (event: H3Event) => {
  try {
    // Ensure registry is populated (lazy initialization)
    // In serverless environments, the registry needs to be initialized at runtime
    if (!farmRegistry.routeManager || !farmRegistry.serverRenderer) {
      // Try to initialize from global if available (set during build)
      if (typeof globalThis !== 'undefined' && (globalThis as any).__FARM_REGISTRY__) {
        Object.assign(farmRegistry, (globalThis as any).__FARM_REGISTRY__);
      }
      // If still not available, try the init function (if it exists)
      if ((!farmRegistry.routeManager || !farmRegistry.serverRenderer) && (farmRegistry as any).__INIT__) {
        (farmRegistry as any).__INIT__();
      }
    }
    
    const routeManager = farmRegistry.routeManager;
    const serverRenderer = farmRegistry.serverRenderer;
    
    if (!routeManager || !serverRenderer) {
      console.error('Route manager or renderer not initialized. Registry keys:', Object.keys(farmRegistry));
      setResponseStatus(event, 500);
      setHeader(event, 'Content-Type', 'text/html; charset=utf-8');
      return '<!DOCTYPE html><html><head><title>Error</title></head><body><h1>500 Internal Server Error</h1><p>Route manager or renderer not initialized. Please check server logs.</p></body></html>';
    }
    
    // Get URL from H3 event
    const url = getRequestURL(event);
    const pathname = url.pathname;
    
    // Skip API routes - let the API handler process them
    if (pathname.startsWith('/api/')) {
      // Return undefined to let Nitro's API handler process
      return undefined;
    }
    
    // Skip static assets - let Nitro serve them
    // Only skip if it's clearly a static file (has extension and not in root)
    if (pathname.startsWith('/assets/') || (pathname.includes('.') && !pathname.startsWith('/api/'))) {
      // Check if it's a static file by extension
      const staticExtensions = ['.js', '.css', '.png', '.jpg', '.jpeg', '.gif', '.svg', '.ico', '.woff', '.woff2', '.ttf', '.eot'];
      const hasStaticExtension = staticExtensions.some(ext => pathname.toLowerCase().endsWith(ext));
      if (hasStaticExtension) {
        return; // Let Nitro's static file handler process
      }
    }
    
    // Try to use Node.js req/res if available (for node-server preset)
    if (event.node && event.node.req && event.node.res) {
      await serverRenderer.renderPage(event.node.req as any, event.node.res as any);
      return undefined; // Response already sent
    }
    
    // For serverless (Vercel), render to string and send HTML
    try {
      // Match route
      const { route, params, layouts } = routeManager.matchRoute(pathname);
      
      if (!route) {
        setResponseStatus(event, 404);
        setHeader(event, 'Content-Type', 'text/html; charset=utf-8');
        return '<!DOCTYPE html><html><head><title>404 Not Found</title></head><body><h1>404 Not Found</h1></body></html>';
      }
      
      // Get search params
      const searchParamsObject: Record<string, string | string[] | undefined> = {};
      url.searchParams.forEach((value, key) => {
        const existing = searchParamsObject[key];
        if (existing) {
          if (Array.isArray(existing)) {
            existing.push(value);
          } else {
            searchParamsObject[key] = [existing, value];
          }
        } else {
          searchParamsObject[key] = value;
        }
      });
      
      // Load route module - in production, use bundled SSR output
      // Get bundled path from registry or construct it
      let routeModule;
      const routePaths = farmRegistry.routePaths || {};
      const bundledPath = routePaths[pathname] || route.modulePath
        .replace(/.*\/src\/app\//, '')
        .replace(/\.(tsx?|jsx?)$/, '.js');
      
      try {
        // Try to load from bundled SSR output (copied to Nitro's server/farm directory)
        // Nitro bundles everything, so we need to use the correct import path
        routeModule = await import('./farm/' + bundledPath);
      } catch (importError) {
        // Fallback: try route manager's load method (for node-server preset)
        try {
          routeModule = await routeManager.loadRouteModule(route.modulePath);
        } catch (loadError) {
          // Last resort: try just the filename
          const bundledName = bundledPath.split('/').pop() || 'page.js';
          try {
            routeModule = await import('./farm/' + bundledName);
          } catch {
            throw new Error(`Failed to load route module: ${route.modulePath}. Tried: ./farm/${bundledPath}, ./farm/${bundledName}`);
          }
        }
      }
      
      if (!routeModule.default) {
        throw new Error(`Route module ${route.modulePath} does not export a default component`);
      }
      
      // Load layout modules
      const layoutModules = await Promise.all(
        layouts.map(async (layout) => {
          const bundledPath = layout.modulePath
            .replace(/.*\/src\/app\//, '')
            .replace(/\.(tsx?|jsx?)$/, '.js');
          
          try {
            // Try to load from bundled SSR output
            return await import('./farm/' + bundledPath);
          } catch {
            // Fallback to route manager's load method
            try {
              return await routeManager.loadLayoutModule(layout.modulePath);
            } catch {
              // Last resort: try just the filename
              const bundledName = bundledPath.split('/').pop() || 'layout.js';
              try {
                return await import('./farm/' + bundledName);
              } catch {
                // Return a dummy layout if all fails
                return { default: ({ children }: any) => children };
              }
            }
          }
        })
      );
      
      // Create page props
      const pageProps = {
        params,
        searchParams: Promise.resolve(searchParamsObject),
        path: pathname,
      };
      
      // Create page element
      const PageComponent = routeModule.default;
      let pageElement = React.createElement(PageComponent, pageProps);
      
      // Wrap with layouts
      for (let i = layoutModules.length - 1; i >= 0; i--) {
        const layoutModule = layoutModules[i];
        const LayoutComponent = layoutModule.default;
        pageElement = React.createElement(LayoutComponent, {
          children: pageElement,
          params,
        } as any);
      }
      
      // Render to string
      const html = renderToString(pageElement);
      
      // Get client script path from manifest
      const clientManifest = farmRegistry.clientManifest || {};
      // Find the client script for this route - check manifest structure
      let clientScript = '/assets/page-wbYjx1yQ.js'; // Default fallback
      if (clientManifest && typeof clientManifest === 'object') {
        // Manifest structure: { "assets/page-xxx.js": { ... } }
        const manifestEntry = Object.values(clientManifest).find((entry: any) => 
          entry && entry.name === 'page'
        ) as any;
        if (manifestEntry && manifestEntry.chunks && manifestEntry.chunks[0]) {
          clientScript = '/' + manifestEntry.chunks[0];
        } else if (Object.keys(clientManifest).length > 0) {
          // Fallback to first asset in manifest
          clientScript = '/' + Object.keys(clientManifest)[0];
        }
      }
      
      // Build full HTML
      const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Farm.js App</title>
  <script>
    window.__FARM_PROPS__ = ${JSON.stringify(pageProps)};
    window.__FARM_PATH__ = ${JSON.stringify(pathname)};
  </script>
</head>
<body>
  <div id="root">${html}</div>
  <script type="module" src="${clientScript}"></script>
</body>
</html>`;
      
      setHeader(event, 'Content-Type', 'text/html; charset=utf-8');
      return fullHtml;
      
    } catch (renderError: any) {
      setResponseStatus(event, 500);
      setHeader(event, 'Content-Type', 'text/html; charset=utf-8');
      return `<!DOCTYPE html><html><head><title>Error</title></head><body><h1>Error</h1><p>${renderError.message || 'Internal Server Error'}</p></body></html>`;
    }
  } catch (error: any) {
    setResponseStatus(event, 500);
    setHeader(event, 'Content-Type', 'text/html; charset=utf-8');
    return `<!DOCTYPE html><html><head><title>Error</title></head><body><h1>Error</h1><p>${error.message || 'Internal Server Error'}</p></body></html>`;
  }
});
