import type {
  FarmSearchClient,
  FarmSearchPublicConfig,
  SearchClientOptions,
  SearchFilterCounts,
  SearchQueryOptions,
  SearchResponse,
  SearchResult,
} from "./types.js";

interface PagefindSearchFragment {
  url: string;
  content: string;
  excerpt: string;
  plain_excerpt: string;
  word_count: number;
  filters: Record<string, string[]>;
  meta: Record<string, string>;
  sub_results: Array<{
    title: string;
    url: string;
    excerpt: string;
    plain_excerpt: string;
  }>;
}

interface PagefindResultHandle {
  id: string;
  score: number;
  words: number[];
  matchedMetaFields?: string[];
  data(): Promise<PagefindSearchFragment>;
}

interface PagefindSearchResponse {
  results: PagefindResultHandle[];
  unfilteredResultCount: number;
  filters: SearchFilterCounts;
  totalFilters: SearchFilterCounts;
  timings:
    | { preload: number; search: number; total: number }
    | Array<{
        preload: number;
        search: number;
        total: number;
      }>;
}

export interface PagefindBrowserApi {
  options(options: Record<string, unknown>): Promise<void>;
  init(): Promise<void>;
  search(term: string | null, options?: Record<string, unknown>): Promise<PagefindSearchResponse>;
  preload(term: string, options?: Record<string, unknown>): Promise<void>;
  filters(): Promise<SearchFilterCounts>;
  destroy(): Promise<void>;
}

export interface PagefindBrowserModule extends PagefindBrowserApi {
  createInstance?(
    options?: Record<string, unknown>,
  ): PagefindBrowserApi | Promise<PagefindBrowserApi>;
}

export type PagefindModuleLoader = (url: string) => Promise<PagefindBrowserModule>;

export function createSearchClient(
  resolveConfig: () => FarmSearchPublicConfig,
  options: SearchClientOptions,
  loadModule: PagefindModuleLoader,
): FarmSearchClient {
  let loaded: Promise<{ api: PagefindBrowserApi; bundlePath: string }> | undefined;

  const getApi = async () => {
    const config = resolveConfig();
    if (!config.available && !options.bundlePath) {
      throw new Error(
        "[farm:search] The search index is generated by production builds. " +
          "Run farm build and serve the production output before searching.",
      );
    }

    const bundlePath = normalizeBundlePath(options.bundlePath ?? config.bundlePath);
    if (!loaded) {
      const loading = loadModule(`${bundlePath}pagefind.js`)
        .then(async (module) => {
          const highlightParam =
            options.highlightParam === false
              ? undefined
              : (options.highlightParam ?? config.highlightParam);
          const pagefindOptions = {
            basePath: bundlePath,
            excerptLength: normalizePositiveInteger(
              options.excerptLength ?? config.excerptLength,
              "excerptLength",
            ),
            ...(highlightParam ? { highlightParam } : {}),
          };
          const api = module.createInstance ? await module.createInstance(pagefindOptions) : module;
          if (!module.createInstance) await api.options(pagefindOptions);
          await api.init();
          return { api, bundlePath };
        })
        .catch((error) => {
          loaded = undefined;
          throw error;
        });
      loaded = loading;
    }

    const current = await loaded;
    if (current.bundlePath !== bundlePath) {
      await current.api.destroy();
      loaded = undefined;
      return getApi();
    }
    return current.api;
  };

  return {
    async search(term, queryOptions = {}) {
      if (term !== null && typeof term !== "string") {
        throw new TypeError("Search term must be a string or null");
      }
      const limit = normalizePositiveInteger(queryOptions.limit ?? 20, "limit");
      const offset = normalizeOffset(queryOptions.offset ?? 0);
      const pagefindOptions = engineOptions(queryOptions);
      const api = await getApi();
      const response = await api.search(term, pagefindOptions);
      const handles = response.results.slice(offset, offset + limit);
      const results = await Promise.all(handles.map(loadResult));
      return {
        results,
        total: response.results.length,
        unfilteredTotal: response.unfilteredResultCount,
        filters: response.filters,
        totalFilters: response.totalFilters,
        timings: combineTimings(response.timings),
      } satisfies SearchResponse;
    },

    async preload(term, queryOptions = {}) {
      if (typeof term !== "string") throw new TypeError("Search preload term must be a string");
      const pagefindOptions = engineOptions(queryOptions);
      const api = await getApi();
      await api.preload(term, pagefindOptions);
    },

    async filters() {
      const api = await getApi();
      return api.filters();
    },

    async destroy() {
      if (!loaded) return;
      const current = await loaded;
      loaded = undefined;
      await current.api.destroy();
    },
  };
}

function engineOptions(options: Pick<SearchQueryOptions, "filters" | "sort">) {
  if (options.sort) {
    const entries = Object.entries(options.sort);
    if (entries.length !== 1) {
      throw new TypeError("Search sort must contain exactly one field");
    }
    const [field, direction] = entries[0]!;
    if (!field.trim() || (direction !== "asc" && direction !== "desc")) {
      throw new TypeError("Search sort must use a non-empty field and asc or desc direction");
    }
  }
  return {
    ...(options.filters ? { filters: options.filters } : {}),
    ...(options.sort ? { sort: options.sort } : {}),
  };
}

async function loadResult(handle: PagefindResultHandle): Promise<SearchResult> {
  const data = await handle.data();
  return {
    id: handle.id,
    score: handle.score,
    url: data.url,
    title: data.meta.title || data.sub_results[0]?.title || data.url,
    excerpt: data.excerpt,
    plainExcerpt: data.plain_excerpt,
    content: data.content,
    wordCount: data.word_count,
    words: handle.words,
    matchedMetaFields: handle.matchedMetaFields ?? [],
    meta: data.meta,
    filters: data.filters,
    subResults: data.sub_results.map((result) => ({
      title: result.title,
      url: result.url,
      excerpt: result.excerpt,
      plainExcerpt: result.plain_excerpt,
    })),
  };
}

function combineTimings(timings: PagefindSearchResponse["timings"]): SearchResponse["timings"] {
  if (!Array.isArray(timings)) return timings;
  return timings.reduce(
    (total, value) => ({
      preload: total.preload + value.preload,
      search: total.search + value.search,
      total: total.total + value.total,
    }),
    { preload: 0, search: 0, total: 0 },
  );
}

function normalizeBundlePath(value: string): string {
  if (typeof value !== "string" || !value.trim()) {
    throw new TypeError("Search bundlePath must be a non-empty URL path");
  }
  const normalized = value.trim();
  return normalized.endsWith("/") ? normalized : `${normalized}/`;
}

function normalizePositiveInteger(value: number, label: string): number {
  if (!Number.isInteger(value) || value < 1) {
    throw new TypeError(`Search ${label} must be a positive integer`);
  }
  return value;
}

function normalizeOffset(value: number): number {
  if (!Number.isInteger(value) || value < 0) {
    throw new TypeError("Search offset must be a non-negative integer");
  }
  return value;
}
