import type {
  FarmSearchClient,
  FarmSearchPublicConfig,
  SearchClientOptions,
  SearchFilterCounts,
  SearchQueryOptions,
  SearchResponse,
  SearchResult,
} from "./types.js";

interface PagefindSearchFragment {
  url: string;
  content: string;
  excerpt: string;
  plain_excerpt: string;
  word_count: number;
  filters: Record<string, string[]>;
  meta: Record<string, string>;
  sub_results: Array<{
    title: string;
    url: string;
    excerpt: string;
    plain_excerpt: string;
  }>;
}

interface PagefindResultHandle {
  id: string;
  score: number;
  words: number[];
  matchedMetaFields?: string[];
  data(): Promise<PagefindSearchFragment>;
}

interface PagefindSearchResponse {
  results: PagefindResultHandle[];
  unfilteredResultCount: number;
  filters: SearchFilterCounts;
  totalFilters: SearchFilterCounts;
  timings:
    | { preload: number; search: number; total: number }
    | Array<{
        preload: number;
        search: number;
        total: number;
      }>;
}

export interface PagefindBrowserApi {
  options(options: Record<string, unknown>): Promise<void>;
  init(): Promise<void>;
  search(term: string | null, options?: Record<string, unknown>): Promise<PagefindSearchResponse>;
  preload(term: string, options?: Record<string, unknown>): Promise<void>;
  filters(): Promise<SearchFilterCounts>;
  destroy(): Promise<void>;
}

export interface PagefindBrowserModule extends PagefindBrowserApi {
  createInstance?(
    options?: Record<string, unknown>,
  ): PagefindBrowserApi | Promise<PagefindBrowserApi>;
}

export type PagefindModuleLoader = (url: string) => Promise<PagefindBrowserModule>;

export function createSearchClient(
  resolveConfig: () => FarmSearchPublicConfig,
  options: SearchClientOptions,
  loadModule: PagefindModuleLoader,
): FarmSearchClient {
  interface ActiveInstance {
    api: PagefindBrowserApi;
    bundlePath: string;
    /** Calls currently running against this instance. */
    uses: number;
    /** A retired instance accepts no new calls and is destroyed once drained. */
    retired: boolean;
    drained?: Promise<void>;
    resolveDrained?: () => void;
  }

  let loading: Promise<ActiveInstance> | undefined;

  /**
   * Stop handing this instance out and destroy it once every in-flight call
   * has released it. Destroying eagerly is the bug this replaces: a
   * bundle-path change or destroy() could tear the engine down under a
   * search(), preload(), or filters() call that had already resolved it.
   */
  const retire = (instance: ActiveInstance): Promise<void> => {
    if (!instance.retired) {
      instance.retired = true;
      instance.drained = (async () => {
        if (instance.uses > 0) {
          await new Promise<void>((resolve) => {
            instance.resolveDrained = resolve;
          });
        }
        await instance.api.destroy();
      })();
    }
    return instance.drained!;
  };

  const release = (instance: ActiveInstance): void => {
    instance.uses -= 1;
    if (instance.retired && instance.uses === 0) instance.resolveDrained?.();
  };

  const getInstance = async (): Promise<ActiveInstance> => {
    const config = resolveConfig();
    if (!config.available && !options.bundlePath) {
      throw new Error(
        "[farm:search] The search index is generated by production builds. " +
          "Run farm build and serve the production output before searching.",
      );
    }

    const bundlePath = normalizeBundlePath(options.bundlePath ?? config.bundlePath);
    if (!loading) {
      const attempt: Promise<ActiveInstance> = loadModule(`${bundlePath}pagefind.js`)
        .then(async (module) => {
          const highlightParam =
            options.highlightParam === false
              ? undefined
              : (options.highlightParam ?? config.highlightParam);
          const pagefindOptions = {
            basePath: bundlePath,
            excerptLength: normalizePositiveInteger(
              options.excerptLength ?? config.excerptLength,
              "excerptLength",
            ),
            ...(highlightParam ? { highlightParam } : {}),
          };
          const api = module.createInstance ? await module.createInstance(pagefindOptions) : module;
          if (!module.createInstance) await api.options(pagefindOptions);
          await api.init();
          return { api, bundlePath, uses: 0, retired: false } satisfies ActiveInstance;
        })
        .catch((error) => {
          if (loading === attempt) loading = undefined;
          throw error;
        });
      loading = attempt;
    }

    const attempt = loading;
    const current = await attempt;
    if (current.bundlePath !== bundlePath) {
      // Only clear our own load: a concurrent caller that noticed the same
      // stale bundle may already have started the replacement.
      if (loading === attempt) loading = undefined;
      // Drain the old engine in the background; the swap must not wait for
      // calls that are still finishing against it. Its destroy() failure has
      // no caller to surface to here — an explicit destroy() still reports it.
      void retire(current).catch(() => {});
      return getInstance();
    }
    return current;
  };

  /** Resolve an instance and hold it for the duration of one call. */
  const withApi = async <T>(run: (api: PagefindBrowserApi) => Promise<T>): Promise<T> => {
    for (;;) {
      const instance = await getInstance();
      instance.uses += 1;
      if (instance.retired) {
        // Retired between resolving and acquiring; hand it back and take the
        // replacement instead of running against an engine that may already
        // be destroyed.
        release(instance);
        continue;
      }
      try {
        return await run(instance.api);
      } finally {
        release(instance);
      }
    }
  };

  return {
    async search(term, queryOptions = {}) {
      if (term !== null && typeof term !== "string") {
        throw new TypeError("Search term must be a string or null");
      }
      const limit = normalizePositiveInteger(queryOptions.limit ?? 20, "limit");
      const offset = normalizeOffset(queryOptions.offset ?? 0);
      const pagefindOptions = engineOptions(queryOptions);
      // Result fragments load lazily, so the instance stays held until they
      // have loaded too, not just through the initial query.
      return withApi(async (api) => {
        const response = await api.search(term, pagefindOptions);
        const handles = response.results.slice(offset, offset + limit);
        const results = await Promise.all(handles.map(loadResult));
        return {
          results,
          total: response.results.length,
          unfilteredTotal: response.unfilteredResultCount,
          filters: response.filters,
          totalFilters: response.totalFilters,
          timings: combineTimings(response.timings),
        } satisfies SearchResponse;
      });
    },

    async preload(term, queryOptions = {}) {
      if (typeof term !== "string") throw new TypeError("Search preload term must be a string");
      const pagefindOptions = engineOptions(queryOptions);
      await withApi((api) => api.preload(term, pagefindOptions));
    },

    async filters() {
      return withApi((api) => api.filters());
    },

    async destroy() {
      if (!loading) return;
      const attempt = loading;
      const current = await attempt.catch(() => undefined);
      if (loading === attempt) loading = undefined;
      if (current) await retire(current);
    },
  };
}

function engineOptions(options: Pick<SearchQueryOptions, "filters" | "sort">) {
  if (options.sort) {
    const entries = Object.entries(options.sort);
    if (entries.length !== 1) {
      throw new TypeError("Search sort must contain exactly one field");
    }
    const [field, direction] = entries[0]!;
    if (!field.trim() || (direction !== "asc" && direction !== "desc")) {
      throw new TypeError("Search sort must use a non-empty field and asc or desc direction");
    }
  }
  return {
    ...(options.filters ? { filters: options.filters } : {}),
    ...(options.sort ? { sort: options.sort } : {}),
  };
}

async function loadResult(handle: PagefindResultHandle): Promise<SearchResult> {
  const data = await handle.data();
  return {
    id: handle.id,
    score: handle.score,
    url: data.url,
    title: data.meta.title || data.sub_results[0]?.title || data.url,
    excerpt: data.excerpt,
    plainExcerpt: data.plain_excerpt,
    content: data.content,
    wordCount: data.word_count,
    words: handle.words,
    matchedMetaFields: handle.matchedMetaFields ?? [],
    meta: data.meta,
    filters: data.filters,
    subResults: data.sub_results.map((result) => ({
      title: result.title,
      url: result.url,
      excerpt: result.excerpt,
      plainExcerpt: result.plain_excerpt,
    })),
  };
}

function combineTimings(timings: PagefindSearchResponse["timings"]): SearchResponse["timings"] {
  if (!Array.isArray(timings)) return timings;
  return timings.reduce(
    (total, value) => ({
      preload: total.preload + value.preload,
      search: total.search + value.search,
      total: total.total + value.total,
    }),
    { preload: 0, search: 0, total: 0 },
  );
}

function normalizeBundlePath(value: string): string {
  if (typeof value !== "string" || !value.trim()) {
    throw new TypeError("Search bundlePath must be a non-empty URL path");
  }
  const normalized = value.trim();
  return normalized.endsWith("/") ? normalized : `${normalized}/`;
}

function normalizePositiveInteger(value: number, label: string): number {
  if (!Number.isInteger(value) || value < 1) {
    throw new TypeError(`Search ${label} must be a positive integer`);
  }
  return value;
}

function normalizeOffset(value: number): number {
  if (!Number.isInteger(value) || value < 0) {
    throw new TypeError("Search offset must be a non-negative integer");
  }
  return value;
}
