/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { GET as GET_guestbook } from "../app/api/guestbook/route";
import type { POST as POST_guestbook } from "../app/api/guestbook/route";

// Type-only representation of your API routes
export type APIRouter = {
  guestbook: {
    get: typeof GET_guestbook;
    post: typeof POST_guestbook;
  };
};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/guestbook",
    methods: ["GET", "POST"],
  },
] as const;
