/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_guestbook } from "../app/api/guestbook/route";
import type { POST as POST_guestbook } from "../app/api/guestbook/route";

// Type-only representation of your API routes
export type APIRouter = {
  guestbook: {
    get: typeof GET_guestbook;
    post: typeof POST_guestbook;
  };
};
