/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 * Generated at: 2026-07-20T22:30:33.401Z
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_locale } from "../app/api/locale/route";

// Type-only representation of your API routes
export type APIRouter = {
  locale: {
    get: typeof GET_locale;
  };
};
