import { defineConfig } from "bumpp";

export default defineConfig({
  commit: "chore: release v%s",
  tag: "v%s",
  push: true,
  files: [
    "packages/farm/package.json",
    "packages/create-farm-app/package.json",
    "packages/farm-ai/package.json",
    "packages/farm-auth0/package.json",
    "packages/farm-authjs/package.json",
    "packages/farm-autumn/package.json",
    "packages/farm-better-auth/package.json",
    "packages/farm-cf-agent/package.json",
    "packages/farm-clerk/package.json",
    "packages/farm-cli/package.json",
    "packages/farm-email/package.json",
    "packages/farm-eve/package.json",
    "packages/farm-integration-utils/package.json",
    "packages/farm-integrations/package.json",
    "packages/farm-jobs/package.json",
    "packages/farm-polar/package.json",
    "packages/farm-preview-gateway/package.json",
    "packages/farm-stripe/package.json",
    "packages/farm-supabase/package.json",
    "packages/farm-unkey/package.json",
    "packages/farm-workos/package.json",
    "packages/farmjs-plugin/package.json",
  ],
  execute: "pnpm build",
});
