/**
 * Generated by Farm.js. Do not edit.
 * Contains project-specific route, environment, content, and internationalization types.
 */

import "@farm.js/core/image";
import "@farm.js/core/css";

/**
 * Auto-generated route types from src/app.
 * Link href and route component props are typed automatically from generated declarations.
 * Regenerated on dev start and when routes change.
 * Set suppressLintOnLink: true in farm.config.ts to accept any string on Link href.
 */
export type RoutePath =
  | "/"
  | "/docs"
  | `/docs/${string}`
  | "/docs/after"
  | "/docs/api-client"
  | "/docs/api-routes"
  | "/docs/auth"
  | "/docs/cache-ppr"
  | "/docs/cli"
  | "/docs/configuration"
  | "/docs/cron"
  | "/docs/deployment"
  | "/docs/devtools"
  | "/docs/docs-engine"
  | "/docs/environment-functions"
  | "/docs/examples"
  | "/docs/fonts"
  | "/docs/getting-started"
  | "/docs/images"
  | "/docs/integrations"
  | "/docs/integrations/auth"
  | "/docs/integrations/auth/auth0"
  | "/docs/integrations/auth/authjs"
  | "/docs/integrations/auth/better-auth"
  | "/docs/integrations/auth/clerk"
  | "/docs/integrations/auth/supabase"
  | "/docs/integrations/auth/workos"
  | "/docs/integrations/autumn"
  | "/docs/integrations/cf-agent"
  | "/docs/integrations/custom"
  | "/docs/integrations/email"
  | "/docs/integrations/eve"
  | "/docs/integrations/inngest"
  | "/docs/integrations/jobs"
  | "/docs/integrations/orm-storage"
  | "/docs/integrations/polar"
  | "/docs/integrations/stripe"
  | "/docs/integrations/trigger"
  | "/docs/integrations/ui-registry"
  | "/docs/integrations/unkey"
  | "/docs/internationalization"
  | "/docs/layers"
  | "/docs/layouts"
  | "/docs/markdown"
  | "/docs/middleware"
  | "/docs/migrations"
  | "/docs/migrations/nextjs"
  | "/docs/migrations/nuxt"
  | "/docs/migrations/sveltekit"
  | "/docs/migrations/tanstack"
  | "/docs/observability"
  | "/docs/openapi"
  | "/docs/plugins"
  | "/docs/plugins/analyzer"
  | "/docs/plugins/client"
  | "/docs/plugins/content"
  | "/docs/plugins/create-plugin"
  | "/docs/plugins/hints"
  | "/docs/plugins/msw"
  | "/docs/plugins/partytown"
  | "/docs/plugins/pwa"
  | "/docs/plugins/sentry"
  | "/docs/plugins/webmcp"
  | "/docs/preview"
  | "/docs/project-structure"
  | "/docs/query"
  | "/docs/reference"
  | "/docs/renderers"
  | "/docs/renderers/preact"
  | "/docs/renderers/react"
  | "/docs/renderers/solid"
  | "/docs/renderers/svelte"
  | "/docs/renderers/vue"
  | "/docs/route-runtime"
  | "/docs/routing"
  | "/docs/server-queries"
  | "/docs/server-rendering"
  | "/docs/storage"
  | "/docs/telemetry"
  | "/docs/testing"
  | "/docs/themes"
  | "/telemetry";
export type RoutePattern =
  | "/"
  | "/docs"
  | "/docs/[...docs]"
  | "/docs/after"
  | "/docs/api-client"
  | "/docs/api-routes"
  | "/docs/auth"
  | "/docs/cache-ppr"
  | "/docs/cli"
  | "/docs/configuration"
  | "/docs/cron"
  | "/docs/deployment"
  | "/docs/devtools"
  | "/docs/docs-engine"
  | "/docs/environment-functions"
  | "/docs/examples"
  | "/docs/fonts"
  | "/docs/getting-started"
  | "/docs/images"
  | "/docs/integrations"
  | "/docs/integrations/auth"
  | "/docs/integrations/auth/auth0"
  | "/docs/integrations/auth/authjs"
  | "/docs/integrations/auth/better-auth"
  | "/docs/integrations/auth/clerk"
  | "/docs/integrations/auth/supabase"
  | "/docs/integrations/auth/workos"
  | "/docs/integrations/autumn"
  | "/docs/integrations/cf-agent"
  | "/docs/integrations/custom"
  | "/docs/integrations/email"
  | "/docs/integrations/eve"
  | "/docs/integrations/inngest"
  | "/docs/integrations/jobs"
  | "/docs/integrations/orm-storage"
  | "/docs/integrations/polar"
  | "/docs/integrations/stripe"
  | "/docs/integrations/trigger"
  | "/docs/integrations/ui-registry"
  | "/docs/integrations/unkey"
  | "/docs/internationalization"
  | "/docs/layers"
  | "/docs/layouts"
  | "/docs/markdown"
  | "/docs/middleware"
  | "/docs/migrations"
  | "/docs/migrations/nextjs"
  | "/docs/migrations/nuxt"
  | "/docs/migrations/sveltekit"
  | "/docs/migrations/tanstack"
  | "/docs/observability"
  | "/docs/openapi"
  | "/docs/plugins"
  | "/docs/plugins/analyzer"
  | "/docs/plugins/client"
  | "/docs/plugins/content"
  | "/docs/plugins/create-plugin"
  | "/docs/plugins/hints"
  | "/docs/plugins/msw"
  | "/docs/plugins/partytown"
  | "/docs/plugins/pwa"
  | "/docs/plugins/sentry"
  | "/docs/plugins/webmcp"
  | "/docs/preview"
  | "/docs/project-structure"
  | "/docs/query"
  | "/docs/reference"
  | "/docs/renderers"
  | "/docs/renderers/preact"
  | "/docs/renderers/react"
  | "/docs/renderers/solid"
  | "/docs/renderers/svelte"
  | "/docs/renderers/vue"
  | "/docs/route-runtime"
  | "/docs/routing"
  | "/docs/server-queries"
  | "/docs/server-rendering"
  | "/docs/storage"
  | "/docs/telemetry"
  | "/docs/testing"
  | "/docs/themes"
  | "/telemetry";
export type RouteModulePattern =
  | "/"
  | "/docs"
  | "/docs/[...docs]"
  | "/docs/after"
  | "/docs/api-client"
  | "/docs/api-routes"
  | "/docs/auth"
  | "/docs/cache-ppr"
  | "/docs/cli"
  | "/docs/configuration"
  | "/docs/cron"
  | "/docs/deployment"
  | "/docs/devtools"
  | "/docs/docs-engine"
  | "/docs/environment-functions"
  | "/docs/examples"
  | "/docs/fonts"
  | "/docs/getting-started"
  | "/docs/images"
  | "/docs/integrations"
  | "/docs/integrations/auth"
  | "/docs/integrations/auth/auth0"
  | "/docs/integrations/auth/authjs"
  | "/docs/integrations/auth/better-auth"
  | "/docs/integrations/auth/clerk"
  | "/docs/integrations/auth/supabase"
  | "/docs/integrations/auth/workos"
  | "/docs/integrations/autumn"
  | "/docs/integrations/cf-agent"
  | "/docs/integrations/custom"
  | "/docs/integrations/email"
  | "/docs/integrations/eve"
  | "/docs/integrations/inngest"
  | "/docs/integrations/jobs"
  | "/docs/integrations/orm-storage"
  | "/docs/integrations/polar"
  | "/docs/integrations/stripe"
  | "/docs/integrations/trigger"
  | "/docs/integrations/ui-registry"
  | "/docs/integrations/unkey"
  | "/docs/internationalization"
  | "/docs/layers"
  | "/docs/layouts"
  | "/docs/markdown"
  | "/docs/middleware"
  | "/docs/migrations"
  | "/docs/migrations/nextjs"
  | "/docs/migrations/nuxt"
  | "/docs/migrations/sveltekit"
  | "/docs/migrations/tanstack"
  | "/docs/observability"
  | "/docs/openapi"
  | "/docs/plugins"
  | "/docs/plugins/analyzer"
  | "/docs/plugins/client"
  | "/docs/plugins/content"
  | "/docs/plugins/create-plugin"
  | "/docs/plugins/hints"
  | "/docs/plugins/msw"
  | "/docs/plugins/partytown"
  | "/docs/plugins/pwa"
  | "/docs/plugins/sentry"
  | "/docs/plugins/webmcp"
  | "/docs/preview"
  | "/docs/project-structure"
  | "/docs/query"
  | "/docs/reference"
  | "/docs/renderers"
  | "/docs/renderers/preact"
  | "/docs/renderers/react"
  | "/docs/renderers/solid"
  | "/docs/renderers/svelte"
  | "/docs/renderers/vue"
  | "/docs/route-runtime"
  | "/docs/routing"
  | "/docs/server-queries"
  | "/docs/server-rendering"
  | "/docs/storage"
  | "/docs/telemetry"
  | "/docs/testing"
  | "/docs/themes"
  | "/telemetry";
declare module "@farm.js/core/client" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

declare module "@farm.js/core" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
  // Ensure root import ("@farm.js/core") uses the same typed Link signature as client entry.
  const Link: typeof import("@farm.js/core/client").Link;
}

// Internal declaration path used by @farm.js/core root type re-exports.
declare module "@farm.js/core/dist/client.js" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

declare global {
  namespace FarmJS {
    interface RouteRegistry {
      pattern: import("./farm").RouteModulePattern;
    }
  }
}

/**
 * Auto-generated env types from farm.config.
 * Regenerated on dev start, build, and farm generate.
 */
import type FarmConfig from "../farm.config";
import type { InferEnv } from "@farm.js/core/env";

type FarmConfigEnv = typeof FarmConfig extends { env?: infer TEnv } ? NonNullable<TEnv> : never;
type FarmResolvedEnv = [FarmConfigEnv] extends [never]
  ? { server: {}; public: {} }
  : InferEnv<FarmConfigEnv>;

declare module "@farm.js/core/env" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

declare module "@farm.js/core" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

/**
 * Auto-generated content collection types from Farm layers and farm.config.
 * Regenerated on dev start, build, and farm generate.
 */
import type FarmContentConfig0 from "../farm.config";

type FarmContentPluginFromConfig<TConfig> = TConfig extends {
  plugins?: readonly (infer TPlugin)[];
}
  ? Extract<TPlugin, { readonly __farmContentRegistry: Record<string, unknown> }>
  : never;
type ContentRegistryFromConfig<TConfig> =
  FarmContentPluginFromConfig<TConfig> extends {
    readonly __farmContentRegistry: infer TRegistry;
  }
    ? TRegistry
    : never;
type FarmContentUnionToIntersection<TValue> = (
  TValue extends unknown ? (value: TValue) => void : never
) extends (value: infer TIntersection) => void
  ? TIntersection
  : never;
type FarmContentRegistry0 = ContentRegistryFromConfig<typeof FarmContentConfig0>;

type FarmResolvedContentRegistry = [FarmContentRegistry0] extends [never]
  ? {}
  : FarmContentUnionToIntersection<FarmContentRegistry0>;

declare global {
  namespace FarmJS {
    interface ContentRegistry {
      collections: FarmResolvedContentRegistry;
    }
  }
}
