
// Auto-generated by Farm.js
// This handler intercepts all /api/* requests
import { defineEventHandler, getHeaders, readBody, setHeaders, setResponseStatus, getRequestURL } from 'h3';
import type { H3Event } from 'h3';
import { farmRegistry } from '../farm-registry';

export default defineEventHandler(async (event: H3Event) => {
  // Get URL using H3's abstraction (works in all environments)
  const url = getRequestURL(event);
  const urlPath = url.pathname;
  
  // Only handle API routes - for Vercel, Nitro routes /api/* to this handler
  // According to https://nitro.build/deploy/providers/vercel
  // This handler should process all /api/* routes
  if (!urlPath.startsWith('/api/')) {
    // Return undefined to let Nitro's routing system handle non-API routes
    return undefined;
  }
  
  // Ensure registry is populated (lazy initialization)
  // In serverless environments, the registry needs to be initialized at runtime
  if (!farmRegistry.apiRouteManager) {
    // Try to initialize from global if available (set during build)
    if (typeof globalThis !== 'undefined' && (globalThis as any).__FARM_REGISTRY__) {
      Object.assign(farmRegistry, (globalThis as any).__FARM_REGISTRY__);
    }
    // If still not available, try the init function (if it exists)
    if (!farmRegistry.apiRouteManager && (farmRegistry as any).__INIT__) {
      (farmRegistry as any).__INIT__();
    }
  }
  
  const apiRouteManager = farmRegistry.apiRouteManager;
  if (!apiRouteManager) {
    console.error('API route manager not initialized. Registry keys:', Object.keys(farmRegistry));
    setResponseStatus(event, 500);
    return { error: 'API route manager not initialized. Please check server logs.' };
  }
  
  const startTime = Date.now();
  const method = event.method || 'GET';
  const host = url.host || 'localhost';
  
  // Log API request (only in development)
  if (process.env.NODE_ENV === 'development' || !process.env.NODE_ENV) {
    try {
      const pc = await import('picocolors');
      const log = [
        pc.default.dim('[') + pc.default.bold(pc.default.blue('FARM')) + pc.default.dim(']'),
        pc.default.dim('[') + pc.default.bold(pc.default.white(method.padEnd(3))) + pc.default.dim(']'),
        pc.default.cyan('[API]'),
        pc.default.gray(`${url.protocol}//${host}${urlPath}`),
      ].join(' ');
      console.log(log);
    } catch {
      // picocolors not available, use simple log
      console.log(`[FARM] [${method}] [API] ${urlPath}`);
    }
  }
  
  try {
    // Convert H3 event to Web Request using H3 abstractions
    const protocol = url.protocol.replace(':', '') || 'http';
    const host = url.host || 'localhost';
    const fullUrl = url.toString();
    
    const headers = new Headers();
    const h3Headers = getHeaders(event);
    
    for (const [key, value] of Object.entries(h3Headers)) {
      if (value) {
        headers.set(key, Array.isArray(value) ? value.join(', ') : String(value));
      }
    }
    
    // Get body
    let body: string | undefined;
    const method = event.method || 'GET';
    if (method !== 'GET' && method !== 'HEAD') {
      const bodyData = await readBody(event).catch(() => undefined);
      if (bodyData) {
        body = typeof bodyData === 'string' ? bodyData : JSON.stringify(bodyData);
      }
    }
    
    // Create Web Request
    const request = new Request(fullUrl, {
      method,
      headers,
      body: body || undefined,
    });
    
    // Call better-call handler
    const betterCallHandler = apiRouteManager.getHandler();
    if (!betterCallHandler) {
      setResponseStatus(event, 404);
      return { error: 'API handler not found' };
    }
    
    const response = await betterCallHandler(request);
    
    // Log API response (only in development)
    if (process.env.NODE_ENV === 'development' || !process.env.NODE_ENV) {
      const duration = Date.now() - startTime;
      const status = response.status;
      try {
        const pc = await import('picocolors');
        let statusColor = pc.default.green;
        if (status >= 500) statusColor = pc.default.red;
        else if (status >= 400) statusColor = pc.default.yellow;
        else if (status >= 300) statusColor = pc.default.cyan;

        const log = [
          pc.default.dim('[') + pc.default.bold(pc.default.blue('FARM')) + pc.default.dim(']'),
          status >= 400 ? pc.default.red('✗') : pc.default.green('✓'),
          pc.default.cyan('[API]'),
          pc.default.gray(urlPath),
          pc.default.dim('-'),
          statusColor(status.toString()),
          pc.default.dim(`(${duration}ms)`),
        ].join(' ');
        console.log(log);
      } catch {
        // picocolors not available, use simple log
        console.log(`[FARM] [${method}] [API] ${urlPath} - ${response.status} (${duration}ms)`);
      }
    }
    
    // Convert Response to H3 response
    const responseBody = await response.text();
    const responseHeaders: Record<string, string> = {};
    response.headers.forEach((value, key) => {
      responseHeaders[key] = value;
    });
    
    setResponseStatus(event, response.status);
    setHeaders(event, responseHeaders);
    
    // Return the response body
    try {
      const parsed = JSON.parse(responseBody);
      return parsed;
    } catch {
      return responseBody;
    }
  } catch (error: any) {
    console.error('API handler error:', error);
    setResponseStatus(event, 500);
    return {
      error: error.message || 'Internal Server Error',
    };
  }
});
