// Auto-generated by Farm.js
// Runtime registry for route managers and renderers
export const farmRegistry: {
  apiRouteManager?: any;
  routeManager?: any;
  serverRenderer?: any;
  clientManifest?: any;
  routePaths?: Record<string, string>;
} = {
  routePaths: {
    "/": "page.js",
    "/api-demo": "api-demo/page.js",
    "/api-demo-client": "api-demo-client/page.js",
    "/about": "about/page.js",
    "/farm-query-client-demo": "farm-query-client-demo/page.js",
    "/farm-query-demo": "farm-query-demo/page.js",
    "/contact": "contact/page.js",
    "/query-state-demo": "query-state-demo/page.js",
    "/query-test": "query-test/page.js",
    "/users/[id]": "users/[id]/page.js",
  },
};
