/**
 * Generated by Farm.js. Do not edit.
 * Contains project-specific route, environment, and internationalization types.
 */

import "@farm.js/core/image";

/**
 * Auto-generated route types from src/app.
 * Link href is typed automatically via module augmentation. Regenerated on dev start and when routes change.
 * Set suppressLintOnLink: true in farm.config.ts to accept any string on Link href.
 */
export type RoutePath = "/" | "/about" | "/api-demo" | "/api-demo-client" | "/api-demo-client-advanced" | "/boundaries/error" | "/boundaries/loading" | "/boundaries/suspense" | "/contact" | "/docs" | `/docs/${string}` | "/docs/getting-started" | "/docs/reference" | "/farm-query-client-demo" | "/farm-query-demo" | "/feature-lab" | "/feature-lab/integrations" | "/feature-lab/layer" | "/feature-lab/login" | `/feature-lab/metadata/${string}` | `/feature-lab/products/${string}` | "/feature-lab/static-metadata" | `/feature-lab/static/${string}` | "/markdown" | "/optional-catchall" | `/optional-catchall/${string}` | "/ppr-demo" | "/prefetch-e2e" | "/query-demo" | "/slot-lab" | `/slot-lab/photo/${string}` | "/storage-demo" | "/store-e2e" | `/users/${string}`;
export type RoutePattern = "/" | "/about" | "/api-demo" | "/api-demo-client" | "/api-demo-client-advanced" | "/boundaries/error" | "/boundaries/loading" | "/boundaries/suspense" | "/contact" | "/docs" | "/docs/[...docs]" | "/docs/getting-started" | "/docs/reference" | "/farm-query-client-demo" | "/farm-query-demo" | "/feature-lab" | "/feature-lab/integrations" | "/feature-lab/layer" | "/feature-lab/login" | "/feature-lab/metadata/[id]" | "/feature-lab/products/[id]" | "/feature-lab/static-metadata" | "/feature-lab/static/[slug]" | "/markdown" | "/optional-catchall/[[...slug]]" | "/ppr-demo" | "/prefetch-e2e" | "/query-demo" | "/slot-lab" | "/slot-lab/photo/[id]" | "/storage-demo" | "/store-e2e" | "/users/[id]";
declare module "@farm.js/core/client" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

declare module "@farm.js/core" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
  // Ensure root import ("@farm.js/core") uses the same typed Link signature as client entry.
  const Link: typeof import("@farm.js/core/client").Link;
}

// Internal declaration path used by @farm.js/core root type re-exports.
declare module "@farm.js/core/dist/client.js" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

/**
 * Auto-generated env types from Farm layers and farm.config.
 * Regenerated on dev start, build, and farm generate.
 */
import type FarmConfig0 from "../layers/framework-features/farm.config";
import type FarmConfig1 from "../farm.config";
import type { InferEnv } from "@farm.js/core/env";

type MergeFarmEnv<TBase, TOverride> = {
  server: Omit<TBase extends { server: infer T } ? T : {}, keyof (TOverride extends { server: infer T } ? T : {})> &
    (TOverride extends { server: infer T } ? T : {});
  public: Omit<TBase extends { public: infer T } ? T : {}, keyof (TOverride extends { public: infer T } ? T : {})> &
    (TOverride extends { public: infer T } ? T : {});
};

type FarmConfigEnv0 = typeof FarmConfig0 extends { env?: infer TEnv }
  ? NonNullable<TEnv>
  : never;
type FarmResolvedEnv0 = [FarmConfigEnv0] extends [never]
  ? { server: {}; public: {} }
  : InferEnv<FarmConfigEnv0>;

type FarmConfigEnv1 = typeof FarmConfig1 extends { env?: infer TEnv }
  ? NonNullable<TEnv>
  : never;
type FarmResolvedEnv1 = [FarmConfigEnv1] extends [never]
  ? { server: {}; public: {} }
  : InferEnv<FarmConfigEnv1>;
type FarmMergedEnv1 = MergeFarmEnv<FarmResolvedEnv0, FarmResolvedEnv1>;

type FarmResolvedEnv = FarmMergedEnv1;

declare module "@farm.js/core/env" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

declare module "@farm.js/core" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

export {};
