import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ResolvedPwaOptions } from "./config.js";

export interface PwaBuildInput {
  outputDir: string;
  publicDir?: string;
  preset: string;
  basePath: string;
  options: ResolvedPwaOptions;
}

export interface PwaBuildResult {
  workerPath: string;
  workerUrl: string;
  precacheUrls: string[];
  staticRoutes: Record<string, string>;
  cacheId: string;
}

const PRECACHE_EXTENSIONS = new Set([
  ".css",
  ".js",
  ".mjs",
  ".otf",
  ".ttf",
  ".wasm",
  ".webmanifest",
  ".woff",
  ".woff2",
]);

export async function writePwaBuildArtifacts(input: PwaBuildInput): Promise<PwaBuildResult> {
  const publicDir = input.publicDir ?? resolvePwaPublicDir(input.outputDir, input.preset);
  const files = await walkFiles(publicDir);
  const staticRouteFiles = resolveStaticRouteFiles(files);
  const basePath = normalizeBasePath(input.basePath);
  const workerRelativePath = path.posix.join(basePath.replace(/^\//, ""), "sw.js");
  const selectedRoutes = selectStaticRoutes(
    staticRouteFiles,
    input.options.cache.staticRoutes,
    basePath,
  );

  const configuredOfflineRoute = input.options.offline;
  const offlineRoute = configuredOfflineRoute
    ? withBasePath(configuredOfflineRoute, basePath)
    : false;
  if (offlineRoute && configuredOfflineRoute) {
    const emittedOfflineFile =
      staticRouteFiles[configuredOfflineRoute] ?? staticRouteFiles[offlineRoute];
    if (!emittedOfflineFile) {
      throw new Error(
        `[farm:pwa] Offline route ${JSON.stringify(input.options.offline)} was not emitted as a static page. ` +
          "Create that page as a static Farm route so it can be precached.",
      );
    }
    selectedRoutes[offlineRoute] = emittedOfflineFile;
  }

  const assetFiles = files.filter(
    (file) =>
      file !== workerRelativePath && PRECACHE_EXTENSIONS.has(path.extname(file).toLowerCase()),
  );
  const precacheFiles = [...new Set([...assetFiles, ...Object.values(selectedRoutes)])].sort();
  const precacheUrls = precacheFiles.map(toPublicUrl);
  const fileHashes = await Promise.all(
    precacheFiles.map(async (file) => {
      const content = await readFile(path.join(publicDir, file));
      return `${file}:${createHash("sha256").update(content).digest("hex")}`;
    }),
  );
  const cacheId = createHash("sha256")
    .update(
      JSON.stringify({
        files: fileHashes,
        routes: selectedRoutes,
        offlineRoute,
        update: input.options.update,
        images: input.options.cache.images,
      }),
    )
    .digest("hex")
    .slice(0, 16);

  const workerPath = path.join(publicDir, ...workerRelativePath.split("/"));
  await mkdir(path.dirname(workerPath), { recursive: true });
  await writeFile(
    workerPath,
    generateServiceWorker({
      cacheId,
      precacheUrls,
      staticRoutes: selectedRoutes,
      offlineRoute,
      update: input.options.update,
      images: input.options.cache.images,
    }),
  );

  return {
    workerPath,
    workerUrl: withBasePath("/sw.js", basePath),
    precacheUrls,
    staticRoutes: selectedRoutes,
    cacheId,
  };
}

export interface GenerateServiceWorkerOptions {
  cacheId: string;
  precacheUrls: string[];
  staticRoutes: Record<string, string>;
  offlineRoute: string | false;
  update: "prompt" | "auto";
  images: ResolvedPwaOptions["cache"]["images"];
}

export function generateServiceWorker(options: GenerateServiceWorkerOptions): string {
  const routeFiles = Object.fromEntries(
    Object.entries(options.staticRoutes).map(([route, file]) => [route, toPublicUrl(file)]),
  );
  const offlineFile = options.offlineRoute ? (routeFiles[options.offlineRoute] ?? null) : null;

  return `/* Generated by @farm.js/pwa. */
const PRECACHE = ${JSON.stringify(`farm-pwa-precache-${options.cacheId}`)};
const IMAGE_CACHE = "farm-pwa-images-v1";
const PRECACHE_URLS = ${JSON.stringify(options.precacheUrls)};
const PRECACHE_PATHS = new Set(PRECACHE_URLS.map((value) => new URL(value, self.location.origin).pathname));
const STATIC_ROUTES = ${JSON.stringify(routeFiles)};
const OFFLINE_FILE = ${JSON.stringify(offlineFile)};
const IMAGE_OPTIONS = ${JSON.stringify(options.images)};

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(PRECACHE);
    await cache.addAll(PRECACHE_URLS);
    ${options.update === "auto" ? "await self.skipWaiting();" : ""}
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name.startsWith("farm-pwa-precache-") && name !== PRECACHE)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data?.type === "FARM_PWA_SKIP_WAITING") void self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(handleNavigation(request, url));
    return;
  }

  if (PRECACHE_PATHS.has(url.pathname)) {
    event.respondWith(cacheFirst(request));
    return;
  }

  if (IMAGE_OPTIONS && request.destination === "image") {
    event.respondWith(staleWhileRevalidateImage(request));
  }
});

async function cacheFirst(request) {
  const cache = await caches.open(PRECACHE);
  return (await cache.match(request, { ignoreSearch: true })) ?? fetch(request);
}

async function handleNavigation(request, url) {
  const staticFile = STATIC_ROUTES[normalizePathname(url.pathname)];
  if (staticFile) {
    const cached = await caches.match(staticFile, { cacheName: PRECACHE });
    if (cached) return cached;
  }

  try {
    return await fetch(request);
  } catch (error) {
    if (OFFLINE_FILE) {
      const fallback = await caches.match(OFFLINE_FILE, { cacheName: PRECACHE });
      if (fallback) return fallback;
    }
    throw error;
  }
}

async function staleWhileRevalidateImage(request) {
  if (request.headers.has("authorization")) return fetch(request);

  const cache = await caches.open(IMAGE_CACHE);
  const cached = await cache.match(request);
  const cachedAt = Number(cached?.headers.get("x-farm-pwa-cached-at") || 0);
  const fresh = cached && Date.now() - cachedAt <= IMAGE_OPTIONS.ttlMs;
  const update = fetchAndCacheImage(request, cache);

  if (fresh) {
    void update.catch(() => undefined);
    return cached;
  }

  try {
    return await update;
  } catch (error) {
    if (cached) return cached;
    throw error;
  }
}

async function fetchAndCacheImage(request, cache) {
  const response = await fetch(request);
  if (!isPublicCacheableImage(response)) return response;

  const headers = new Headers(response.headers);
  headers.set("x-farm-pwa-cached-at", String(Date.now()));
  const stored = new Response(response.clone().body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
  await cache.put(request, stored);
  await trimImageCache(cache, IMAGE_OPTIONS.limit);
  return response;
}

function isPublicCacheableImage(response) {
  if (!response.ok || response.type === "opaque") return false;
  const policy = (response.headers.get("cache-control") || "").toLowerCase();
  return !policy.includes("private") && !policy.includes("no-store") && !policy.includes("no-cache");
}

async function trimImageCache(cache, limit) {
  const keys = await cache.keys();
  if (keys.length <= limit) return;

  const entries = await Promise.all(keys.map(async (request) => {
    const response = await cache.match(request);
    return {
      request,
      cachedAt: Number(response?.headers.get("x-farm-pwa-cached-at") || 0),
    };
  }));
  entries.sort((left, right) => left.cachedAt - right.cachedAt);
  await Promise.all(entries.slice(0, entries.length - limit).map(({ request }) => cache.delete(request)));
}

function normalizePathname(pathname) {
  if (pathname === "/") return pathname;
  return pathname.replace(/\\/+$/, "");
}
`;
}

export function resolvePwaPublicDir(outputDir: string, preset: string): string {
  return path.join(
    outputDir,
    preset === "vercel" || preset === "vercel-edge" ? "static" : "public",
  );
}

export function normalizeBasePath(value: string | undefined): string {
  if (!value || value === "/") return "/";
  return `/${value.replace(/^\/+|\/+$/g, "")}`;
}

export function withBasePath(route: string, basePath: string): string {
  const normalizedBase = normalizeBasePath(basePath);
  const normalizedRoute = route === "/" ? "/" : `/${route.replace(/^\/+|\/+$/g, "")}`;
  if (normalizedBase === "/") return normalizedRoute;
  if (normalizedRoute === normalizedBase || normalizedRoute.startsWith(`${normalizedBase}/`)) {
    return normalizedRoute;
  }
  return normalizedRoute === "/" ? normalizedBase : `${normalizedBase}${normalizedRoute}`;
}

async function walkFiles(root: string): Promise<string[]> {
  const entries = await readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const relative = entry.name;
      if (entry.isDirectory()) {
        return (await walkFiles(path.join(root, entry.name))).map((file) =>
          path.posix.join(relative, file),
        );
      }
      return entry.isFile() ? [relative] : [];
    }),
  );
  return files.flat().sort();
}

function resolveStaticRouteFiles(files: string[]): Record<string, string> {
  const routes: Record<string, string> = {};
  for (const file of files) {
    if (path.extname(file).toLowerCase() !== ".html") continue;
    const normalized = file.replace(/\\/g, "/");
    const withoutIndex = normalized.replace(/(?:^|\/)index\.html$/, "");
    const route = withoutIndex
      ? `/${withoutIndex.replace(/\.html$/, "").replace(/^\/+|\/+$/g, "")}`
      : "/";
    routes[route] = normalized;
  }
  return routes;
}

function selectStaticRoutes(
  emitted: Record<string, string>,
  configured: boolean | string[],
  basePath: string,
): Record<string, string> {
  if (configured === false) return {};
  if (configured === true) {
    return Object.fromEntries(
      Object.entries(emitted).map(([route, file]) => [withBasePath(route, basePath), file]),
    );
  }

  const selected: Record<string, string> = {};
  for (const requested of configured) {
    const route = withBasePath(requested, basePath);
    const emittedFile = emitted[requested] ?? emitted[route];
    if (!emittedFile) {
      throw new Error(
        `[farm:pwa] Static route ${JSON.stringify(requested)} was not found in the production output.`,
      );
    }
    selected[route] = emittedFile;
  }
  return selected;
}

function toPublicUrl(file: string): string {
  return `/${file
    .replace(/\\/g, "/")
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/")}`;
}
