/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_server_status } from "../app/api/server-status/route";

// Type-only representation of your API routes
export type APIRouter = {
  "server-status": {
    get: typeof GET_server_status;
  };
};
