import path from "path";
import {
  collectSchemaDependencies,
  collectSchemaExtensions,
  findSchemaTableOwners,
  orderSchemaOwners,
  loadConfig,
  logger,
  migrateSchemaTables,
  resolveConfig,
} from "@farm.js/core";
import { detectOrmSchemaOwners, renderSchemaExtensionForOrm } from "./generate";

export interface MigrateSchemaOptions {
  root?: string;
  configPath?: string;
  /** Write the statements to this path instead of printing them. */
  write?: string;
  /** Execute the statements. */
  apply?: boolean;
  /**
   * Asked after printing a plan, when there is something to apply. Only the
   * CLI in an interactive terminal passes one; scripts and CI print and stop.
   */
  confirm?: (question: string) => Promise<boolean>;
}

/** A yes/no question in the terminal; anything but "y" or "yes" is no. */
export async function askToConfirm(question: string): Promise<boolean> {
  const { createInterface } = await import("node:readline/promises");
  const terminal = createInterface({ input: process.stdin, output: process.stdout });
  try {
    const answer = await terminal.question(`${question} (y/N) `);
    return /^y(es)?$/iu.test(answer.trim());
  } finally {
    terminal.close();
  }
}

async function loadApp(options: MigrateSchemaOptions) {
  const root = path.resolve(options.root || process.cwd());
  const userConfig = await loadConfig(root, options.configPath, "production");
  if (!userConfig) {
    throw new Error(`No farm.config file was found in ${root}.`);
  }

  const config = await resolveConfig({ ...userConfig, root }, "production");
  return { config, owners: findSchemaTableOwners(config) };
}

/** Names of the plugins in this app that own tables, for help and errors. */
export async function listSchemaTableOwners(options: MigrateSchemaOptions = {}): Promise<string[]> {
  return (await loadApp(options)).owners.map((owner) => owner.name);
}

/**
 * Create the tables one plugin's schema needs.
 *
 * Printing is the default: applying schema changes is a deliberate act, so the
 * command hands back sql to read unless `--apply` is passed.
 */
export async function migrateSchema(
  name: string,
  options: MigrateSchemaOptions = {},
): Promise<void> {
  const { config, owners } = await loadApp(options);
  const owner = owners.find((candidate) => candidate.name === name);

  if (!owner) {
    const available = owners.map((candidate) => candidate.name);
    throw new Error(
      available.length > 0
        ? `No plugin named "${name}" owns tables in this app. Available: ${available.join(", ")}.`
        : `No configured plugin owns tables, so there is nothing to migrate.`,
    );
  }

  let outcome = await migrateOwner(owner, config, options);
  let applied = Boolean(options.apply);
  if (
    !applied &&
    !options.write &&
    outcome.planned > 0 &&
    (await options.confirm?.(`Apply these changes to ${owner.name}'s tables now?`))
  ) {
    outcome = await migrateOwner(owner, config, { ...options, apply: true, confirm: undefined });
    applied = true;
  }
  if (applied && outcome.pending.length > 0) {
    throw new Error(
      `${outcome.pending.length} change(s) ${owner.name} needs are still missing: ${outcome.pending.join(", ")}. See above for why.`,
    );
  }
}

type LoadedApp = Awaited<ReturnType<typeof loadApp>>;

/**
 * One owner's migration, shared by `farm <plugin> migrate` and
 * `farm schema migrate` so the two never behave differently.
 */
async function migrateOwner(
  owner: LoadedApp["owners"][number],
  config: LoadedApp["config"],
  options: MigrateSchemaOptions & { sqlOnly?: boolean },
): Promise<{ pending: string[]; sql: string; created: number; planned: number }> {
  // An ORM's schema owns the app's tables: report the columns an owner adds
  // there instead of altering them behind the ORM's back.
  const ormOwners = detectOrmSchemaOwners(config.root);
  const result = await migrateSchemaTables(owner, {
    config,
    write: options.sqlOnly ? undefined : options.write,
    apply: options.apply,
    extensions: ormOwners.length > 0 ? "report" : "apply",
    // Collecting sql for one combined file: the sql itself is not logged.
    log: (message) => {
      if (options.sqlOnly && message.startsWith("-- Generated by")) return;
      logger.info(message);
    },
  });

  if (ormOwners.length > 0) {
    const missing = new Set(result.extensions.pending);
    for (const extension of collectSchemaExtensions(owner.name, owner.schema, owner.models)) {
      const needed = {
        ...extension,
        fields: extension.fields.filter(({ field }) =>
          missing.has(`${extension.table}.${field.name}`),
        ),
      };
      if (needed.fields.length === 0) continue;
      for (const orm of ormOwners) {
        logger.warn(
          `${owner.name} adds columns to "${extension.table}", which your ${orm === "prisma" ? "Prisma" : "Drizzle"} schema owns. Farm will not alter it. Add them there and run its migration:\n${renderSchemaExtensionForOrm(orm, needed, result.plan.dialect)}`,
        );
      }
    }
  }

  if (result.applied.length > 0) {
    logger.success(`Created ${result.applied.length} object(s).`);
  } else if (result.planned > 0 && !options.write && !options.apply && !options.confirm) {
    logger.info("Re-run with --apply to execute, or --write <file> to save it.");
  }

  if (result.plan.drift.length > 0) {
    logger.warn(
      "Tables that differ from the schema were left unchanged. Review them and migrate with your own tooling.",
    );
  }
  return {
    // Still missing after --apply: columns, and foreign keys the app allowed
    // but rows that point at nothing kept out.
    pending: [
      ...result.extensions.pending,
      ...result.foreignKeys.blocked.map(
        ({ key, orphans }) =>
          `${key.table}.${key.column} → ${key.referencedTable} (${orphans} orphan row(s))`,
      ),
    ],
    sql: result.sql,
    created: result.applied.length,
    planned: result.planned,
  };
}

/**
 * Create the tables every plugin needs, dependencies first: a plugin whose
 * tables point at another plugin's is migrated after it. Your own ORM's or
 * library's migrations are not run here; run them first (`farm migrate`).
 *
 * Printing is the default, as with `farm <plugin> migrate`.
 */
export async function migrateAllSchemas(options: MigrateSchemaOptions = {}): Promise<void> {
  const { config, owners } = await loadApp(options);
  if (owners.length === 0) {
    logger.info("No configured plugin owns tables, so there is nothing to migrate.");
    return;
  }

  const dependencies = collectSchemaDependencies(owners);
  const ordered = orderSchemaOwners(owners, dependencies);
  logger.info(`Migrating in order: ${ordered.map((owner) => owner.name).join(" → ")}`);

  const failed = new Set<string>();
  const problems: string[] = [];
  const files: string[] = [];
  let planned = 0;
  for (const owner of ordered) {
    // A plugin whose dependency failed would only fail the same way, or
    // create tables that point at nothing.
    const blockedBy = [...(dependencies.get(owner.name) ?? [])].filter((name) => failed.has(name));
    if (blockedBy.length > 0) {
      failed.add(owner.name);
      problems.push(`${owner.name}: skipped because ${blockedBy.join(", ")} did not finish.`);
      logger.warn(
        `Skipping ${owner.name}: it depends on ${blockedBy.join(", ")}, which did not finish.`,
      );
      continue;
    }

    logger.info(`\n${owner.name}`);
    try {
      const outcome = await migrateOwner(owner, config, {
        ...options,
        sqlOnly: Boolean(options.write),
      });
      files.push(outcome.sql);
      planned += outcome.planned;
      if (options.apply && outcome.pending.length > 0) {
        problems.push(`${owner.name}: still missing ${outcome.pending.join(", ")}.`);
      }
    } catch (error) {
      failed.add(owner.name);
      const message = error instanceof Error ? error.message : String(error);
      problems.push(`${owner.name}: ${message}`);
      logger.error(`${owner.name} failed: ${message}`);
    }
  }

  if (options.write && !options.apply) {
    const { mkdir, writeFile } = await import("node:fs/promises");
    await mkdir(path.dirname(path.resolve(options.write)), { recursive: true });
    await writeFile(path.resolve(options.write), files.join("\n"), "utf8");
    logger.success(`Wrote the plan for ${files.length} plugin(s) to ${options.write}`);
  }

  if (problems.length > 0) {
    throw new Error(`Not everything was migrated:\n  ${problems.join("\n  ")}`);
  }

  if (
    !options.apply &&
    !options.write &&
    planned > 0 &&
    (await options.confirm?.("Apply all of these changes now?"))
  ) {
    await migrateAllSchemas({ ...options, apply: true, confirm: undefined });
  }
}
