// @vitest-environment node
import { describe, expect, it } from "vitest";
import { createIntegrationOrm } from "../integration-orm";
import { defineSchema } from "../schema";
import {
  applySchemaMigration,
  createSchemaExecutor,
  formatSchemaMigration,
  planSchemaMigration,
  type FarmSchemaExecutor,
} from "../schema-migrate";
import {
  collectSchemaModels,
  generateSqlStatements,
  renderSqlSchemaFile,
  resolveSchemaModels,
  type FarmSqlDialect,
} from "../schema-sql";
import {
  collectOwnerModels,
  declareSchemaTables,
  findSchemaTableOwners,
  migrateSchemaTables,
} from "../schema-tables";

const schema = defineSchema({
  models: {
    tasks: {
      name: "todo_items",
      fields: {
        id: { type: "uuid", primaryKey: true },
        title: { type: "string", required: true },
        status: { type: "enum", values: ["open", "done"], default: "open" },
        priority: { type: "integer", default: 0 },
        listId: { type: "string", required: true, index: true, name: "list_id" },
        slug: { type: "string", unique: true },
        updatedAt: { type: "datetime", name: "updated_at" },
      },
      constraints: [{ type: "index", fields: ["listId", "status"] }],
    },
  },
});

const models = (only?: readonly string[]) => collectSchemaModels([["sync", schema, only]]);

describe("schema name resolution", () => {
  /**
   * The runtime orm reads `model.name ?? modelKey`, so generated artifacts have
   * to agree with it. Defaulting to anything else describes tables the app
   * cannot read.
   */
  it("falls back to the schema's own keys, matching the runtime orm", () => {
    const resolved = resolveSchemaModels("billing", {
      models: {
        invoiceLines: {
          fields: { id: { type: "uuid", primaryKey: true }, lineTotal: { type: "integer" } },
        },
      },
    });

    expect(resolved.invoiceLines!.name).toBe("invoiceLines");
    expect(resolved.invoiceLines!.fields.lineTotal!.name).toBe("lineTotal");
  });

  it("still honors explicit name mappings", () => {
    const resolved = resolveSchemaModels("sync", schema);

    expect(resolved.tasks!.name).toBe("todo_items");
    expect(resolved.tasks!.fields.listId!.name).toBe("list_id");
  });

  it("rejects two models that would claim the same table", () => {
    expect(() =>
      collectSchemaModels([
        ["alpha", { models: { tasks: { fields: { id: { type: "uuid" } } } } }],
        ["beta", { models: { tasks: { fields: { id: { type: "uuid" } } } } }],
      ]),
    ).toThrow(/conflicts with/);
  });

  it("claims only the models an owner was given", () => {
    const shared = defineSchema({
      models: {
        tasks: { fields: { id: { type: "uuid", primaryKey: true } } },
        secrets: { fields: { id: { type: "uuid", primaryKey: true } } },
      },
    });

    expect(collectSchemaModels([["sync", shared, ["tasks"]]]).map((m) => m.modelKey)).toEqual([
      "tasks",
    ]);
  });
});

describe("sql generation", () => {
  it("uses the mapped table and column names, not the model keys", () => {
    const sql = generateSqlStatements(models(), "postgres")
      .map((statement) => statement.sql)
      .join("\n");

    expect(sql).toContain('CREATE TABLE IF NOT EXISTS "todo_items"');
    expect(sql).toContain('"list_id"');
    expect(sql).toContain('"updated_at"');
    expect(sql).not.toContain('"listId"'); // the schema key never reaches sql
  });

  it("carries primary key, not null, defaults, and unique across", () => {
    const [table] = generateSqlStatements(models(), "postgres");

    expect(table!.sql).toContain('"id" TEXT PRIMARY KEY');
    expect(table!.sql).toContain('"title" TEXT NOT NULL');
    expect(table!.sql).toContain("DEFAULT 'open'");
    expect(table!.sql).toContain('"priority" INTEGER');
    expect(table!.sql).toContain("UNIQUE");
  });

  it("emits an index per indexed field and per declared constraint", () => {
    const indexes = generateSqlStatements(models(), "postgres").filter(
      (statement) => statement.kind === "index",
    );

    expect(indexes.map((statement) => statement.target)).toEqual([
      "todo_items_list_id_idx",
      "todo_items_list_id_status_index",
    ]);
  });

  it.each([
    ["postgres", "TIMESTAMPTZ", '"todo_items"'],
    ["sqlite", "TEXT", '"todo_items"'],
    ["mysql", "DATETIME", "`todo_items`"],
  ] as Array<[FarmSqlDialect, string, string]>)(
    "maps types and quoting for %s",
    (dialect, dateType, quotedTable) => {
      const [table] = generateSqlStatements(models(), dialect);

      expect(table!.sql).toContain(quotedTable);
      expect(table!.sql).toContain(dateType);
    },
  );

  it("renders a reviewable file naming the owner of each model", () => {
    const file = renderSqlSchemaFile(models(), "postgres");

    expect(file).toContain("-- Generated by Farm.js CLI");
    expect(file).toContain('-- Owner "sync" model "tasks"');
  });
});

/** An executor over an in-memory sqlite database. */
async function sqliteExecutor() {
  const { DatabaseSync } = await import("node:sqlite");
  const database = new DatabaseSync(":memory:");
  const executor: FarmSchemaExecutor = {
    async execute(sql) {
      database.exec(sql);
    },
    async query(sql) {
      return database.prepare(sql).all() as Record<string, unknown>[];
    },
  };
  return { database, executor };
}

describe("migration planning", () => {
  it("plans a create for a table that does not exist", async () => {
    const { executor } = await sqliteExecutor();
    const plan = await planSchemaMigration(models(), "sqlite", executor);

    expect(plan.statements.length).toBeGreaterThan(0);
    expect(plan.upToDate).toEqual([]);
    expect(plan.drift).toEqual([]);
  });

  it("plans nothing once the table matches the schema", async () => {
    const { executor } = await sqliteExecutor();
    await applySchemaMigration(await planSchemaMigration(models(), "sqlite", executor), executor);

    const second = await planSchemaMigration(models(), "sqlite", executor);
    expect(second.statements).toEqual([]);
    expect(second.upToDate).toEqual(["todo_items"]);
    expect(second.drift).toEqual([]);
  });

  it("reports a differing table instead of altering it", async () => {
    const { database, executor } = await sqliteExecutor();
    // A table that predates a schema change: one column missing, one extra.
    database.exec(
      `create table todo_items (id TEXT primary key, title TEXT, list_id TEXT, legacy_note TEXT)`,
    );

    const plan = await planSchemaMigration(models(), "sqlite", executor);

    expect(plan.statements).toEqual([]); // nothing is emitted for it
    expect(plan.drift).toHaveLength(1);
    expect(plan.drift[0]!.missingColumns).toEqual(
      expect.arrayContaining(["status", "priority", "slug", "updated_at"]),
    );
    expect(plan.drift[0]!.extraColumns).toEqual(["legacy_note"]);

    const applied = await applySchemaMigration(plan, executor);
    expect(applied.applied).toEqual([]);
    expect(applied.skipped).toHaveLength(1);

    // The pre-existing column is untouched.
    const columns = await executor.query("pragma table_info('todo_items')");
    expect(columns.map((row) => row.name)).toContain("legacy_note");
  });

  it("only creates the tables that are missing, leaving the rest alone", async () => {
    const { database, executor } = await sqliteExecutor();
    const two = collectSchemaModels([
      [
        "sync",
        defineSchema({
          models: {
            present: { fields: { id: { type: "uuid", primaryKey: true } } },
            absent: { fields: { id: { type: "uuid", primaryKey: true } } },
          },
        }),
      ],
    ]);
    database.exec(`create table present (id TEXT primary key)`);

    const plan = await planSchemaMigration(two, "sqlite", executor);

    expect(plan.upToDate).toEqual(["present"]);
    expect(plan.statements.map((statement) => statement.target)).toEqual(["absent"]);
  });

  it("renders a migration file, including when there is nothing to do", async () => {
    const { executor } = await sqliteExecutor();
    const plan = await planSchemaMigration(models(), "sqlite", executor);

    const sql = formatSchemaMigration(plan, "sync");
    expect(sql).toContain("Generated by `farm sync migrate`");
    expect(sql).toContain("CREATE TABLE IF NOT EXISTS");

    await applySchemaMigration(plan, executor);
    const empty = formatSchemaMigration(
      await planSchemaMigration(models(), "sqlite", executor),
      "sync",
    );
    expect(empty).toContain("Nothing to create");
  });
});

describe("generated sql against the runtime orm", () => {
  /**
   * The point of the command: what it creates is what the app then reads. This
   * fails if the emitter and `createIntegrationOrm` ever disagree on a name.
   */
  it("produces tables the runtime orm can read and write", async () => {
    const { database, executor } = await sqliteExecutor();
    // No `name` anywhere: the defaults are what must line up.
    const appSchema = defineSchema({
      models: {
        tasks: {
          fields: {
            id: { type: "uuid", primaryKey: true },
            title: { type: "string", required: true },
            listId: { type: "string", required: true, index: true },
          },
        },
      },
    });

    await applySchemaMigration(
      await planSchemaMigration(collectSchemaModels([["app", appSchema]]), "sqlite", executor),
      executor,
    );

    const orm = await createIntegrationOrm({ schema: appSchema, client: database });
    await orm.tasks.create({ data: { id: "t1", title: "round trip", listId: "list-a" } });
    const rows = await orm.tasks.findMany({});

    expect(rows).toHaveLength(1);
    expect(rows[0]).toMatchObject({ title: "round trip", listId: "list-a" });
  });
});

describe("client detection", () => {
  it("reports a key-value storage mount as having no tables", async () => {
    const { createStorage } = await import("unstorage");
    expect(createSchemaExecutor(createStorage(), "sync")).toBeNull();
  });

  it("names the owner when a client cannot run migrations", () => {
    expect(() => createSchemaExecutor({ notADatabase: true }, "jobs")).toThrow(
      /jobs: the configured client cannot run migrations/,
    );
  });
});

describe("table owners", () => {
  /** A plugin-shaped object that declares it owns the schema's tables. */
  function ownerPlugin(name: string, client: unknown) {
    return declareSchemaTables(
      { name: `farm:${name}` },
      { name, schema, resolveClient: async () => client },
    );
  }

  it("finds owners across plugins and integrations", () => {
    const owners = findSchemaTableOwners({
      plugins: [{ name: "farm:unrelated" }, ownerPlugin("sync", null)],
      integrations: { jobs: ownerPlugin("jobs", null) },
    });

    expect(owners.map((owner) => owner.name)).toEqual(["sync", "jobs"]);
  });

  it("does not expose the declaration to config serialization", () => {
    const plugin = ownerPlugin("sync", null);
    expect(Object.keys(plugin)).toEqual(["name"]);
    expect(JSON.parse(JSON.stringify(plugin))).toEqual({ name: "farm:sync" });
  });

  it("resolves a declaration down to the models tooling works with", () => {
    const owner = findSchemaTableOwners({ plugins: [ownerPlugin("sync", null)] })[0]!;
    expect(collectOwnerModels(owner).map((model) => model.modelName)).toEqual(["todo_items"]);
  });

  it("creates an owner's tables, then reports it is up to date", async () => {
    const { DatabaseSync } = await import("node:sqlite");
    const database = new DatabaseSync(":memory:");
    const owner = findSchemaTableOwners({ plugins: [ownerPlugin("sync", database)] })[0]!;
    const logs: string[] = [];

    const first = await migrateSchemaTables(owner, {
      apply: true,
      log: (message) => logs.push(message),
    });
    expect(first.applied).toContain("todo_items");

    const columns = database.prepare("pragma table_info('todo_items')").all() as any[];
    expect(columns.map((row) => row.name)).toEqual(
      expect.arrayContaining(["id", "title", "list_id", "updated_at"]),
    );

    const second = await migrateSchemaTables(owner, {
      apply: true,
      log: (message) => logs.push(message),
    });
    expect(second.applied).toEqual([]);
    expect(logs.join("\n")).toContain("Already up to date");
  });

  it("prints sql without touching the database unless asked", async () => {
    const { DatabaseSync } = await import("node:sqlite");
    const database = new DatabaseSync(":memory:");

    const result = await migrateSchemaTables(
      findSchemaTableOwners({ plugins: [ownerPlugin("sync", database)] })[0]!,
    );

    expect(result.sql).toContain("CREATE TABLE IF NOT EXISTS");
    expect(result.applied).toEqual([]);
    const present = database
      .prepare("select name from sqlite_master where type='table'")
      .all() as any[];
    expect(present.map((row) => row.name)).not.toContain("todo_items");
  });

  it("names the owner when it stores through a storage mount", async () => {
    const { createStorage } = await import("unstorage");
    const logs: string[] = [];

    const result = await migrateSchemaTables(
      findSchemaTableOwners({ plugins: [ownerPlugin("jobs", createStorage())] })[0]!,
      { log: (message) => logs.push(message) },
    );

    expect(result.applied).toEqual([]);
    expect(logs.join("\n")).toContain("jobs stores data through a storage mount");
  });

  it("hands the app config to an owner that reads its client from there", async () => {
    const { DatabaseSync } = await import("node:sqlite");
    const database = new DatabaseSync(":memory:");
    // An integration configured through `storage.client` rather than its own
    // options — the shape @farm.js/stripe uses.
    const integration = declareSchemaTables(
      { type: "stripe" },
      {
        name: "stripe",
        schema,
        resolveClient: async (config) =>
          (config.storage as { client?: unknown } | undefined)?.client,
      },
    );

    const result = await migrateSchemaTables(
      findSchemaTableOwners({ integrations: { billing: integration } })[0]!,
      { apply: true, config: { storage: { client: database } } },
    );

    expect(result.applied).toContain("todo_items");
  });

  it("finds nothing when no plugin declares tables", () => {
    expect(findSchemaTableOwners({ plugins: [{ name: "farm:unrelated" }] })).toEqual([]);
    expect(findSchemaTableOwners({})).toEqual([]);
  });
});

/** The declaration contract is structural, so a third party can satisfy it. */
describe("a third-party plugin", () => {
  it("gets migrations by declaring its schema and client", async () => {
    const { DatabaseSync } = await import("node:sqlite");
    const database = new DatabaseSync(":memory:");

    const plugin = declareSchemaTables(
      { name: "acme:webhooks" },
      {
        name: "webhooks",
        schema: defineSchema({
          models: {
            webhooks: {
              fields: {
                id: { type: "uuid", primaryKey: true },
                url: { type: "string", required: true },
                deliveredAt: { type: "datetime", name: "delivered_at" },
              },
            },
          },
        }),
        resolveClient: async () => database,
      },
    );

    const result = await migrateSchemaTables(findSchemaTableOwners({ plugins: [plugin] })[0]!, {
      apply: true,
    });

    expect(result.applied).toEqual(["webhooks"]);
    const columns = database.prepare("pragma table_info('webhooks')").all() as any[];
    expect(columns.map((row) => row.name)).toEqual(["id", "url", "delivered_at"]);
  });
});
