import {
  columnNameOf,
  generateSyncDdl,
  tableNameOf,
  type SyncDdlStatement,
  type SyncDialect,
} from "./ddl.js";
import type { ResolvedSyncModel } from "./types.js";

/** The subset of a database client this needs: run a statement, read a result. */
export type SyncMigrateExecutor = {
  /** Run a statement that returns nothing. */
  execute(sql: string): Promise<void>;
  /** Run a query and return its rows. */
  query(sql: string, params?: unknown[]): Promise<Record<string, unknown>[]>;
};

export type SyncTableDrift = {
  table: string;
  /** Declared in the schema but absent from the table. */
  missingColumns: string[];
  /** Present in the table but not declared. Reported, never dropped. */
  extraColumns: string[];
};

export type SyncMigratePlan = {
  dialect: SyncDialect;
  /** Statements for tables that do not exist yet. */
  statements: SyncDdlStatement[];
  /** Tables that exist and already match the schema. */
  upToDate: string[];
  /** Tables that exist but differ. Never altered automatically. */
  drift: SyncTableDrift[];
};

/**
 * Compare the schema against the live database and plan what to create.
 *
 * Creation is derivable from the schema alone, so it is safe to emit. Changing
 * an existing table is not: a rename and a drop-plus-add look identical here,
 * and one of them destroys data. Differences are reported for a human instead.
 */
export async function planSyncMigration(
  models: Map<string, ResolvedSyncModel>,
  dialect: SyncDialect,
  executor: SyncMigrateExecutor,
): Promise<SyncMigratePlan> {
  const statements: SyncDdlStatement[] = [];
  const upToDate: string[] = [];
  const drift: SyncTableDrift[] = [];

  for (const model of models.values()) {
    const table = tableNameOf(model.name, model.model);
    const existing = await describeTable(executor, dialect, table);

    if (!existing) {
      statements.push(...generateSyncDdl(new Map([[model.name, model]]), dialect));
      continue;
    }

    const declared = Object.entries(model.fields).map(([field, definition]) =>
      columnNameOf(field, definition),
    );
    const missingColumns = declared.filter((column) => !existing.has(column.toLowerCase()));
    const extraColumns = [...existing].filter(
      (column) => !declared.some((declaredColumn) => declaredColumn.toLowerCase() === column),
    );

    if (missingColumns.length === 0 && extraColumns.length === 0) upToDate.push(table);
    else drift.push({ table, missingColumns, extraColumns });
  }

  return { dialect, statements, upToDate, drift };
}

/** Column names of a table, lowercased, or undefined when it does not exist. */
async function describeTable(
  executor: SyncMigrateExecutor,
  dialect: SyncDialect,
  table: string,
): Promise<Set<string> | undefined> {
  if (dialect === "sqlite") {
    const rows = await executor.query(`pragma table_info('${table.split("'").join("''")}')`);
    if (rows.length === 0) return undefined;
    return new Set(rows.map((row) => String(row.name).toLowerCase()));
  }

  const rows = await executor.query(
    "select column_name from information_schema.columns where table_name = ?",
    [table],
  );
  if (rows.length === 0) return undefined;
  return new Set(rows.map((row) => String(row.column_name ?? row.COLUMN_NAME).toLowerCase()));
}

export type ApplySyncMigrationResult = {
  applied: string[];
  skipped: SyncTableDrift[];
};

/**
 * Run the plan's create statements. Drift is never applied: a plan that reports
 * differences leaves those tables untouched and says so.
 */
export async function applySyncMigration(
  plan: SyncMigratePlan,
  executor: SyncMigrateExecutor,
): Promise<ApplySyncMigrationResult> {
  const applied: string[] = [];
  for (const statement of plan.statements) {
    await executor.execute(statement.sql);
    applied.push(statement.target);
  }
  return { applied, skipped: plan.drift };
}

/** Render a plan as a reviewable SQL file. */
export function formatSyncMigration(plan: SyncMigratePlan): string {
  const header = [
    "-- Generated by `farm sync migrate` from the sync schema.",
    `-- Dialect: ${plan.dialect}`,
    "-- Review before applying. Sync never alters existing tables.",
  ];

  if (plan.statements.length === 0) {
    header.push("--", "-- Nothing to create: every exposed model already has a table.");
    return `${header.join("\n")}\n`;
  }

  return `${header.join("\n")}\n\n${plan.statements.map((statement) => statement.sql).join("\n\n")}\n`;
}

/** Human-readable summary of tables that exist but no longer match the schema. */
export function describeDrift(drift: readonly SyncTableDrift[]): string {
  return drift
    .map((entry) => {
      const lines = [`  ${entry.table}`];
      if (entry.missingColumns.length > 0) {
        lines.push(`    missing in the database: ${entry.missingColumns.join(", ")}`);
      }
      if (entry.extraColumns.length > 0) {
        lines.push(`    not in the schema: ${entry.extraColumns.join(", ")}`);
      }
      return lines.join("\n");
    })
    .join("\n");
}
