import { mkdirSync } from "node:fs";
import path from "node:path";
import { writeFileIfChanged } from "./write-file-if-changed";

export const FARM_STATIC_IMAGE_EXTENSIONS = ["avif", "gif", "jpeg", "jpg", "png", "webp"] as const;

export interface GenerateFarmImageTypesOptions {
  root: string;
  srcDir?: string;
  outFile?: string;
}

export function generateFarmImageTypes(options: GenerateFarmImageTypesOptions): string {
  const outputPath = options.outFile
    ? path.resolve(options.root, options.outFile)
    : path.join(options.root, options.srcDir || "src", "farm-images.d.ts");
  mkdirSync(path.dirname(outputPath), { recursive: true });
  writeFileIfChanged(outputPath, createFarmImageTypeDeclarations());
  return outputPath;
}

export function createFarmImageTypeDeclarations(): string {
  const modules = FARM_STATIC_IMAGE_EXTENSIONS.map(
    (extension) => `declare module "*.${extension}" {
  const image: import("@farm.js/core/image").StaticImageData;
  export const src: string;
  export const width: number;
  export const height: number;
  export const blurDataURL: string | undefined;
  export default image;
}`,
  );

  return `// Generated by Farm.js. Do not edit.
${modules.join("\n\n")}

declare module "*?url" {
  const src: string;
  export default src;
}
`;
}
