import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import { join, relative, dirname } from 'path';

export interface APIRouteInfo {
  path: string;
  methods: string[];
  filePath: string;
  relativePath: string;
}

export class APITypeGenerator {
  private appDir: string;
  private apiDir: string;

  constructor(appDir: string) {
    this.appDir = appDir;
    this.apiDir = join(appDir, 'api');
  }

  /**
   * Scan all API route files and extract route information
   */
  scanAPIRoutes(): APIRouteInfo[] {
    const routes: APIRouteInfo[] = [];
    
    if (!existsSync(this.apiDir)) {
      return routes;
    }

    this.scanDirectory(this.apiDir, routes);
    return routes;
  }

  private scanDirectory(dir: string, routes: APIRouteInfo[], basePath: string = '') {
    const items = readdirSync(dir, { withFileTypes: true });
    
    for (const item of items) {
      const fullPath = join(dir, item.name);
      
      if (item.isDirectory()) {
        const newBasePath = basePath ? `${basePath}/${item.name}` : item.name;
        this.scanDirectory(fullPath, routes, newBasePath);
      } else if (item.name === 'route.ts' || item.name === 'route.tsx') {
        const routeInfo = this.extractRouteInfo(fullPath, basePath);
        if (routeInfo) {
          routes.push(routeInfo);
        }
      }
    }
  }

  private extractRouteInfo(filePath: string, basePath: string): APIRouteInfo | null {
    try {
      const content = readFileSync(filePath, 'utf-8');
      const methods = this.extractExportedMethods(content);
      
      if (methods.length === 0) {
        return null;
      }

      const relativePath = relative(this.appDir, filePath);
      const apiPath = basePath ? `/api/${basePath}` : '/api';

      return {
        path: apiPath,
        methods,
        filePath,
        relativePath
      };
    } catch (error) {
      console.warn(`Failed to read route file ${filePath}:`, error);
      return null;
    }
  }

  private extractExportedMethods(content: string): string[] {
    const methods: string[] = [];
    const httpMethods = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS', 'HEAD'];
    
    for (const method of httpMethods) {
      // Look for export const METHOD = or export { METHOD }
      const patterns = [
        new RegExp(`export\\s+const\\s+${method}\\s*=`, 'g'),
        new RegExp(`export\\s*{\\s*${method}\\s*}`, 'g'),
        new RegExp(`export\\s*{\\s*${method}\\s*as\\s+\\w+\\s*}`, 'g')
      ];
      
      for (const pattern of patterns) {
        if (pattern.test(content)) {
          methods.push(method);
          break;
        }
      }
    }
    
    return methods;
  }

  /**
   * Generate TypeScript code for the API router
   */
  generateAPIRouter(routes: APIRouteInfo[]): string {
    const imports: string[] = [];
    
    // Group routes by path to handle multiple methods
    const routeGroups = new Map<string, APIRouteInfo[]>();
    
    for (const route of routes) {
      const key = route.path;
      if (!routeGroups.has(key)) {
        routeGroups.set(key, []);
      }
      routeGroups.get(key)!.push(route);
    }

    // Build nested structure
    const nestedStructure: any = {};
    
    for (const [path, routeList] of routeGroups) {
      const route = routeList[0];
      const importPath = route.relativePath.replace(/\\/g, '/').replace(/\.(ts|tsx)$/, '');
      const routeName = this.pathToRouteName(route.path);
      const cleanPath = path.replace(/^\/api\//, '');
      const parts = cleanPath ? cleanPath.split('/') : [];
      
      // Collect all methods for this route
      const allMethods = routeList.flatMap(r => r.methods);
      
      // Generate imports
      for (const method of allMethods) {
        const importName = `${method}_${routeName}`;
        imports.push(`import type { ${method} as ${importName} } from '../app/${importPath}';`);
      }
      
      // Build nested object
      let current = nestedStructure;
      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        if (i === parts.length - 1) {
          // Last part - add methods
          current[part] = {};
          for (const method of allMethods) {
            const importName = `${method}_${routeName}`;
            const methodName = method.toLowerCase();
            current[part][methodName] = `typeof ${importName}`;
          }
        } else {
          // Intermediate part - create nested object
          if (!current[part]) {
            current[part] = {};
          }
          current = current[part];
        }
      }
    }
    
    // Convert nested structure to TypeScript code
    const typeExports = this.structureToTypeString(nestedStructure, 1);

    return `/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 * Generated at: ${new Date().toISOString()}
 * 
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

${imports.join('\n')}

// Type-only representation of your API routes
export type APIRouter = {
${typeExports}
};
`;
  }

  private pathToRouteName(path: string): string {
    return path
      .replace(/^\/api\//, '')
      .replace(/\//g, '_')
      .replace(/[^a-zA-Z0-9_]/g, '');
  }

  private structureToTypeString(obj: any, indent: number): string {
    const spaces = '  '.repeat(indent);
    const lines: string[] = [];
    
    for (const [key, value] of Object.entries(obj)) {
      if (typeof value === 'string') {
        // It's a type reference
        lines.push(`${spaces}${key}: ${value};`);
      } else if (typeof value === 'object') {
        // It's a nested object
        lines.push(`${spaces}${key}: {`);
        lines.push(this.structureToTypeString(value, indent + 1));
        lines.push(`${spaces}};`);
      }
    }
    
    return lines.join('\n');
  }

  private getBaseExportName(path: string): string {
    const cleanPath = path.replace(/^\/api\//, '');
    
    if (cleanPath === '') {
      return 'api';
    }
    
    // Convert path to nested structure
    // /api/auth/login -> ['auth', 'login']
    return cleanPath;
  }

  private getExportName(path: string, method: string): string {
    const cleanPath = path.replace(/^\/api\//, '');
    
    if (cleanPath === '') {
      return method.toLowerCase();
    }
    
    const parts = cleanPath.split('/');
    if (parts.length === 1) {
      // For single-level paths like /api/hello, just use the path name
      return parts[0];
    }
    
    // For nested paths like /api/auth/login, create nested structure
    // This matches the expected API client usage: api.auth.login()
    return parts.join('.');
  }

  /**
   * Generate the API index file
   */
  generateAPIIndex(outputPath: string): void {
    const routes = this.scanAPIRoutes();
    const content = this.generateAPIRouter(routes);
    
    writeFileSync(outputPath, content, 'utf-8');
    console.log(`✅ Generated API types for ${routes.length} routes`);
  }
}
