-- Generated by Farm.js CLI. Review before applying.

-- Integration "billing" model "billingAccount"
CREATE TABLE IF NOT EXISTS "billing_account" (
  "id" TEXT PRIMARY KEY,
  "owner_id" TEXT NOT NULL,
  "owner_kind" TEXT NOT NULL DEFAULT 'user',
  "stripe_customer_id" TEXT UNIQUE,
  "stripe_subscription_id" TEXT UNIQUE,
  "plan_id" TEXT NOT NULL DEFAULT 'free',
  "product_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'free',
  "current_period_end" TEXT,
  "cancel_at_period_end" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "billing_account_owner_id_idx" ON "billing_account" ("owner_id");

CREATE INDEX IF NOT EXISTS "billing_account_owner_kind_idx" ON "billing_account" ("owner_kind");

CREATE UNIQUE INDEX IF NOT EXISTS "billing_account_owner_unique" ON "billing_account" ("owner_kind", "owner_id");
