import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const require = createRequire(import.meta.url);
const { listSchemaTableOwners, migrateSchema } = require("../dist/index.js");

/**
 * A plugin that declares tables. The declaration is a plain object under a
 * global symbol, so a fixture can build one without importing core.
 */
function pluginSource(name, { client = "null" } = {}) {
  return `
const declaration = {
  name: ${JSON.stringify(name)},
  schema: {
    models: {
      widgets: {
        fields: {
          id: { type: "uuid", primaryKey: true },
          label: { type: "string", required: true },
          ownerId: { type: "string", index: true },
        },
      },
      privateNotes: {
        fields: { id: { type: "uuid", primaryKey: true } },
      },
    },
  },
  models: ["widgets"],
  resolveClient: async () => ${client},
};
const plugin = { name: "farm:" + ${JSON.stringify(name)} };
Object.defineProperty(plugin, Symbol.for("farm.schema-tables"), {
  value: declaration,
  enumerable: false,
});
`;
}

async function fixture(body) {
  const root = await mkdtemp(path.join(os.tmpdir(), "farm-cli-schema-migrate-"));
  await writeFile(path.join(root, "farm.config.mjs"), body);
  return root;
}

test("lists the plugins in an app that own tables", async () => {
  const root = await fixture(`${pluginSource("widgets")}
export default { plugins: [plugin] };
`);

  try {
    assert.deepEqual(await listSchemaTableOwners({ root }), ["widgets"]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("names the available plugins when asked for one that does not own tables", async () => {
  const root = await fixture(`${pluginSource("widgets")}
export default { plugins: [plugin] };
`);

  try {
    await assert.rejects(
      () => migrateSchema("jobs", { root }),
      (error) => {
        assert.match(error.message, /No plugin named "jobs"/);
        assert.match(error.message, /Available: widgets/);
        return true;
      },
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("explains when the configured client cannot run migrations", async () => {
  const root = await fixture(`${pluginSource("widgets")}
export default { plugins: [plugin] };
`);

  try {
    await assert.rejects(
      () => migrateSchema("widgets", { root }),
      /widgets: the configured client cannot run migrations/,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("says there is nothing to migrate when no plugin owns tables", async () => {
  const root = await fixture("export default {};\n");

  try {
    await assert.rejects(
      () => migrateSchema("widgets", { root }),
      /No configured plugin owns tables/,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("writes reviewable sql covering only the models the plugin owns", async () => {
  // A connection is required even to write: the output is what is *missing*
  // from this database, not a full dump. `farm generate --orm` emits the dump.
  const root = await fixture(`import { DatabaseSync } from "node:sqlite";
${pluginSource("widgets", { client: 'new DatabaseSync(":memory:")' })}
export default { plugins: [plugin] };
`);
  const output = path.join(root, "migrations", "widgets.sql");

  try {
    await migrateSchema("widgets", { root, write: output });
    const sql = await readFile(output, "utf8");

    assert.match(sql, /Generated by `farm widgets migrate`/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS "widgets"/);
    assert.match(sql, /CREATE INDEX IF NOT EXISTS "widgets_ownerId_idx"/);
    // `privateNotes` is in the schema but not in `models`, so it is not ours.
    assert.doesNotMatch(sql, /privateNotes/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("applies the statements against a real database", async () => {
  const root = await fixture(`import { DatabaseSync } from "node:sqlite";
const database = new DatabaseSync(":memory:");
globalThis.__testDatabase = database;
${pluginSource("widgets", { client: "database" })}
export default { plugins: [plugin] };
`);

  try {
    await migrateSchema("widgets", { root, apply: true });

    // The same config module is reused, so the in-memory database persists.
    const database = globalThis.__testDatabase;
    const tables = database
      .prepare("select name from sqlite_master where type='table'")
      .all()
      .map((row) => row.name);

    assert.ok(tables.includes("widgets"), `expected widgets table, got ${tables.join(", ")}`);
    assert.ok(!tables.includes("privateNotes"), "unowned model must not be created");
  } finally {
    delete globalThis.__testDatabase;
    await rm(root, { recursive: true, force: true });
  }
});
