/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 * Generated at: 2026-07-16T22:44:48.551Z
 * 
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */



// Type-only representation of your API routes
export type APIRouter = {

};
