/**
 * Auto-generated API router for type generation
 * This file is automatically generated - do not edit manually
 * Generated at: 2025-10-16T11:39:55.558Z
 */

import { GET as GET_auth_login } from '../api/auth/login/route';
import { POST as POST_auth_login } from '../api/auth/login/route';
import { GET as GET_hello } from '../api/hello/route';
import { GET as GET_users } from '../api/users/route';
import { POST as POST_users } from './users/route';

// Export all endpoints with their paths for better-call router
export const api = {
  'auth/login': {
    get: GET_auth_login,
    post: POST_auth_login,
  },
  hello: GET_hello,
  users: {
    get: GET_users,
    post: POST_users,
  },
};

// Export the type for the RPC client
export type APIRouter = {
  'auth/login': {
    get: typeof GET_auth_login;
    post: typeof POST_auth_login;
  };
  hello: typeof GET_hello;
  users: {
    get: typeof GET_users;
    post: typeof POST_users;
  };
};
