// Generated by Farm.js CLI. Review before committing.
import { boolean, index, integer, jsonb, pgTable, real, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

// Farm.js generated from "alpha" model "orgs"
export const alphaOrgs = pgTable("orgs", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
}, (table) => ({
}));

// Farm.js generated from "alpha" model "members"
export const alphaMembers = pgTable("members", {
  id: text("id").primaryKey(),
  // orgId references orgs.id (onDelete: cascade)
  orgId: text("org_id").notNull(),
  role: text("role").notNull().default("member"),
  seatCount: integer("seat_count").notNull().default(1),
  spendCap: real("spend_cap"),
  active: boolean("active").notNull().default(true),
  profile: jsonb("profile"),
  notes: text("notes"),
  joinedAt: timestamp("joined_at", { mode: "date" }).notNull().defaultNow(),
  // offsiteRef references elsewhere.id
  offsiteRef: text("offsite_ref"),
}, (table) => ({
  orgIdIdx: index("members_org_id_idx").on(table.orgId),
  membersOrgIdRoleUnique: uniqueIndex("members_org_id_role_unique").on(table.orgId, table.role),
}));

// Farm.js generated from "beta" model "projects"
export const betaProjects = pgTable("projects", {
  id: text("id").primaryKey(),
  projectTitle: text("projectTitle").notNull(),
  // ownerId references tickets.id
  ownerId: text("ownerId").notNull(),
  createdAt: timestamp("createdAt", { mode: "date" }).notNull(),
}, (table) => ({
  ownerIdIdx: index("projects_ownerId_idx").on(table.ownerId),
}));

// Farm.js generated from "beta" model "tickets"
export const betaTickets = pgTable("tickets", {
  id: text("id").primaryKey(),
  ticketBody: text("ticketBody"),
}, (table) => ({
}));

// Farm.js generated from "widgets" model "widgets"
export const widgetsWidgets = pgTable("widgets", {
  id: text("id").primaryKey(),
  label: text("label").notNull(),
}, (table) => ({
}));
