// Generated by Farm.js CLI. Review before committing.
import type { Db } from "mongodb";

export async function ensureFarmIntegrationCollections(db: Db) {
  // Owner "alpha" model "orgs"
  const alphaOrgs = db.collection("orgs");
  await alphaOrgs.createIndex({ "slug": 1 }, { unique: true, name: "orgs_slug_unique" });

  // Owner "alpha" model "members"
  const alphaMembers = db.collection("members");
  await alphaMembers.createIndex({ "org_id": 1 }, { name: "members_org_id_idx" });
  // orgId references orgs.id (onDelete: cascade)
  // offsiteRef references elsewhere.id
  await alphaMembers.createIndex({ "org_id": 1, "role": 1 }, { unique: true, name: "members_org_id_role_unique" });

  // Owner "beta" model "projects"
  const betaProjects = db.collection("projects");
  await betaProjects.createIndex({ "ownerId": 1 }, { name: "projects_ownerId_idx" });
  // ownerId references tickets.id

  // Owner "beta" model "tickets"
  const betaTickets = db.collection("tickets");

  // Owner "widgets" model "widgets"
  const widgetsWidgets = db.collection("widgets");

}
