-- Generated by Farm.js CLI. Review before applying.

-- Owner "alpha" model "orgs"
CREATE TABLE IF NOT EXISTS `orgs` (
  `id` VARCHAR(255) PRIMARY KEY,
  `slug` VARCHAR(255) NOT NULL UNIQUE
);

-- Owner "alpha" model "members"
CREATE TABLE IF NOT EXISTS `members` (
  `id` VARCHAR(255) PRIMARY KEY,
  `org_id` VARCHAR(255) NOT NULL REFERENCES `orgs` (`id`) ON DELETE CASCADE,
  `role` VARCHAR(255) NOT NULL DEFAULT 'member',
  `seat_count` INT NOT NULL DEFAULT 1,
  `spend_cap` DOUBLE,
  `active` BOOLEAN NOT NULL DEFAULT TRUE,
  `profile` JSON,
  `notes` TEXT,
  `joined_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `offsite_ref` VARCHAR(255) /* references elsewhere.id */,
  KEY `members_org_id_idx` (`org_id`),
  UNIQUE KEY `members_org_id_role_unique` (`org_id`, `role`)
);

-- Owner "beta" model "projects"
CREATE TABLE IF NOT EXISTS `projects` (
  `id` VARCHAR(255) PRIMARY KEY,
  `projectTitle` VARCHAR(255) NOT NULL,
  `ownerId` VARCHAR(255) NOT NULL REFERENCES `tickets` (`id`),
  `createdAt` DATETIME NOT NULL,
  KEY `projects_ownerId_idx` (`ownerId`)
);

-- Owner "beta" model "tickets"
CREATE TABLE IF NOT EXISTS `tickets` (
  `id` VARCHAR(255) PRIMARY KEY,
  `ticketBody` TEXT
);

-- Owner "widgets" model "widgets"
CREATE TABLE IF NOT EXISTS `widgets` (
  `id` VARCHAR(255) PRIMARY KEY,
  `label` VARCHAR(255) NOT NULL
);
