-- Generated by Farm.js CLI. Review before applying.

-- Owner "alpha" model "orgs"
CREATE TABLE IF NOT EXISTS "orgs" (
  "id" TEXT PRIMARY KEY,
  "slug" TEXT NOT NULL UNIQUE
);

-- Owner "alpha" model "members"
CREATE TABLE IF NOT EXISTS "members" (
  "id" TEXT PRIMARY KEY,
  "org_id" TEXT NOT NULL REFERENCES "orgs" ("id") ON DELETE CASCADE,
  "role" TEXT NOT NULL DEFAULT 'member',
  "seat_count" INTEGER NOT NULL DEFAULT 1,
  "spend_cap" DOUBLE PRECISION,
  "active" BOOLEAN NOT NULL DEFAULT TRUE,
  "profile" JSONB,
  "notes" TEXT,
  "joined_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "offsite_ref" TEXT /* references elsewhere.id */
);

CREATE INDEX IF NOT EXISTS "members_org_id_idx" ON "members" ("org_id");

CREATE UNIQUE INDEX IF NOT EXISTS "members_org_id_role_unique" ON "members" ("org_id", "role");

-- Owner "beta" model "projects"
CREATE TABLE IF NOT EXISTS "projects" (
  "id" TEXT PRIMARY KEY,
  "projectTitle" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL REFERENCES "tickets" ("id"),
  "createdAt" TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS "projects_ownerId_idx" ON "projects" ("ownerId");

-- Owner "beta" model "tickets"
CREATE TABLE IF NOT EXISTS "tickets" (
  "id" TEXT PRIMARY KEY,
  "ticketBody" TEXT
);

-- Owner "widgets" model "widgets"
CREATE TABLE IF NOT EXISTS "widgets" (
  "id" TEXT PRIMARY KEY,
  "label" TEXT NOT NULL
);
