import type React from "react";
import type { FarmIslandStrategy } from "../island";

const REACT_ELEMENT_TYPE = Symbol.for("react.transitional.element");
const LEGACY_REACT_ELEMENT_TYPE = Symbol.for("react.element");
const BOUNDARY_GRAPH_CONTEXT = Symbol.for("farm.isolated-hydration.client-graph-context");

function getBoundaryGraphContext(ReactRuntime: typeof React): React.Context<boolean> {
  const shared = globalThis as typeof globalThis &
    Record<symbol, WeakMap<object, React.Context<boolean>> | undefined>;
  const contexts = shared[BOUNDARY_GRAPH_CONTEXT] ?? new WeakMap();
  shared[BOUNDARY_GRAPH_CONTEXT] = contexts;
  const runtimeIdentity = ReactRuntime.createElement;
  const existing = contexts.get(runtimeIdentity);
  if (existing) return existing;

  const context = ReactRuntime.createContext(false);
  contexts.set(runtimeIdentity, context);
  return context;
}

function serializeBoundaryProps(value: unknown, seen = new Set<object>()): unknown {
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new TypeError("non-finite numbers are not serializable");
    return value;
  }
  if (typeof value === "undefined") {
    throw new TypeError("undefined values are not serializable");
  }
  if (typeof value !== "object") {
    throw new TypeError(`${typeof value} values are not serializable`);
  }
  if (
    (value as { $$typeof?: symbol }).$$typeof === REACT_ELEMENT_TYPE ||
    (value as { $$typeof?: symbol }).$$typeof === LEGACY_REACT_ELEMENT_TYPE
  ) {
    throw new TypeError("React elements cannot cross an isolated hydration boundary");
  }
  if (seen.has(value)) throw new TypeError("circular props are not serializable");
  seen.add(value);
  try {
    if (Array.isArray(value)) return value.map((entry) => serializeBoundaryProps(entry, seen));
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) {
      throw new TypeError("class instances are not serializable");
    }
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, serializeBoundaryProps(entry, seen)]),
    );
  } finally {
    seen.delete(value);
  }
}

function serializeBoundaryPayload(value: unknown): string {
  return JSON.stringify(serializeBoundaryProps(value))
    .replace(/&/g, "\\u0026")
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

/** @internal Keeps client-to-client imports inside one isolated React root. */
export function wrapFarmIsolatedClientGraph(
  ReactRuntime: typeof React,
  element: React.ReactNode,
): React.ReactElement {
  const Context = getBoundaryGraphContext(ReactRuntime);
  return ReactRuntime.createElement(Context.Provider, { value: true }, element);
}

/** @internal Generated by Farm's experimental isolated-hydration transform. */
export function createFarmIsolatedClientBoundary(
  ReactRuntime: typeof React,
  Component: React.ComponentType<any>,
  moduleReference: string,
  exportName: string,
  islandStrategy: FarmIslandStrategy,
): React.ComponentType<any> {
  function FarmIsolatedClientBoundary(props: Record<string, unknown>) {
    const Context = getBoundaryGraphContext(ReactRuntime);
    const belongsToParentClientGraph = ReactRuntime.useContext(Context);
    const boundaryId = ReactRuntime.useId();

    if (belongsToParentClientGraph) {
      return ReactRuntime.createElement(Component, props);
    }

    let serializedProps: string;
    try {
      serializedProps = serializeBoundaryPayload(props);
    } catch (error) {
      if (typeof window === "undefined") {
        console.warn(
          `[Farm.js] Could not isolate ${moduleReference}#${exportName}: ${
            error instanceof Error ? error.message : String(error)
          }. The server-rendered component was preserved without client hydration.`,
        );
      }
      return ReactRuntime.createElement(Component, props);
    }

    return ReactRuntime.createElement(
      ReactRuntime.Fragment,
      null,
      ReactRuntime.createElement(
        "farm-client-boundary",
        {
          "data-farm-client-boundary": moduleReference,
          "data-farm-client-id": boundaryId,
          "data-farm-client-export": exportName,
          "data-farm-island-strategy": islandStrategy,
          style: { display: "contents" },
        },
        ReactRuntime.createElement(
          Context.Provider,
          { value: true },
          ReactRuntime.createElement(Component, props),
        ),
      ),
      ReactRuntime.createElement("script", {
        type: "application/json",
        "data-farm-client-props": boundaryId,
        dangerouslySetInnerHTML: { __html: serializedProps },
      }),
    );
  }

  FarmIsolatedClientBoundary.displayName = `FarmIsolated(${
    Component.displayName || Component.name || exportName
  })`;
  return FarmIsolatedClientBoundary;
}

type FarmIsolatedRoot = {
  render(element: React.ReactNode): void;
  unmount(): void;
};

interface FarmIsolatedRootRecord {
  root: FarmIsolatedRoot;
  reference: string;
  exportName: string;
  props: Record<string, unknown>;
  serverHTML: string;
  restore(error: unknown): void;
}

interface FarmIsolatedHydrationRootOptions {
  onUncaughtError?: (error: unknown) => void;
}

export interface FarmIsolatedHydrationRuntimeOptions {
  ReactRuntime: typeof React;
  hydrateRoot(
    container: Element,
    element: React.ReactNode,
    options?: FarmIsolatedHydrationRootOptions,
  ): FarmIsolatedRoot;
  load(reference: string): Promise<Record<string, unknown>>;
  schedule(options: {
    container: Element;
    strategy: FarmIslandStrategy;
    signal?: AbortSignal;
    hydrate(): Promise<void>;
  }): Promise<unknown>;
  wrap?(element: React.ReactElement): React.ReactNode;
  report?(message: string, error?: unknown): void;
}

function findBoundaryPayload(container: Element, boundaryId: string): HTMLScriptElement | null {
  const sibling = container.nextElementSibling;
  if (
    sibling instanceof HTMLScriptElement &&
    sibling.type === "application/json" &&
    sibling.getAttribute("data-farm-client-props") === boundaryId
  ) {
    return sibling;
  }

  for (const candidate of container.ownerDocument.querySelectorAll<HTMLScriptElement>(
    'script[type="application/json"][data-farm-client-props]',
  )) {
    if (candidate.getAttribute("data-farm-client-props") === boundaryId) return candidate;
  }
  return null;
}

/** @internal Shared development and production runtime for isolated React roots. */
export function createFarmIsolatedHydrationRuntime(options: FarmIsolatedHydrationRuntimeOptions) {
  const roots = new Map<Element, FarmIsolatedRootRecord>();
  const pending = new Map<Element, AbortController>();
  const report =
    options.report ??
    ((message: string, error?: unknown) => console.warn(`[Farm.js] ${message}`, error));

  const failRoot = (
    container: Element,
    reference: string,
    exportName: string,
    serverHTML: string,
    error: unknown,
  ) => {
    report(
      `Could not hydrate isolated client boundary ${reference}#${exportName}. ` +
        "The server-rendered HTML was restored.",
      error,
    );
    queueMicrotask(() => {
      try {
        roots.get(container)?.root.unmount();
      } catch {
        // React may already have detached a root that failed during hydration.
      }
      roots.delete(container);
      container.removeAttribute("data-farm-hydrated");
      container.innerHTML = serverHTML;
    });
  };

  class FarmIsolatedRootErrorBoundary extends options.ReactRuntime.Component<
    { children?: React.ReactNode; onError(error: unknown): void },
    { failed: boolean }
  > {
    state = { failed: false };

    static getDerivedStateFromError() {
      return { failed: true };
    }

    componentDidCatch(error: unknown) {
      this.props.onError(error);
    }

    render() {
      return this.state.failed ? null : this.props.children;
    }
  }

  const createBoundaryGraph = (
    Component: React.ComponentType<any>,
    props: Record<string, unknown>,
    restore: (error: unknown) => void,
  ) => {
    const componentElement = options.ReactRuntime.createElement(Component, props);
    const wrappedElement = options.wrap ? options.wrap(componentElement) : componentElement;
    return wrapFarmIsolatedClientGraph(
      options.ReactRuntime,
      options.ReactRuntime.createElement(
        FarmIsolatedRootErrorBoundary,
        { onError: restore },
        wrappedElement,
      ),
    );
  };

  async function hydrate(scope: ParentNode = document, signal?: AbortSignal): Promise<void> {
    const candidates = Array.from(
      scope.querySelectorAll<Element>("farm-client-boundary[data-farm-client-boundary]"),
    );
    if (
      scope instanceof Element &&
      scope.matches("farm-client-boundary[data-farm-client-boundary]")
    ) {
      candidates.unshift(scope);
    }
    const boundaries = candidates.filter((container) => {
      if (roots.has(container) || pending.has(container)) return false;
      return !container.parentElement?.closest("farm-client-boundary[data-farm-client-boundary]");
    });

    await Promise.all(
      boundaries.map(async (container) => {
        const reference = container.getAttribute("data-farm-client-boundary");
        const boundaryId = container.getAttribute("data-farm-client-id");
        const exportName = container.getAttribute("data-farm-client-export") || "default";
        const strategy =
          (container.getAttribute("data-farm-island-strategy") as FarmIslandStrategy | null) ??
          "load";
        if (!reference || !boundaryId) {
          report("An isolated client boundary is missing its module reference or payload ID.");
          return;
        }

        const controller = new AbortController();
        pending.set(container, controller);
        const abort = () => controller.abort();
        if (signal?.aborted) abort();
        else signal?.addEventListener("abort", abort, { once: true });
        const cleanup = () => {
          signal?.removeEventListener("abort", abort);
          if (pending.get(container) === controller) pending.delete(container);
        };

        let scheduled: Promise<unknown>;
        try {
          scheduled = options.schedule({
            container,
            strategy,
            signal: controller.signal,
            hydrate: async () => {
              if (controller.signal.aborted || !container.isConnected) return;
              const serverHTML = container.innerHTML;
              try {
                const module = await options.load(reference);
                if (controller.signal.aborted || !container.isConnected) return;
                const originals = module.__farm_client_boundary_originals__ as
                  | Record<string, unknown>
                  | undefined;
                const Component = originals?.[exportName];
                if (typeof Component !== "function" && typeof Component !== "object") {
                  throw new Error("compiled original export was not found");
                }
                const payload = findBoundaryPayload(container, boundaryId);
                if (!payload) throw new Error(`serialized props ${boundaryId} were not found`);
                const props = JSON.parse(payload.textContent || "{}");
                if (!props || typeof props !== "object" || Array.isArray(props)) {
                  throw new Error("serialized props must be an object");
                }

                let rootFailure: unknown;
                const restore = (error: unknown) => {
                  if (rootFailure !== undefined) return;
                  rootFailure = error;
                  failRoot(container, reference, exportName, serverHTML, error);
                  controller.abort();
                };
                const graphElement = createBoundaryGraph(
                  Component as React.ComponentType<any>,
                  props as Record<string, unknown>,
                  restore,
                );
                const root = options.hydrateRoot(container, graphElement, {
                  onUncaughtError: restore,
                });
                roots.set(container, {
                  root,
                  reference,
                  exportName,
                  props: props as Record<string, unknown>,
                  serverHTML,
                  restore,
                });
                container.setAttribute("data-farm-hydrated", "true");
              } catch (error) {
                failRoot(container, reference, exportName, serverHTML, error);
                controller.abort();
              }
            },
          });
        } catch (error) {
          failRoot(container, reference, exportName, container.innerHTML, error);
          controller.abort();
          cleanup();
          return;
        }

        const tracked = Promise.resolve(scheduled)
          .catch((error) => {
            if (!controller.signal.aborted) {
              failRoot(container, reference, exportName, container.innerHTML, error);
              controller.abort();
            }
          })
          .finally(cleanup);
        if (strategy === "load") await tracked;
        else void tracked;
      }),
    );
  }

  function updateModule(reference: string, module: Record<string, unknown>): number {
    const originals = module.__farm_client_boundary_originals__ as
      | Record<string, unknown>
      | undefined;
    let updated = 0;

    for (const [container, record] of roots) {
      if (record.reference !== reference) continue;
      const Component = originals?.[record.exportName];
      if (typeof Component !== "function" && typeof Component !== "object") {
        failRoot(
          container,
          record.reference,
          record.exportName,
          record.serverHTML,
          new Error("updated compiled original export was not found"),
        );
        continue;
      }

      try {
        record.root.render(
          createBoundaryGraph(Component as React.ComponentType<any>, record.props, record.restore),
        );
        updated++;
      } catch (error) {
        failRoot(container, record.reference, record.exportName, record.serverHTML, error);
      }
    }

    return updated;
  }

  function dispose(scope: Node): void {
    for (const [container, controller] of pending) {
      if (container === scope || scope.contains(container)) {
        controller.abort();
        pending.delete(container);
      }
    }
    for (const [container, record] of roots) {
      if (container === scope || scope.contains(container)) {
        try {
          record.root.unmount();
        } catch {
          // The DOM owner may already have removed a failed root.
        }
        roots.delete(container);
        container.removeAttribute("data-farm-hydrated");
      }
    }
  }

  return {
    hydrate,
    updateModule,
    dispose,
    rootCount: () => roots.size,
  };
}
