import type React from "react";
import type { FarmIslandStrategy } from "../island";

const REACT_ELEMENT_TYPE = Symbol.for("react.transitional.element");
const LEGACY_REACT_ELEMENT_TYPE = Symbol.for("react.element");

function serializeBoundaryProps(value: unknown, seen = new Set<object>()): unknown {
  if (value === null || typeof value === "string" || typeof value === "boolean") return value;
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new TypeError("non-finite numbers are not serializable");
    return value;
  }
  if (typeof value === "undefined") {
    throw new TypeError("undefined values are not serializable");
  }
  if (typeof value !== "object") {
    throw new TypeError(`${typeof value} values are not serializable`);
  }
  if (
    (value as { $$typeof?: symbol }).$$typeof === REACT_ELEMENT_TYPE ||
    (value as { $$typeof?: symbol }).$$typeof === LEGACY_REACT_ELEMENT_TYPE
  ) {
    throw new TypeError("React elements cannot cross an isolated hydration boundary");
  }
  if (seen.has(value)) throw new TypeError("circular props are not serializable");
  seen.add(value);
  try {
    if (Array.isArray(value)) return value.map((entry) => serializeBoundaryProps(entry, seen));
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) {
      throw new TypeError("class instances are not serializable");
    }
    return Object.fromEntries(
      Object.entries(value).map(([key, entry]) => [key, serializeBoundaryProps(entry, seen)]),
    );
  } finally {
    seen.delete(value);
  }
}

/** @internal Generated by Farm's experimental isolated-hydration transform. */
export function createFarmIsolatedClientBoundary(
  ReactRuntime: typeof React,
  Component: React.ComponentType<any>,
  moduleReference: string,
  exportName: string,
  islandStrategy: FarmIslandStrategy,
): React.ComponentType<any> {
  function FarmIsolatedClientBoundary(props: Record<string, unknown>) {
    let serializedProps: string;
    try {
      serializedProps = JSON.stringify(serializeBoundaryProps(props));
    } catch (error) {
      if (typeof window === "undefined") {
        console.warn(
          `[Farm.js] Could not isolate ${moduleReference}#${exportName}: ${
            error instanceof Error ? error.message : String(error)
          }. The server-rendered component was preserved without client hydration.`,
        );
      }
      return ReactRuntime.createElement(Component, props);
    }

    return ReactRuntime.createElement(
      "farm-client-boundary",
      {
        "data-farm-client-boundary": moduleReference,
        "data-farm-client-export": exportName,
        "data-farm-client-props": serializedProps,
        "data-farm-island-strategy": islandStrategy,
        style: { display: "contents" },
      },
      ReactRuntime.createElement(Component, props),
    );
  }

  FarmIsolatedClientBoundary.displayName = `FarmIsolated(${
    Component.displayName || Component.name || exportName
  })`;
  return FarmIsolatedClientBoundary;
}
