/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { PluginAPIRouter } from "@farm.js/core/api";
import type FarmPluginConfig0 from "../../farm.config";
import type { GET as GET_projects } from "../app/api/projects/route";
import type { POST as POST_projects } from "../app/api/projects/route";

// Type-only representation of your API routes
export type APIRouter = PluginAPIRouter<typeof FarmPluginConfig0> & {
  projects: {
    get: typeof GET_projects;
    post: typeof POST_projects;
  };
};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/mcp",
    methods: ["DELETE", "GET", "POST"],
  },
  {
    path: "/api/projects",
    methods: ["GET", "POST"],
  },
] as const;
