/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { GET as GET_status } from "../app/api/status/route";

// Type-only representation of your API routes
export type APIRouter = {
  status: {
    get: typeof GET_status;
  };
};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/status",
    methods: ["GET"],
  },
] as const;
