import { mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  readFarmI18nCatalogs,
  type FarmI18nArgumentKind,
  type FarmI18nMessageSignature,
} from "./catalog";
import type { ResolvedFarmI18nConfig } from "./types";
import { writeFileIfChanged } from "../write-file-if-changed";

export interface GenerateFarmI18nTypesOptions {
  root: string;
  srcDir?: string;
  config: ResolvedFarmI18nConfig;
  outFile?: string;
}

export async function generateFarmI18nTypes(
  options: GenerateFarmI18nTypesOptions,
): Promise<string | undefined> {
  if (!options.config.enabled) return undefined;

  const { signatures } = await readFarmI18nCatalogs(options.config);
  const outFile = options.outFile
    ? resolve(options.root, options.outFile)
    : join(resolve(options.root), options.srcDir || "src", "farm-i18n.d.ts");
  const content = renderFarmI18nTypes(options.config.locales, signatures);

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileIfChanged(outFile, content);
  return outFile;
}

export function renderFarmI18nTypes(
  locales: readonly string[],
  signatures: Record<string, FarmI18nMessageSignature>,
): string {
  const localeEntries = locales.map((locale) => `    ${JSON.stringify(locale)}: true;`);
  const messageEntries = Object.entries(signatures)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, signature]) => `    ${JSON.stringify(key)}: ${renderSignature(signature)};`);

  return `// Generated by Farm.js. Do not edit.
import "@farmjs/core/i18n";

declare module "@farmjs/core/i18n" {
  interface FarmI18nLocaleRegistry {
${localeEntries.join("\n")}
  }

  interface FarmI18nMessageRegistry {
${messageEntries.join("\n")}
  }
}

export {};
`;
}

function renderSignature(signature: FarmI18nMessageSignature): string {
  const entries = Object.entries(signature).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) return "Record<never, never>";
  return `{ ${entries
    .map(([name, kind]) => `${JSON.stringify(name)}: ${argumentType(kind)}`)
    .join("; ")} }`;
}

function argumentType(kind: FarmI18nArgumentKind): string {
  switch (kind) {
    case "number":
      return "number";
    case "date":
      return "Date | number";
    case "rich":
      return "(chunks: unknown[]) => unknown";
    case "select":
    case "string":
      return "string";
  }
}
