import { defineConfig, type Options } from "tsup";

export const farmPackageBuildOptions = {
  entry: {
    index: "src/index.ts",
    version: "src/version.ts",
    server: "src/server.ts",
    client: "src/client.ts",
    vite: "src/vite.ts",
    "server-plugins": "src/server-plugins.ts",
    "client-plugins": "src/client-plugins.ts",
    "query/index": "src/query/index.ts",
    "query/parsers": "src/query/parsers.ts",
    "query/client": "src/query/client.ts",
    "query/server": "src/query/server.ts",
    middleware: "src/middleware/index.ts",
    api: "src/api/index.ts",
    "api/runtime": "src/api/runtime.ts",
    "api/route-manager": "src/api/route-manager.ts",
    router: "src/router.ts",
    routes: "src/routes.ts",
    request: "src/request.ts",
    plugin: "src/plugin.ts",
    integrations: "src/integrations.ts",
    storage: "src/storage/index.ts",
    cache: "src/cache.ts",
    deferred: "src/deferred.ts",
    after: "src/after.ts",
    navigation: "src/navigation.ts",
    headers: "src/headers.ts",
    "theme/index": "src/theme/index.ts",
    "theme/client": "src/theme/client.tsx",
    "theme/server": "src/theme/server.ts",
    docs: "src/docs/index.ts",
    markdown: "src/markdown.ts",
    "app-markdown": "src/app-markdown.ts",
    observability: "src/observability.ts",
    workflows: "src/workflows.ts",
    cron: "src/cron.ts",
    "server-fn": "src/server-fn.ts",
    "server-fn-client": "src/server-fn-client.ts",
    "server-query": "src/server-query.ts",
    "server-query-client": "src/server-query-client.ts",
    "server-action-security": "src/server-action-security.ts",
    deployment: "src/deployment.ts",
    env: "src/env.ts",
    "env-types": "src/env-types.ts",
    environment: "src/environment.ts",
    font: "src/font.ts",
    "environment/vite": "src/environment-vite.ts",
    testing: "src/testing.ts",
    "agent-runtime": "src/agent-runtime.ts",
    image: "src/image.tsx",
    "image/server": "src/image-server.ts",
    "image/sharp": "src/image-sharp.ts",
    "i18n/index": "src/i18n/index.ts",
    "i18n/server": "src/i18n/server.ts",
    "i18n/client": "src/i18n/client.tsx",
    "internal/client-runtime": "src/client/production-runtime.ts",
    "internal/production-runtime": "src/nitro/production-runtime.ts",
    "internal/metadata-image-runtime": "src/metadata-image.ts",
    "internal/build-runtime": "src/nitro/build-runtime.ts",
    "internal/config-runtime": "src/config-runtime.ts",
    "internal/production-node-env": "src/build/production-node-env.ts",
    config: "src/config-entry.ts",
  },
  format: ["cjs", "esm"],
  dts: true,
  clean: true,
  external: [
    "react",
    "react-dom",
    "@vercel/og",
    "rolldown",
    "sharp",
    "vite",
    "vite-rolldown",
    /^@farming-labs\/orm/,
  ],
  sourcemap: true,
  treeshake: false,
  esbuildOptions(options) {
    options.keepNames = true;
    return options;
  },
  outExtension({ format }) {
    return { js: format === "cjs" ? ".cjs" : ".mjs" };
  },
} satisfies Options;

export default defineConfig(farmPackageBuildOptions);
