import { mkdir, readFile, realpath, writeFile } from "node:fs/promises";
import path from "node:path";
import fg from "fast-glob";
import matter from "gray-matter";
import { parse as parseYaml } from "yaml";
import {
  mergeContentAssetData,
  resolveContentAssetFields,
  splitContentAssetInput,
  type ContentAssetImport,
} from "./assets.js";
import { isSupportedContentFile } from "./config.js";
import { resolveMarkdownAssets } from "./markdown-assets.js";
import type {
  ContentCollection,
  ContentCollections,
  ContentEntry,
  ContentFileSource,
  ContentSchema,
  ContentSchemaIssue,
} from "./types.js";

export interface LoadedContent {
  readonly collections: Readonly<Record<string, readonly ContentEntry<any>[]>>;
  readonly sourceFiles: ReadonlySet<string>;
  readonly assetImports: ReadonlyMap<string, ContentAssetImport>;
}

export async function loadContentCollections(
  root: string,
  collections: ContentCollections,
): Promise<LoadedContent> {
  const loaded: Record<string, readonly ContentEntry<any>[]> = Object.create(null);
  const sourceFiles = new Set<string>();
  const assetImports = new Map<string, ContentAssetImport>();

  for (const [name, definition] of Object.entries(collections)) {
    validateCollectionName(name);
    const entries = await loadCollection(root, name, definition, sourceFiles, assetImports);
    loaded[name] = Object.freeze(entries);
  }

  return {
    collections: Object.freeze(loaded),
    sourceFiles,
    assetImports,
  };
}

export async function writeContentServerModule(
  outputFile: string,
  collections: Readonly<Record<string, readonly ContentEntry<any>[]>>,
  assetImports: ReadonlyMap<string, ContentAssetImport> = new Map(),
): Promise<void> {
  const outputDirectory = path.dirname(outputFile);
  await mkdir(outputDirectory, { recursive: true });
  const actualOutputDirectory = await realpath(outputDirectory);
  const encoded = encodeContentValue(collections);
  const imports = [...assetImports.values()].sort((left, right) =>
    left.token.localeCompare(right.token),
  );
  const importSource = imports
    .map(
      (asset, index) =>
        `import farmContentAsset${index} from ${JSON.stringify(
          `${toViteImportSpecifier(actualOutputDirectory, asset.filePath)}?url`,
        )};`,
    )
    .join("\n");
  const assetUrls = imports.length
    ? `, { ${imports
        .map((asset, index) => `${JSON.stringify(asset.token)}: farmContentAsset${index}`)
        .join(", ")} }`
    : "";
  const source = `// Generated by @farm.js/content. Do not edit.
import { createContentRuntime, decodeContentValue } from "@farm.js/content/internal/runtime";
${importSource ? `\n${importSource}` : ""}

const runtime = createContentRuntime(decodeContentValue(${JSON.stringify(encoded)}${assetUrls}));

export const getCollection = runtime.getCollection;
export const getEntry = runtime.getEntry;
export const getEntryOrThrow = runtime.getEntryOrThrow;
`;
  await writeFileIfChanged(outputFile, source);
}

async function loadCollection(
  root: string,
  name: string,
  definition: ContentCollection<any>,
  sourceFiles: Set<string>,
  assetImports: Map<string, ContentAssetImport>,
): Promise<ContentEntry<any>[]> {
  const source = definition.source;
  const relativeFiles = await fg([...source.patterns], {
    cwd: root,
    absolute: false,
    onlyFiles: true,
    unique: true,
    dot: false,
    followSymbolicLinks: false,
    ignore: [...source.ignore],
  });
  const files = relativeFiles
    .map(normalizePath)
    .filter(isSupportedContentFile)
    .sort((left, right) => left.localeCompare(right));
  const entries: ContentEntry<any>[] = [];
  const ids = new Map<string, string>();

  for (const relativeFile of files) {
    const absoluteFile = path.resolve(root, relativeFile);
    const id = contentEntryId(relativeFile, source);
    const duplicate = ids.get(id);
    if (duplicate) {
      throw new Error(
        `[farm:content] Collection "${name}" has duplicate entry ID "${id}" from ${duplicate} and ${relativeFile}`,
      );
    }
    ids.set(id, relativeFile);
    sourceFiles.add(absoluteFile);

    const parsed = await parseContentFile(absoluteFile, relativeFile);
    const assetContext = {
      root,
      collectionName: name,
      sourceFile: relativeFile,
      sourceFiles,
      imports: assetImports,
    };
    const typedAssets =
      definition.assets && definition.assets !== true ? definition.assets : undefined;
    let schemaInput = parsed.data;
    let assetInput: unknown;
    if (typedAssets) {
      try {
        const split = splitContentAssetInput(parsed.data, typedAssets);
        schemaInput = split.schemaInput;
        assetInput = split.assetInput;
      } catch (error) {
        throw new Error(
          `[farm:content] Collection ${JSON.stringify(name)} rejected ${relativeFile}: ${errorMessage(error)}`,
          { cause: error },
        );
      }
    }
    const validatedData = await validateContentData(
      definition.schema,
      schemaInput,
      name,
      relativeFile,
    );
    const data = typedAssets
      ? mergeContentAssetData(
          validatedData,
          await resolveContentAssetFields(typedAssets, assetInput, assetContext),
          assetContext,
        )
      : validatedData;
    const resolvedBody =
      definition.assets && /\.mdx?$/i.test(relativeFile)
        ? await resolveMarkdownAssets(parsed.body, assetContext)
        : { body: parsed.body, assets: Object.freeze([]) };
    const baseEntry = {
      id,
      data,
      body: resolvedBody.body,
      bodyAssets: resolvedBody.assets,
      filePath: relativeFile,
      words: countWords(resolvedBody.body),
    };
    const transformed = definition.transform
      ? await definition.transform(baseEntry)
      : baseEntry.data;

    entries.push(
      Object.freeze({
        id,
        data: freezeContentValue(transformed),
        body: resolvedBody.body,
        bodyAssets: freezeContentValue(resolvedBody.assets),
        filePath: relativeFile,
      }),
    );
  }

  return entries;
}

async function parseContentFile(
  absoluteFile: string,
  relativeFile: string,
): Promise<{ data: unknown; body: string }> {
  const source = await readFile(absoluteFile, "utf8");
  const extension = path.extname(relativeFile).toLowerCase();
  try {
    if (extension === ".md" || extension === ".mdx") {
      const parsed = matter(source);
      return { data: parsed.data, body: parsed.content };
    }
    if (extension === ".json") {
      return { data: JSON.parse(source), body: "" };
    }
    if (extension === ".yaml" || extension === ".yml") {
      return { data: parseYaml(source), body: "" };
    }
  } catch (error) {
    throw new Error(`[farm:content] Could not parse ${relativeFile}: ${errorMessage(error)}`, {
      cause: error,
    });
  }
  throw new Error(`[farm:content] Unsupported content file: ${relativeFile}`);
}

async function validateContentData<TOutput>(
  schema: ContentSchema<TOutput>,
  input: unknown,
  collectionName: string,
  filePath: string,
): Promise<TOutput> {
  try {
    const standard = schema["~standard"];
    if (standard) {
      const result = await standard.validate(input);
      if (result.issues?.length) {
        throw new ContentValidationError(formatIssues(result.issues));
      }
      return result.value as TOutput;
    }
    if (schema.parseAsync) return await schema.parseAsync(input);
    if (schema.parse) return schema.parse(input);
  } catch (error) {
    const details =
      error instanceof ContentValidationError ? error.message : formatSchemaError(error);
    throw new Error(
      `[farm:content] Collection "${collectionName}" rejected ${filePath}: ${details}`,
      { cause: error },
    );
  }
  throw new TypeError(`[farm:content] Collection "${collectionName}" has an invalid schema`);
}

class ContentValidationError extends Error {}

function formatSchemaError(error: unknown): string {
  if (error && typeof error === "object" && "issues" in error) {
    const issues = (error as { issues?: readonly ContentSchemaIssue[] }).issues;
    if (issues?.length) return formatIssues(issues);
  }
  return errorMessage(error);
}

function formatIssues(issues: readonly ContentSchemaIssue[]): string {
  return issues
    .map((issue) => {
      const pathLabel = issue.path?.length
        ? `${issue.path.map(formatIssuePathSegment).join(".")}: `
        : "";
      return `${pathLabel}${issue.message}`;
    })
    .join("; ");
}

function formatIssuePathSegment(segment: unknown): string {
  if (segment && typeof segment === "object" && "key" in segment) {
    return String((segment as { key: unknown }).key);
  }
  return String(segment);
}

function contentEntryId(filePath: string, source: ContentFileSource): string {
  const base = source.base ?? inferCommonSourceBase(source.patterns);
  const relative = base && base !== "." ? path.posix.relative(base, filePath) : filePath;
  if (relative === ".." || relative.startsWith("../") || path.posix.isAbsolute(relative)) {
    throw new Error(
      `[farm:content] Source file ${filePath} is outside the configured content base ${base}`,
    );
  }
  return relative.replace(/\.(?:mdx?|json|ya?ml)$/i, "").replace(/(?:^|\/)index$/, "") || "index";
}

function inferCommonSourceBase(patterns: readonly string[]): string {
  const bases = patterns.map(inferSourceBase).map((base) => base.split("/").filter(Boolean));
  const [first = [], ...rest] = bases;
  const common: string[] = [];
  for (let index = 0; index < first.length; index += 1) {
    const segment = first[index];
    if (!rest.every((base) => base[index] === segment)) break;
    common.push(segment);
  }
  return common.join("/");
}

function inferSourceBase(pattern: string): string {
  const segments = normalizePath(pattern).split("/");
  const staticSegments: string[] = [];
  for (const segment of segments) {
    if (/[*?{}()[\]!]/.test(segment)) break;
    staticSegments.push(segment);
  }
  if (staticSegments.length > 0 && path.posix.extname(staticSegments.at(-1) ?? "")) {
    staticSegments.pop();
  }
  return staticSegments.join("/");
}

function validateCollectionName(name: string): void {
  if (!/^[A-Za-z][A-Za-z0-9_-]*$/.test(name)) {
    throw new TypeError(
      `[farm:content] Collection name "${name}" must start with a letter and contain only letters, numbers, underscores, or hyphens`,
    );
  }
}

function countWords(body: string): number {
  const normalized = body.trim();
  return normalized ? normalized.split(/\s+/).length : 0;
}

function normalizePath(value: string): string {
  return value.replace(/\\/g, "/");
}

function toViteImportSpecifier(outputDirectory: string, filePath: string): string {
  const relative = normalizePath(path.relative(outputDirectory, filePath));
  return relative.startsWith(".") ? relative : `./${relative}`;
}

type EncodedContentValue =
  | null
  | boolean
  | number
  | string
  | ["undefined"]
  | ["date", string]
  | ["bigint", string]
  | ["array", EncodedContentValue[]]
  | ["object", Array<[string, EncodedContentValue]>];

export function encodeContentValue(value: unknown, seen = new Set<object>()): EncodedContentValue {
  if (value === null || typeof value === "boolean" || typeof value === "string") return value;
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new TypeError("[farm:content] Content data cannot contain non-finite numbers");
    }
    return value;
  }
  if (value === undefined) return ["undefined"];
  if (typeof value === "bigint") return ["bigint", value.toString()];
  if (typeof value === "function" || typeof value === "symbol") {
    throw new TypeError(`[farm:content] Content data cannot contain ${typeof value} values`);
  }
  if (value instanceof Date) {
    if (Number.isNaN(value.getTime())) {
      throw new TypeError("[farm:content] Content data cannot contain an invalid Date");
    }
    return ["date", value.toISOString()];
  }
  if (seen.has(value)) {
    throw new TypeError("[farm:content] Content data cannot contain circular references");
  }
  seen.add(value);
  try {
    if (Array.isArray(value)) return ["array", encodeArray(value, seen)];
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== Object.prototype && prototype !== null) {
      throw new TypeError(
        `[farm:content] Content data must use plain objects, arrays, dates, bigints, and primitive values`,
      );
    }
    return ["object", encodeObject(value, seen)];
  } finally {
    seen.delete(value);
  }
}

function encodeArray(value: unknown[], seen: Set<object>): EncodedContentValue[] {
  const descriptors = Object.getOwnPropertyDescriptors(value);
  const keys = Reflect.ownKeys(value).filter((key) => key !== "length");
  for (const key of keys) {
    if (typeof key === "symbol" || !isArrayIndex(key, value.length)) {
      throw new TypeError("[farm:content] Content arrays cannot contain custom properties");
    }
  }

  return Array.from({ length: value.length }, (_, index) => {
    const descriptor = descriptors[index];
    if (!descriptor) {
      throw new TypeError("[farm:content] Content data cannot contain sparse arrays");
    }
    assertSerializableProperty(descriptor);
    return encodeContentValue(descriptor.value, seen);
  });
}

function encodeObject(value: object, seen: Set<object>): Array<[string, EncodedContentValue]> {
  const descriptors = Object.getOwnPropertyDescriptors(value);
  return Reflect.ownKeys(value).map((key) => {
    if (typeof key === "symbol") {
      throw new TypeError("[farm:content] Content objects cannot contain symbol keys");
    }
    const descriptor = descriptors[key];
    assertSerializableProperty(descriptor);
    return [key, encodeContentValue(descriptor.value, seen)];
  });
}

function assertSerializableProperty(
  descriptor: PropertyDescriptor,
): asserts descriptor is PropertyDescriptor & {
  value: unknown;
} {
  if (!("value" in descriptor)) {
    throw new TypeError("[farm:content] Content data cannot contain getters or setters");
  }
  if (!descriptor.enumerable) {
    throw new TypeError("[farm:content] Content data cannot contain non-enumerable properties");
  }
}

function isArrayIndex(key: string, length: number): boolean {
  const index = Number(key);
  return Number.isInteger(index) && index >= 0 && index < length && String(index) === key;
}

function freezeContentValue<T>(value: T, ancestors = new Set<object>()): T {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  if (ancestors.has(value)) {
    throw new TypeError("[farm:content] Content data cannot contain circular references");
  }
  ancestors.add(value);
  try {
    if (Array.isArray(value)) {
      for (const descriptor of Object.values(Object.getOwnPropertyDescriptors(value))) {
        if ("value" in descriptor) freezeContentValue(descriptor.value, ancestors);
      }
    } else if (!(value instanceof Date)) {
      for (const descriptor of Object.values(Object.getOwnPropertyDescriptors(value))) {
        if ("value" in descriptor) freezeContentValue(descriptor.value, ancestors);
      }
    }
    return Object.freeze(value);
  } finally {
    ancestors.delete(value);
  }
}

async function writeFileIfChanged(filePath: string, source: string): Promise<void> {
  try {
    if ((await readFile(filePath, "utf8")) === source) return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await writeFile(filePath, source, "utf8");
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
