// Generated by Farm.js. Do not edit.
import "@farmjs/core/i18n";

declare module "@farmjs/core/i18n" {
  interface FarmI18nLocaleRegistry {
    "en": true;
    "am": true;
    "ar": true;
  }

  interface FarmI18nMessageRegistry {
    "home.current": { "locale": string };
    "home.description": Record<never, never>;
    "home.eyebrow": Record<never, never>;
    "home.localeLabel": Record<never, never>;
    "home.messageLabel": Record<never, never>;
    "home.numberLabel": Record<never, never>;
    "home.title": Record<never, never>;
    "home.visits": { "count": number };
    "locale.amharic": Record<never, never>;
    "locale.arabic": Record<never, never>;
    "locale.english": Record<never, never>;
    "locale.switch": Record<never, never>;
  }
}

export {};
