/**
 * Generated by Farm.js. Do not edit.
 * Contains project-specific route, environment, and internationalization types.
 */

import "@farm.js/core/image";

/**
 * Auto-generated route types from src/app.
 * Link href is typed automatically via module augmentation. Regenerated on dev start and when routes change.
 * Set suppressLintOnLink: true in farm.config.ts to accept any string on Link href.
 */
export type RoutePath = "/";
export type RoutePattern = "/";
declare module "@farm.js/core/client" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

declare module "@farm.js/core" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
  // Ensure root import ("@farm.js/core") uses the same typed Link signature as client entry.
  const Link: typeof import("@farm.js/core/client").Link;
}

// Internal declaration path used by @farm.js/core root type re-exports.
declare module "@farm.js/core/dist/client.js" {
  interface LinkDefaultRoute {
    _: import("./farm").RoutePath;
    pattern: import("./farm").RoutePattern;
  }
}

/**
 * Auto-generated env types from farm.config.
 * Regenerated on dev start, build, and farm generate.
 */
import type FarmConfig from "../farm.config";
import type { InferEnv } from "@farm.js/core/env";

type FarmConfigEnv = typeof FarmConfig extends { env?: infer TEnv } ? NonNullable<TEnv> : never;
type FarmResolvedEnv = [FarmConfigEnv] extends [never]
  ? { server: {}; public: {} }
  : InferEnv<FarmConfigEnv>;

declare module "@farm.js/core/env" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

declare module "@farm.js/core" {
  interface FarmEnvTypes {
    server: FarmResolvedEnv["server"];
    public: FarmResolvedEnv["public"];
  }
}

export {};

// Generated by Farm.js. Do not edit.
import "@farm.js/core/i18n";

declare module "@farm.js/core/i18n" {
  interface FarmI18nLocaleRegistry {
    "en": true;
    "am": true;
    "ar": true;
  }

  interface FarmI18nMessageRegistry {
    "home.current": { "locale": string };
    "home.description": Record<never, never>;
    "home.eyebrow": Record<never, never>;
    "home.localeLabel": Record<never, never>;
    "home.messageLabel": Record<never, never>;
    "home.numberLabel": Record<never, never>;
    "home.title": Record<never, never>;
    "home.visits": { "count": number };
    "locale.amharic": Record<never, never>;
    "locale.arabic": Record<never, never>;
    "locale.english": Record<never, never>;
    "locale.switch": Record<never, never>;
  }
}

export {};
