/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { POST as POST_greeting } from "../app/api/greeting/route";

// Type-only representation of your API routes
export type APIRouter = {
  greeting: {
    post: typeof POST_greeting;
  };
};
