import * as fs from 'fs';
import * as path from 'path';
import type { APIRouteManager } from '../api/route-manager';

/**
 * Generate Nitro route files from Farm.js API routes
 * This creates actual route files that Nitro can consume
 */
export async function generateNitroRoutes(
  apiRouteManager: APIRouteManager,
  outputDir: string
): Promise<void> {
  const routes = apiRouteManager.getRoutes();
  const serverApiDir = path.join(outputDir, 'server', 'api');
  
  // Create server/api directory
  await fs.promises.mkdir(serverApiDir, { recursive: true });
  
  for (const [routePath, route] of routes) {
    // Convert /api/auth/login -> auth/login
    const relativePath = routePath.replace(/^\/api\//, '');
    const routeDir = path.join(serverApiDir, relativePath);
    
    // Create directory structure
    await fs.promises.mkdir(routeDir, { recursive: true });
    
    // Generate route.ts file
    const routeFile = path.join(routeDir, 'route.ts');
    
    // Generate handler code
    const handlerCode = generateRouteHandler(route, routePath);
    
    await fs.promises.writeFile(routeFile, handlerCode, 'utf-8');
  }
}

/**
 * Generate route handler code for Nitro
 */
function generateRouteHandler(route: any, routePath: string): string {
  const methods = route.methods.map((m: string) => `'${m.toLowerCase()}'`).join(', ');
  
  return `// Auto-generated by Farm.js
// Route: ${routePath}
// Methods: ${route.methods.join(', ')}

import { defineEventHandler, readBody, getQuery, setResponseStatus, setHeaders } from 'h3';

export default defineEventHandler(async (event) => {
  const method = event.node.req.method?.toUpperCase();
  
  // Handle different HTTP methods
  switch (method) {
${route.methods.map((method: string) => generateMethodHandler(method, routePath)).join('\n')}
    default:
      setResponseStatus(event, 405);
      return { error: 'Method not allowed' };
  }
});

${route.methods.map((method: string) => generateMethodFunction(method, routePath)).join('\n\n')}
`;
}

function generateMethodHandler(method: string, routePath: string): string {
  const methodLower = method.toLowerCase();
  return `    case '${method}':
      return await handle${method}${methodLower}(event);`;
}

function generateMethodFunction(method: string, routePath: string): string {
  const methodLower = method.toLowerCase();
  return `async function handle${method}${methodLower}(event: any) {
  // This will be replaced with actual route handler at build time
  // For now, return a placeholder
  setResponseStatus(event, 501);
  return { error: 'Route handler not implemented' };
}`;
}

