import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import {
  buildDocsAgentDiscoverySpec,
  buildDocsSitemapManifest,
  isDocsAgentDiscoveryRequest,
  isDocsAgentsRequest,
  isDocsSkillRequest,
  renderDocsAgentsDocument,
  renderDocsLlmsTxt,
  renderDocsMarkdownDocument,
  renderDocsRobotsTxt,
  renderDocsSitemapMarkdown,
  renderDocsSitemapXml,
  renderDocsSkillDocument,
  resolveDocsLlmsTxtFormat,
  resolveDocsRobotsRequest,
  resolveDocsSitemapRequest,
  type DocsLlmsTxtPageInput,
  type DocsMarkdownPage,
  type DocsSitemapPageInput,
} from "@farming-labs/docs";
import { marked, Renderer } from "marked";
import { highlight } from "sugar-high";
import type { FarmLayoutFonts } from "../font";
import {
  resolveFarmDocsFontAssets,
  toFarmDocsPublicFontAssets,
  type FarmDocsPublicFontAsset,
} from "./fonts";
import { resolveFarmDocsPageLastModified } from "./last-modified";
import { generateFarmDocsSearchBootstrapRuntime, isFarmDocsSearchEnabled } from "./search-client";
import {
  createFarmDocsSocialImageDescriptor,
  getFarmDocsCustomSocialImage,
  getFarmDocsSocialImageSlug,
  isFarmDocsSocialImageEnabled,
  renderFarmDocsSocialImageSvg,
  renderFarmDocsSocialMetadata,
} from "./social-image";
import type { FarmDocsResolvedConfig } from "./types";

export interface FarmDocsHandlerOptions {
  root: string;
  srcDir?: string;
  clientEntry?: string;
  fontAssets?: readonly FarmDocsPublicFontAsset[];
  /** Resolve semantic fonts from the layouts that apply to the requested docs route. */
  resolveLayoutFonts?: (
    pathname: string,
  ) => FarmLayoutFonts | undefined | Promise<FarmLayoutFonts | undefined>;
  /** Stylesheet containing the `@font-face` rules generated by Farm's font compiler. */
  fontStylesheetHref?: string;
  /** Application-owned global stylesheet, including the selected docs theme CSS import. */
  globalStylesheetHref?: string;
}

export interface FarmDocsPage {
  slug: string;
  title: string;
  description?: string;
  section?: string;
  href: string;
  sourcePath: string;
  lastModified?: string;
}

export interface LoadedFarmDocsPage extends FarmDocsPage {
  body: string;
  frontmatter: Record<string, string>;
}

const DOCS_FILE_NAMES = ["page.mdx", "page.md", "index.mdx", "index.md"];
const DOCS_FILE_EXTENSIONS = [".mdx", ".md"];
const FARM_DOCS_FALLBACK_FAVICON =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' fill='black'/%3E%3Cpath d='M7 8h18v3H10v5h12v3H10v5H7z' fill='white'/%3E%3C/svg%3E";
const FARM_DOCS_FAVICON_FILES = ["favicon.svg", "favicon.ico", "favicon.png"];

function trimSlashes(value: string): string {
  return value.replace(/^\/+|\/+$/g, "");
}

function normalizeEntry(entry: string | undefined): string {
  if (!entry || entry === "/") return "/";
  return `/${trimSlashes(entry)}`;
}

function normalizeSlug(value: string): string {
  return trimSlashes(decodeURIComponent(value)).replace(/\.(mdx?|markdown)$/i, "");
}

function resolveFarmDocsFavicon(
  docs: FarmDocsResolvedConfig | undefined,
  options: FarmDocsHandlerOptions,
): string {
  const configuredFavicon = docs?.config.favicon;
  if (typeof configuredFavicon === "string" && configuredFavicon.trim()) {
    return configuredFavicon.trim();
  }

  const publicDir = path.join(path.resolve(options.root), "public");

  for (const fileName of FARM_DOCS_FAVICON_FILES) {
    const faviconPath = path.join(publicDir, fileName);
    if (existsSync(faviconPath) && statSync(faviconPath).isFile()) {
      return `/${fileName}`;
    }
  }

  return FARM_DOCS_FALLBACK_FAVICON;
}

function renderFarmDocsFaviconLink(faviconHref: string): string {
  const normalizedHref = faviconHref.split(/[?#]/, 1)[0]?.toLowerCase() || "";
  const type =
    normalizedHref.endsWith(".svg") || faviconHref.startsWith("data:image/svg+xml")
      ? "image/svg+xml"
      : normalizedHref.endsWith(".png")
        ? "image/png"
        : normalizedHref.endsWith(".ico")
          ? "image/x-icon"
          : undefined;
  const metadata =
    type === "image/svg+xml" ? ' sizes="any" type="image/svg+xml"' : type ? ` type="${type}"` : "";

  return `<link rel="icon" href="${escapeAttribute(faviconHref)}"${metadata}>`;
}

function renderFarmDocsBrandMark(): string {
  return `<svg class="sidebar-brand-logo" viewBox="0 0 24 24" aria-hidden="true" focusable="false">
    <rect x="2" y="2" width="5" height="5" rx="0.75" fill="currentColor"></rect>
    <path d="M9.75 2h11.5c.41 0 .75.34.75.75v3.5c0 .41-.34.75-.75.75H9.75A.75.75 0 0 1 9 6.25v-3.5c0-.41.34-.75.75-.75Zm9.75 1.62a.38.38 0 0 0-.38.38v1c0 .21.17.38.38.38h.75c.21 0 .38-.17.38-.38V4a.38.38 0 0 0-.38-.38h-.75Z" fill="currentColor"></path>
    <rect x="2" y="9.5" width="5" height="5" rx="0.75" fill="currentColor" opacity="0.64"></rect>
    <rect x="9" y="9.5" width="13" height="5" rx="0.75" fill="currentColor" opacity="0.64"></rect>
    <rect x="2" y="17" width="5" height="5" rx="0.75" fill="currentColor" opacity="0.34"></rect>
    <rect x="9" y="17" width="7.5" height="5" rx="0.75" fill="currentColor" opacity="0.34"></rect>
  </svg>`;
}

function renderFarmDocsBrandTitle(navTitle: string): string {
  const suffix = navTitle.match(/\.js$/i)?.[0];

  if (!suffix) {
    return `<span class="sidebar-brand-title">${escapeHtml(navTitle)}</span>`;
  }

  const productName = navTitle.slice(0, -suffix.length);
  return `<span class="sidebar-brand-title">${escapeHtml(productName)}<span class="sidebar-brand-suffix">${escapeHtml(suffix)}</span></span>`;
}

function isSafeSegment(segment: string): boolean {
  return segment !== ".." && !segment.includes("/") && !segment.includes("\\");
}

function resolveInside(root: string, target: string): string | null {
  const resolvedRoot = path.resolve(root);
  const resolvedTarget = path.resolve(target);
  const relative = path.relative(resolvedRoot, resolvedTarget);
  if (relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative))) {
    return resolvedTarget;
  }
  return null;
}

export function isFarmDocsRequest(docs: FarmDocsResolvedConfig | undefined, request: Request) {
  if (!docs?.enabled) return false;
  if (request.method !== "GET" && request.method !== "HEAD") return false;

  const pathname = new URL(request.url).pathname;
  const entry = normalizeEntry(docs.entry);
  if (entry === "/") return true;

  return pathname === entry || pathname === `${entry}.md` || pathname.startsWith(`${entry}/`);
}

export function resolveFarmDocsContentDir(
  docs: FarmDocsResolvedConfig,
  options: FarmDocsHandlerOptions,
): string {
  const root = path.resolve(options.root);
  const srcDir = options.srcDir || "src";
  const configuredContentDir = docs.contentDir || docs.config.contentDir;

  if (configuredContentDir) {
    return path.isAbsolute(configuredContentDir)
      ? configuredContentDir
      : path.join(root, configuredContentDir);
  }

  const entryDir = docs.config.entry || trimSlashes(docs.entry) || "docs";
  const appDocsDir = path.join(root, srcDir, "app", entryDir);
  if (existsSync(appDocsDir)) return appDocsDir;

  return path.join(root, entryDir);
}

export function getFarmDocsRouteTypeEntries(docs: FarmDocsResolvedConfig | undefined): string[] {
  if (!docs?.enabled) return [];
  const entry = normalizeEntry(docs.entry);
  if (entry === "/") return ["/", "/[...docs]"];
  return [entry, `${entry}/[...docs]`];
}

export function getFarmDocsDocumentNavigationMatchers(
  docs: FarmDocsResolvedConfig | undefined,
): string[] {
  if (!docs?.enabled) return [];
  const entry = normalizeEntry(docs.entry);
  return [entry === "/" ? "/(.*)" : `${entry}(.*)`];
}

function getRequestSlug(docs: FarmDocsResolvedConfig, request: Request): string {
  const pathname = new URL(request.url).pathname;
  const entry = normalizeEntry(docs.entry);

  if (entry === "/") return normalizeSlug(pathname);
  if (pathname === entry || pathname === `${entry}.md`) return "";

  return normalizeSlug(pathname.slice(entry.length));
}

function findDocsPageFile(contentDir: string, slug: string): string | null {
  const segments = slug ? slug.split("/").filter(Boolean) : [];
  if (!segments.every(isSafeSegment)) return null;

  const slugDir = path.join(contentDir, ...segments);
  const candidates =
    segments.length === 0
      ? DOCS_FILE_NAMES.map((filename) => path.join(contentDir, filename))
      : [
          ...DOCS_FILE_NAMES.map((filename) => path.join(slugDir, filename)),
          ...DOCS_FILE_EXTENSIONS.map((extension) => path.join(contentDir, `${slug}${extension}`)),
        ];

  for (const candidate of candidates) {
    const safePath = resolveInside(contentDir, candidate);
    if (safePath && existsSync(safePath) && statSync(safePath).isFile()) {
      return safePath;
    }
  }

  return null;
}

function parseFrontmatter(source: string): {
  frontmatter: Record<string, string>;
  body: string;
} {
  if (!source.startsWith("---")) {
    return { frontmatter: {}, body: source };
  }

  const endIndex = source.indexOf("\n---", 3);
  if (endIndex === -1) return { frontmatter: {}, body: source };

  const frontmatterSource = source.slice(3, endIndex).trim();
  const body = source.slice(source.indexOf("\n", endIndex + 1) + 1);
  const frontmatter: Record<string, string> = {};

  for (const line of frontmatterSource.split(/\r?\n/)) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    const key = line.slice(0, separator).trim();
    const value = line
      .slice(separator + 1)
      .trim()
      .replace(/^["']|["']$/g, "");
    if (key && value) frontmatter[key] = value;
  }

  return { frontmatter, body };
}

function titleFromSlug(slug: string): string {
  const lastSegment = slug.split("/").filter(Boolean).pop() || "Docs";
  return lastSegment
    .split(/[-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function titleFromMarkdown(body: string, fallback: string): string {
  const heading = body.match(/^#\s+(.+)$/m)?.[1]?.trim();
  return heading || fallback;
}

export function loadFarmDocsPage(
  contentDir: string,
  docs: FarmDocsResolvedConfig,
  slug: string,
): LoadedFarmDocsPage | null {
  const sourcePath = findDocsPageFile(contentDir, slug);
  if (!sourcePath) return null;

  const source = readFileSync(sourcePath, "utf8");
  const { frontmatter, body } = parseFrontmatter(source);
  const title = frontmatter.title || titleFromMarkdown(body, titleFromSlug(slug));
  const href = createDocsHref(docs.entry, slug);

  return {
    slug,
    title,
    description: frontmatter.description,
    section: frontmatter.section,
    href,
    sourcePath,
    lastModified: resolveFarmDocsPageLastModified(contentDir, sourcePath, frontmatter),
    frontmatter,
    body,
  };
}

function createDocsHref(entry: string, slug: string): string {
  const normalizedEntry = normalizeEntry(entry);
  const normalizedSlug = trimSlashes(slug);
  if (normalizedEntry === "/") return normalizedSlug ? `/${normalizedSlug}` : "/";
  return normalizedSlug ? `${normalizedEntry}/${normalizedSlug}` : normalizedEntry;
}

function pathToSlug(contentDir: string, filePath: string): string | null {
  const relative = path.relative(contentDir, filePath).replace(/\\/g, "/");
  if (relative.startsWith("..")) return null;

  const extension = path.extname(relative);
  if (!DOCS_FILE_EXTENSIONS.includes(extension)) return null;

  const withoutExtension = relative.slice(0, -extension.length);
  if (withoutExtension === "page" || withoutExtension === "index") return "";
  if (withoutExtension.endsWith("/page") || withoutExtension.endsWith("/index")) {
    return withoutExtension.replace(/\/(page|index)$/, "");
  }
  return withoutExtension;
}

function loadPage(
  contentDir: string,
  docs: FarmDocsResolvedConfig,
  request: Request,
): LoadedFarmDocsPage | null {
  return loadFarmDocsPage(contentDir, docs, getRequestSlug(docs, request));
}

export function discoverFarmDocsPages(
  contentDir: string,
  docs: FarmDocsResolvedConfig,
): FarmDocsPage[] {
  if (!existsSync(contentDir)) return [];

  const pages: FarmDocsPage[] = [];
  const visit = (dir: string) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
      const absolutePath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        visit(absolutePath);
        continue;
      }
      if (!entry.isFile()) continue;

      const slug = pathToSlug(contentDir, absolutePath);
      if (slug === null) continue;

      const source = readFileSync(absolutePath, "utf8");
      const { frontmatter, body } = parseFrontmatter(source);
      pages.push({
        slug,
        title: frontmatter.title || titleFromMarkdown(body, titleFromSlug(slug)),
        description: frontmatter.description,
        section: frontmatter.section,
        href: createDocsHref(docs.entry, slug),
        sourcePath: absolutePath,
        lastModified: resolveFarmDocsPageLastModified(contentDir, absolutePath, frontmatter),
      });
    }
  };

  visit(contentDir);
  return pages.sort((a, b) => a.href.localeCompare(b.href));
}

export function toFarmDocsMarkdownPage(page: LoadedFarmDocsPage): DocsMarkdownPage {
  const lastModified =
    page.lastModified || page.frontmatter.lastModified || page.frontmatter.lastmod;

  return {
    slug: page.slug,
    url: page.href,
    title: page.title,
    description: page.description,
    lastModified,
    lastmod: lastModified,
    content: page.body,
    rawContent: page.body,
  };
}

function getDocsTitle(docs: FarmDocsResolvedConfig): string {
  return typeof docs.config.nav === "object" && docs.config.nav && "title" in docs.config.nav
    ? String((docs.config.nav as { title?: unknown }).title || "Documentation")
    : "Documentation";
}

function getDocsDescription(docs: FarmDocsResolvedConfig): string | undefined {
  return docs.config.metadata?.description;
}

function getLoadedDocsPages(
  contentDir: string,
  docs: FarmDocsResolvedConfig,
): LoadedFarmDocsPage[] {
  return discoverFarmDocsPages(contentDir, docs)
    .map((page) => loadFarmDocsPage(contentDir, docs, page.slug))
    .filter((page): page is LoadedFarmDocsPage => Boolean(page));
}

function toDocsLlmsPage(page: LoadedFarmDocsPage): DocsLlmsTxtPageInput {
  return toFarmDocsMarkdownPage(page);
}

function toDocsSitemapPage(page: LoadedFarmDocsPage): DocsSitemapPageInput {
  return {
    ...toFarmDocsMarkdownPage(page),
    sourcePath: page.sourcePath,
  };
}

type CopyMarkdownActionConfig = {
  format: "markdown" | "text";
  includeTitle: boolean;
  label: string;
  copiedLabel: string;
};

type LastUpdatedDisplayConfig = {
  enabled: boolean;
  label: string;
  position: "footer" | "below-title";
};

type ReadingTimeDisplayConfig = {
  wordsPerMinute: number;
  format: "long" | "short";
  includeCode: boolean;
};

function resolvePageActionsConfig(docs: FarmDocsResolvedConfig): Record<string, unknown> {
  return isObjectRecord(docs.config.pageActions) ? docs.config.pageActions : {};
}

function resolvePageActionsAlignment(docs: FarmDocsResolvedConfig): "left" | "right" {
  return resolvePageActionsConfig(docs).alignment === "right" ? "right" : "left";
}

function resolveCopyMarkdownActionConfig(
  docs: FarmDocsResolvedConfig,
): CopyMarkdownActionConfig | null {
  const raw = resolvePageActionsConfig(docs).copyMarkdown;
  if (raw === undefined || raw === false) return null;

  const options = isObjectRecord(raw) ? raw : {};
  if (isObjectRecord(raw) && raw.enabled === false) return null;

  return {
    format: options.format === "text" ? "text" : "markdown",
    includeTitle: options.includeTitle === true,
    label: readString(options.label) ?? "Copy page",
    copiedLabel: readString(options.copiedLabel) ?? "Copied!",
  };
}

function resolveLastUpdatedDisplayConfig(docs: FarmDocsResolvedConfig): LastUpdatedDisplayConfig {
  const raw = docs.config.lastUpdated;
  const options = isObjectRecord(raw) ? raw : {};

  return {
    enabled: raw !== false && (!isObjectRecord(raw) || raw.enabled !== false),
    label: typeof options.label === "string" ? options.label : "Last updated",
    position: options.position === "below-title" ? "below-title" : "footer",
  };
}

function formatLastModifiedDate(value: string | undefined): string | undefined {
  if (!value) return undefined;

  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;

  return new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date);
}

function renderLastUpdatedText(
  page: LoadedFarmDocsPage,
  docs: FarmDocsResolvedConfig,
  position: "footer" | "below-title",
): string {
  const config = resolveLastUpdatedDisplayConfig(docs);
  const formatted = formatLastModifiedDate(page.lastModified);
  if (!config.enabled || config.position !== position || !formatted) return "";

  const time = `<time datetime="${escapeAttribute(page.lastModified || "")}">${escapeHtml(formatted)}</time>`;
  const label = config.label.trim();
  return label ? `${escapeHtml(label)} ${time}` : time;
}

function resolveReadingTimeDisplayConfig(
  docs: FarmDocsResolvedConfig,
): ReadingTimeDisplayConfig | null {
  const raw = docs.config.readingTime;
  if (raw === undefined || raw === false) return null;

  const options = isObjectRecord(raw) ? raw : {};
  if (isObjectRecord(raw) && options.enabled === false) return null;

  const wordsPerMinute =
    typeof options.wordsPerMinute === "number" && options.wordsPerMinute > 0
      ? options.wordsPerMinute
      : 220;

  return {
    wordsPerMinute,
    format: options.format === "short" ? "short" : "long",
    includeCode: options.includeCode === true,
  };
}

function countMarkdownWords(body: string, includeCode: boolean): number {
  const readable = (
    includeCode ? body : body.replace(/```[\s\S]*?```/g, " ").replace(/`[^`]*`/g, " ")
  )
    .replace(/!\[[^\]]*]\([^)]*\)/g, " ")
    .replace(/\[([^\]]+)]\([^)]*\)/g, "$1")
    .replace(/<[^>]+>/g, " ")
    .replace(/[#>*_~`|:-]/g, " ");

  return readable.match(/[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)*/g)?.length ?? 0;
}

function renderReadingTimeMeta(page: LoadedFarmDocsPage, docs: FarmDocsResolvedConfig): string {
  const config = resolveReadingTimeDisplayConfig(docs);
  if (!config) return "";

  const words = countMarkdownWords(page.body, config.includeCode);
  const minutes = Math.max(1, Math.ceil(words / config.wordsPerMinute));
  const label = config.format === "short" ? `${minutes} min` : `${minutes} min read`;

  return `<div class="fd-page-meta not-prose" data-page-reading-time>
  <span class="fd-page-meta-dot" aria-hidden="true">·</span>
  <span class="fd-page-meta-item">${escapeHtml(label)}</span>
</div>`;
}

function renderPixelPageActions(page: LoadedFarmDocsPage, docs: FarmDocsResolvedConfig): string {
  const copyMarkdown = resolveCopyMarkdownActionConfig(docs);
  if (!copyMarkdown) return "";

  const markdownUrl = `${page.href}.md`;
  const includeTitle = copyMarkdown.includeTitle ? "true" : "false";

  return `<div class="fd-page-actions" data-page-actions data-actions-alignment="${resolvePageActionsAlignment(docs)}">
  <button
    type="button"
    class="fd-page-action-btn"
    data-page-action="copy-markdown"
    data-copied="false"
    data-markdown-url="${escapeAttribute(markdownUrl)}"
    data-copy-markdown-format="${copyMarkdown.format}"
    data-copy-markdown-include-title="${includeTitle}"
    data-copy-label="${escapeAttribute(copyMarkdown.label)}"
    data-copied-label="${escapeAttribute(copyMarkdown.copiedLabel)}"
    aria-label="${escapeAttribute(copyMarkdown.label)}"
    title="${escapeAttribute(copyMarkdown.label)}"
  >
    <svg class="fd-page-action-copy-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
    <svg class="fd-page-action-check-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M20 6 9 17l-5-5"></path></svg>
    <span data-page-action-label>${escapeHtml(copyMarkdown.label)}</span>
  </button>
</div>`;
}

function renderBelowTitleMeta(page: LoadedFarmDocsPage, docs: FarmDocsResolvedConfig): string {
  const lastUpdated = renderLastUpdatedText(page, docs, "below-title");
  const actions = renderPixelPageActions(page, docs);
  const readingTime = renderReadingTimeMeta(page, docs);
  if (!lastUpdated && !actions && !readingTime) return "";

  return `<div class="fd-below-title-block not-prose">
  ${lastUpdated ? `<p class="fd-last-updated-inline">${lastUpdated}</p>` : ""}
  ${actions}
  ${readingTime}
</div>`;
}

function renderMarkdownHtmlWithTitleMeta(
  page: LoadedFarmDocsPage,
  docs: FarmDocsResolvedConfig,
): string {
  const html = renderMarkdownHtml(page.body);
  const meta = renderBelowTitleMeta(page, docs);
  if (!meta) return html;

  const withTitleMeta = html.replace(/(<h1\b[\s\S]*?<\/h1>)/, `$1\n${meta}`);
  return withTitleMeta === html ? `${meta}\n${html}` : withTitleMeta;
}

function renderPixelPageFooter(page: LoadedFarmDocsPage, docs: FarmDocsResolvedConfig): string {
  const lastUpdated = renderLastUpdatedText(page, docs, "footer");
  if (!lastUpdated) return "";

  return `<div class="not-prose fd-page-footer">
  <span class="fd-last-updated-footer">${lastUpdated}</span>
</div>`;
}

function getDocsLlmsOptions(docs: FarmDocsResolvedConfig, request: Request) {
  const configured =
    typeof docs.config.llmsTxt === "object" && docs.config.llmsTxt !== null
      ? docs.config.llmsTxt
      : {};
  return {
    enabled: true,
    baseUrl: new URL(request.url).origin,
    siteTitle: getDocsTitle(docs),
    siteDescription: getDocsDescription(docs),
    ...configured,
  };
}

function getDocsDiscoveryOptions(docs: FarmDocsResolvedConfig, request: Request) {
  return {
    origin: new URL(request.url).origin,
    entry: docs.entry,
    i18n: null,
    search: docs.config.search ?? true,
    mcp: {
      enabled: false,
      route: "/api/docs/mcp",
      name: `${getDocsTitle(docs)} MCP`,
      version: "1",
      tools: {
        listDocs: false,
        listPages: false,
        readPage: false,
        searchDocs: false,
        getNavigation: false,
        getCodeExamples: false,
        getConfigSchema: false,
      },
    },
    feedback: undefined,
    llms: getDocsLlmsOptions(docs, request),
    sitemap: docs.config.sitemap ?? true,
    robots: docs.config.robots ?? true,
    openapi: undefined,
    markdown: {
      acceptHeader: true,
      signatureAgentHeader: true,
    },
  };
}

function createFarmDocsPublicResponse(
  contentDir: string,
  docs: FarmDocsResolvedConfig,
  request: Request,
): Response | null {
  const url = new URL(request.url);
  const loadedPages = getLoadedDocsPages(contentDir, docs);
  const sitemapManifest = () =>
    buildDocsSitemapManifest({
      pages: loadedPages.map(toDocsSitemapPage),
      entry: docs.entry,
      siteTitle: getDocsTitle(docs),
      baseUrl: url.origin,
    });
  const textHeaders = (contentType: string) => ({
    "Content-Type": contentType,
    "Cache-Control": "public, max-age=60",
  });

  const llmsFormat = resolveDocsLlmsTxtFormat(url);
  if (llmsFormat) {
    const generated = renderDocsLlmsTxt(
      loadedPages.map(toDocsLlmsPage),
      getDocsLlmsOptions(docs, request),
    );
    return new Response(llmsFormat === "llms-full" ? generated.llmsFullTxt : generated.llmsTxt, {
      status: 200,
      headers: textHeaders("text/plain; charset=utf-8"),
    });
  }

  const sitemapFormat = resolveDocsSitemapRequest(url, docs.config.sitemap ?? true);
  if (sitemapFormat === "xml") {
    return new Response(
      renderDocsSitemapXml(sitemapManifest(), {
        baseUrl: url.origin,
        includeLastmod: true,
      }),
      {
        status: 200,
        headers: textHeaders("application/xml; charset=utf-8"),
      },
    );
  }
  if (sitemapFormat === "markdown") {
    return new Response(
      renderDocsSitemapMarkdown(sitemapManifest(), {
        includeDescriptions: true,
      }),
      {
        status: 200,
        headers: textHeaders("text/markdown; charset=utf-8"),
      },
    );
  }

  if (resolveDocsRobotsRequest(url, docs.config.robots ?? true)) {
    return new Response(
      renderDocsRobotsTxt({
        entry: docs.entry,
        sitemap: docs.config.sitemap ?? true,
        robots: docs.config.robots ?? true,
        baseUrl: url.origin,
      }),
      {
        status: 200,
        headers: textHeaders("text/plain; charset=utf-8"),
      },
    );
  }

  if (isDocsAgentDiscoveryRequest(url)) {
    const spec = buildDocsAgentDiscoverySpec(getDocsDiscoveryOptions(docs, request));
    const title = getDocsTitle(docs);
    return new Response(
      JSON.stringify({
        ...spec,
        name: title,
        site: {
          ...spec.site,
          title,
          description: getDocsDescription(docs),
          entry: docs.entry,
        },
      }),
      {
        status: 200,
        headers: textHeaders("application/json; charset=utf-8"),
      },
    );
  }

  if (isDocsAgentsRequest(url)) {
    return new Response(
      `${renderDocsAgentsDocument(getDocsDiscoveryOptions(docs, request)).trim()}\n`,
      {
        status: 200,
        headers: textHeaders("text/markdown; charset=utf-8"),
      },
    );
  }

  if (isDocsSkillRequest(url)) {
    return new Response(
      `${renderDocsSkillDocument(getDocsDiscoveryOptions(docs, request)).trim()}\n`,
      {
        status: 200,
        headers: textHeaders("text/markdown; charset=utf-8"),
      },
    );
  }

  return null;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function shouldReturnMarkdown(request: Request): boolean {
  const url = new URL(request.url);
  return (
    url.pathname.endsWith(".md") ||
    request.headers.get("accept")?.includes("text/markdown") === true ||
    request.headers.get("accept")?.includes("text/plain") === true
  );
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replace(/'/g, "&#39;");
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/<[^>]+>/g, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function createSlugger() {
  const seen = new Map<string, number>();

  return (value: string) => {
    const base = slugify(value) || "section";
    const count = seen.get(base) || 0;
    seen.set(base, count + 1);
    return count === 0 ? base : `${base}-${count + 1}`;
  };
}

function stripHtml(value: string): string {
  return value.replace(/<[^>]+>/g, "");
}

function getCodeFence(line: string): { marker: "`" | "~"; length: number } | null {
  const match = /^(?: {0,3})(`{3,}|~{3,})/.exec(line);
  const value = match?.[1];
  if (!value) return null;
  return { marker: value[0] as "`" | "~", length: value.length };
}

function isClosingCodeFence(line: string, fence: { marker: "`" | "~"; length: number }): boolean {
  const trimmed = line.trim();
  return (
    trimmed.length >= fence.length && Array.from(trimmed).every((char) => char === fence.marker)
  );
}

function stripMdxRuntimeSyntax(body: string): string {
  const output: string[] = [];
  let fence: { marker: "`" | "~"; length: number } | null = null;

  for (const line of body.split("\n")) {
    const nextFence = getCodeFence(line);
    if (fence) {
      output.push(line);
      if (nextFence && nextFence.marker === fence.marker && isClosingCodeFence(line, fence)) {
        fence = null;
      }
      continue;
    }

    if (nextFence) {
      fence = nextFence;
      output.push(line);
      continue;
    }

    if (/^\s*import\s.+$/.test(line) || /^\s*export\s+(const|default)\s.+$/.test(line)) {
      continue;
    }

    output.push(line);
  }

  return output.join("\n");
}

function unescapeHtml(value: string): string {
  return value
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

const CODE_LANGUAGE_LABELS = new Set([
  "bash",
  "cjs",
  "cmd",
  "console",
  "css",
  "html",
  "javascript",
  "js",
  "json",
  "jsx",
  "md",
  "mdx",
  "shell",
  "sh",
  "terminal",
  "text",
  "ts",
  "tsx",
  "txt",
  "typescript",
  "yaml",
  "yml",
  "zsh",
]);

const EXTENSIONLESS_CODE_FILENAMES = new Set([
  "dockerfile",
  "makefile",
  "procfile",
  "readme",
  "license",
]);

function isCodePathLabel(label: string): boolean {
  const trimmed = label.trim();
  if (!trimmed || /\s/.test(trimmed)) return false;

  const lower = trimmed.toLowerCase();
  if (CODE_LANGUAGE_LABELS.has(lower)) return false;

  const fileName = trimmed.split(/[\\/]/).filter(Boolean).pop() || trimmed;
  const lowerFileName = fileName.toLowerCase();
  if (EXTENSIONLESS_CODE_FILENAMES.has(lowerFileName)) return true;
  if (fileName.startsWith(".") && fileName.length > 1) return true;

  return /\.[a-z0-9][a-z0-9-]*$/i.test(fileName);
}

function parseCodeInfo(info: string | undefined): {
  language: string;
  label: string;
  hasExplicitLabel: boolean;
} {
  const source = (info || "").trim();
  const language = source.match(/^\S+/)?.[0] || "text";
  const explicitLabel = source
    .match(/\b(?:title|filename|file|label|name)=["']([^"']+)["']/)?.[1]
    ?.trim();
  return { language, label: explicitLabel || language, hasExplicitLabel: Boolean(explicitLabel) };
}

function getStandaloneCodeLabel(line: string): string | null {
  const trimmed = line.trim();
  const match = /^(?:\*\*([^*]+)\*\*|__([^_]+)__|`([^`]+)`)$/u.exec(trimmed);
  const label = match?.[1] || match?.[2] || match?.[3];
  return label?.trim() || null;
}

function hasCodeFenceTitle(info: string): boolean {
  return /\b(?:title|filename|file|label|name)=["'][^"']+["']/.test(info);
}

function escapeCodeFenceTitle(value: string): string {
  return value.replace(/"/g, "&quot;");
}

function addTitleToCodeFence(line: string, title: string): string {
  const match = /^(\s{0,3})(`{3,}|~{3,})(.*)$/u.exec(line);
  if (!match) return line;
  const [, indent, marker, infoSource] = match;
  const info = infoSource.trim();
  if (hasCodeFenceTitle(info)) return line;
  const suffix = `title="${escapeCodeFenceTitle(title)}"`;
  return `${indent}${marker}${info ? `${info} ${suffix}` : `text ${suffix}`}`;
}

function attachCodeBlockLabels(body: string): string {
  const lines = body.split("\n");
  const output: string[] = [];
  let fence: { marker: "`" | "~"; length: number } | null = null;

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index] || "";
    const nextFence = getCodeFence(line);

    if (fence) {
      output.push(line);
      if (nextFence && nextFence.marker === fence.marker && isClosingCodeFence(line, fence)) {
        fence = null;
      }
      continue;
    }

    if (nextFence) {
      fence = nextFence;
      output.push(line);
      continue;
    }

    const label = getStandaloneCodeLabel(line);
    if (!label) {
      output.push(line);
      continue;
    }

    let fenceIndex = index + 1;
    while (fenceIndex < lines.length && (lines[fenceIndex] || "").trim() === "") {
      fenceIndex += 1;
    }

    const labeledFence = getCodeFence(lines[fenceIndex] || "");
    if (!labeledFence) {
      output.push(line);
      continue;
    }

    output.push(addTitleToCodeFence(lines[fenceIndex] || "", label));
    fence = labeledFence;
    index = fenceIndex;
  }

  return output.join("\n");
}

function highlightCodeBlock(code: string): string {
  return highlight(code.replace(/\n$/, "")).replace(/<\/span>\n<span/g, "</span><span");
}

function renderCodeCopyButton(className = "code-copy"): string {
  return `<button class="${className}" type="button" data-copied="false" aria-label="Copy code" title="Copy code" onclick="navigator.clipboard?.writeText(this.closest('figure').querySelector('code').innerText); this.dataset.copied='true'; this.setAttribute('aria-label','Copied'); this.title='Copied'; clearTimeout(this._copyTimer); this._copyTimer=setTimeout(() => { this.dataset.copied='false'; this.setAttribute('aria-label','Copy code'); this.title='Copy code'; }, 4500);"><svg class="code-copy-icon" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg><svg class="code-copy-check" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M20 6 9 17l-5-5"></path></svg></button>`;
}

function renderMarkdownHtml(body: string): string {
  const slug = createSlugger();
  const renderer = new Renderer();

  renderer.heading = (text, level, raw) => {
    const id = slug(raw || stripHtml(text));
    return `<h${level} id="${escapeAttribute(id)}"><a class="heading-anchor" href="#${escapeAttribute(id)}">${text}</a></h${level}>\n`;
  };

  renderer.code = (code, infostring, escaped) => {
    const { language, label, hasExplicitLabel } = parseCodeInfo(infostring);
    const rawCode = escaped ? unescapeHtml(code) : code;
    const highlighted = highlightCodeBlock(rawCode);
    const shouldRenderHeader = hasExplicitLabel && isCodePathLabel(label);
    const header = shouldRenderHeader
      ? `<div class="code-block-header">
    <span class="code-block-title">${escapeHtml(label)}</span>
    ${renderCodeCopyButton()}
  </div>`
      : renderCodeCopyButton("code-copy code-copy-floating");

    return `<figure class="shiki code-block ${shouldRenderHeader ? "code-block-framed" : "code-block-plain"}" data-language="${escapeAttribute(language)}">
  ${header}
  <pre><code class="sh-code language-${escapeAttribute(language)}">${highlighted}</code></pre>
</figure>\n`;
  };

  renderer.table = (header, body) =>
    `<div class="fd-table-wrapper table-wrap relative overflow-auto prose-no-margin my-6"><table><thead>${header}</thead><tbody>${body}</tbody></table></div>\n`;

  renderer.blockquote = (quote) => `<blockquote>${quote}</blockquote>\n`;
  renderer.codespan = (code) => `<code>${escapeHtml(code)}</code>`;

  renderer.link = (href, title, text) => {
    const safeHref = href || "";
    const titleAttribute = title ? ` title="${escapeAttribute(title)}"` : "";
    return `<a href="${escapeAttribute(safeHref)}"${titleAttribute}>${text}</a>`;
  };

  renderer.image = (href, title, text) => {
    const titleAttribute = title ? ` title="${escapeAttribute(title)}"` : "";
    return `<img src="${escapeAttribute(href)}" alt="${escapeAttribute(text)}"${titleAttribute}>`;
  };

  const html = marked(attachCodeBlockLabels(stripMdxRuntimeSyntax(body)), {
    async: false,
    breaks: false,
    gfm: true,
    renderer,
  }) as string;

  return html.trim();
}

interface TocItem {
  id: string;
  title: string;
  level: number;
}

function extractTocItems(body: string, depth: number): TocItem[] {
  const slug = createSlugger();
  const maxLevel = Math.max(2, Math.min(depth, 6));

  return body
    .split(/\r?\n/)
    .map((line) => line.match(/^(#{2,6})\s+(.+)$/))
    .filter((match): match is RegExpMatchArray => Boolean(match))
    .map((match) => ({
      id: slug(match[2].trim()),
      title: match[2].trim(),
      level: match[1].length,
    }))
    .filter((item) => item.level <= maxLevel);
}

function getThemeUI(docs: FarmDocsResolvedConfig): Record<string, any> {
  const theme = docs.config.theme;
  return theme && typeof theme === "object" && "ui" in theme && typeof theme.ui === "object"
    ? (theme.ui as Record<string, any>)
    : {};
}

function getThemeName(docs: FarmDocsResolvedConfig): string {
  const theme = docs.config.theme;
  return theme && typeof theme === "object" && "name" in theme
    ? String((theme as { name?: unknown }).name || "farm-docs")
    : "farm-docs";
}

function getThemeTocDepth(docs: FarmDocsResolvedConfig): number {
  const toc = getThemeUI(docs).layout?.toc;
  return toc && typeof toc === "object" && typeof toc.depth === "number" ? toc.depth : 3;
}

const SIDEBAR_SECTION_ORDER = [
  "Start",
  "Core",
  "Data and APIs",
  "Integrations",
  "Runtime",
  "Content",
  "Extending",
  "Reference",
];

const SIDEBAR_PAGE_ORDER = new Map(
  [
    "",
    "getting-started",
    "project-structure",
    "configuration",
    "routing",
    "layouts",
    "server-rendering",
    "middleware",
    "query",
    "api-routes",
    "api-client",
    "storage",
    "integrations",
    "integrations/stripe",
    "integrations/autumn",
    "integrations/polar",
    "integrations/auth",
    "integrations/email",
    "integrations/jobs",
    "integrations/unkey",
    "integrations/ui-registry",
    "integrations/orm-storage",
    "cache-ppr",
    "observability",
    "deployment",
    "docs-engine",
    "markdown",
    "openapi",
    "plugins",
    "plugins/create-plugin",
    "cli",
    "examples",
    "reference",
  ].map((slug, index) => [slug, index]),
);

type SidebarNavigationItem = {
  label?: string;
  icon?: string;
  slug?: string;
  href?: string;
  children: SidebarNavigationItem[];
};

function isSidebarNavigationItem(
  value: SidebarNavigationItem | null,
): value is SidebarNavigationItem {
  return value !== null;
}

function compareSidebarPages(a: FarmDocsPage, b: FarmDocsPage): number {
  const aOrder = SIDEBAR_PAGE_ORDER.get(a.slug) ?? 1000;
  const bOrder = SIDEBAR_PAGE_ORDER.get(b.slug) ?? 1000;
  return aOrder - bOrder || a.title.localeCompare(b.title);
}

function getSidebarSection(page: FarmDocsPage): string {
  if (page.section) return page.section;
  if (page.slug.startsWith("integrations/")) return "Integrations";
  if (page.slug.startsWith("plugins/")) return "Extending";
  return "Reference";
}

function sidebarIdFor(section: string): string {
  return `sidebar-${slugify(section)}`;
}

function isObjectRecord(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function readString(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
}

function readOptionalString(value: unknown): string | undefined {
  return typeof value === "string" ? value.trim() : undefined;
}

function normalizeSidebarSlug(value: string): string {
  if (value === "/" || value === ".") return "";
  return trimSlashes(value);
}

function getSidebarNavigation(docs: FarmDocsResolvedConfig): SidebarNavigationItem[] {
  const navigation = docs.config.navigation;
  if (!isObjectRecord(navigation) || !Array.isArray(navigation.sidebar)) return [];
  return navigation.sidebar.map(normalizeSidebarNavigationItem).filter(isSidebarNavigationItem);
}

function normalizeSidebarNavigationItem(value: unknown): SidebarNavigationItem | null {
  if (!isObjectRecord(value)) return null;

  const label = readString(value.label) ?? readString(value.title);
  const icon = readString(value.icon);
  const slug = readOptionalString(value.slug) ?? readOptionalString(value.path);
  const href = readString(value.href) ?? readString(value.url);
  const rawChildren = Array.isArray(value.children)
    ? value.children
    : Array.isArray(value.items)
      ? value.items
      : [];
  const children = rawChildren.map(normalizeSidebarNavigationItem).filter(isSidebarNavigationItem);

  if (!label && !slug && !href && children.length === 0) return null;
  return {
    ...(label ? { label } : {}),
    ...(icon ? { icon } : {}),
    ...(slug !== undefined ? { slug: normalizeSidebarSlug(slug) } : {}),
    ...(href ? { href } : {}),
    children,
  };
}

function createSidebarPageMaps(pages: FarmDocsPage[]) {
  return {
    bySlug: new Map(pages.map((page) => [page.slug, page])),
    byHref: new Map(pages.map((page) => [page.href, page])),
  };
}

function resolveConfiguredSidebarPage(
  item: SidebarNavigationItem,
  maps: ReturnType<typeof createSidebarPageMaps>,
): FarmDocsPage | undefined {
  if (item.slug !== undefined) return maps.bySlug.get(item.slug);
  if (item.href) return maps.byHref.get(item.href);
  return undefined;
}

function getSidebarIconRegistry(docs: FarmDocsResolvedConfig): Record<string, unknown> {
  return isObjectRecord(docs.config.icons) ? docs.config.icons : {};
}

function renderConfiguredIconSvg(value: unknown): string {
  if (typeof value !== "string") return "";
  const icon = value.trim();
  if (!icon) return "";
  if (/^<svg[\s>]/i.test(icon)) return icon;
  if (/^<(path|circle|rect|line|polyline|polygon|ellipse|g)\b/i.test(icon)) {
    return `<svg viewBox="0 0 24 24" focusable="false">${icon}</svg>`;
  }
  return "";
}

function renderSidebarIcon(
  docs: FarmDocsResolvedConfig,
  icon: string | undefined,
  className = "sidebar-icon fd-sidebar-icon",
): string {
  if (!icon) return "";
  const iconRegistry = getSidebarIconRegistry(docs);
  const configuredIcon = iconRegistry[icon] ?? icon;
  const svg = renderConfiguredIconSvg(configuredIcon);
  if (!svg) return "";
  return `<span class="${className}" data-sidebar-icon="${escapeAttribute(icon)}" aria-hidden="true">${svg}</span>`;
}

function renderSidebarLabel(
  docs: FarmDocsResolvedConfig,
  icon: string | undefined,
  label: string,
  className: string,
): string {
  return `<span class="${className}">${renderSidebarIcon(docs, icon)}<span class="sidebar-label-text">${escapeHtml(label)}</span></span>`;
}

function getSidebarPageLabel(item: FarmDocsPage, configured?: SidebarNavigationItem): string {
  if (configured?.label) return configured.label;
  if (item.slug === "") return "Why?";
  if (item.slug === "integrations") return "Overview";
  if (item.slug === "integrations/ui-registry") return "UI Registry";
  if (item.slug === "integrations/orm-storage") return "ORM Storage";
  if (item.slug.startsWith("integrations/")) {
    return item.title.replace(/\s+Integrations?$/i, "");
  }
  return item.title;
}

function renderSidebarLink(
  item: FarmDocsPage,
  activeHref: string,
  docs: FarmDocsResolvedConfig,
  configured?: SidebarNavigationItem,
): string {
  const active = item.href === activeHref;
  return `<a class="fd-sidebar-link${active ? " fd-sidebar-link-active" : ""}" data-active="${active ? "true" : "false"}" href="${escapeAttribute(item.href)}">${renderSidebarLabel(docs, configured?.icon, getSidebarPageLabel(item, configured), "sidebar-link-label fd-sidebar-link-label")}</a>`;
}

function collectConfiguredSidebarPages(
  items: SidebarNavigationItem[],
  maps: ReturnType<typeof createSidebarPageMaps>,
  seen = new Set<string>(),
): FarmDocsPage[] {
  const ordered: FarmDocsPage[] = [];
  for (const item of items) {
    const page = resolveConfiguredSidebarPage(item, maps);
    if (page && !seen.has(page.slug)) {
      seen.add(page.slug);
      ordered.push(page);
    }
    ordered.push(...collectConfiguredSidebarPages(item.children, maps, seen));
  }
  return ordered;
}

function getOrderedSidebarPages(
  pages: FarmDocsPage[],
  docs?: FarmDocsResolvedConfig,
): FarmDocsPage[] {
  if (!docs) return [...pages].sort(compareSidebarPages);

  const maps = createSidebarPageMaps(pages);
  const configuredPages = collectConfiguredSidebarPages(getSidebarNavigation(docs), maps);
  if (configuredPages.length === 0) return [...pages].sort(compareSidebarPages);

  const configuredSlugs = new Set(configuredPages.map((page) => page.slug));
  const remainingPages = pages
    .filter((page) => !configuredSlugs.has(page.slug))
    .sort(compareSidebarPages);
  return [...configuredPages, ...remainingPages];
}

function renderExternalSidebarLink(
  item: SidebarNavigationItem,
  activeHref: string,
  docs: FarmDocsResolvedConfig,
): string {
  if (!item.href || !item.label) return "";
  const active = item.href === activeHref;
  return `<a class="fd-sidebar-link${active ? " fd-sidebar-link-active" : ""}" data-active="${active ? "true" : "false"}" href="${escapeAttribute(item.href)}">${renderSidebarLabel(docs, item.icon, item.label, "sidebar-link-label fd-sidebar-link-label")}</a>`;
}

function renderConfiguredSidebarSubgroup(
  item: SidebarNavigationItem,
  childHtml: string,
  docs: FarmDocsResolvedConfig,
): string {
  const label = item.label;
  if (!label) return childHtml;
  return `<div class="sidebar-subgroup fd-sidebar-folder" data-sidebar-subgroup="${escapeAttribute(slugify(label))}">
  <div class="sidebar-subgroup-title fd-sidebar-folder-trigger">${renderSidebarLabel(docs, item.icon, label, "sidebar-subgroup-label")}</div>
  <div class="sidebar-subgroup-content fd-sidebar-folder-content">
${childHtml}
  </div>
</div>`;
}

function renderConfiguredSidebarItems(
  items: SidebarNavigationItem[],
  maps: ReturnType<typeof createSidebarPageMaps>,
  activeHref: string,
  docs: FarmDocsResolvedConfig,
): string {
  const renderedItems: string[] = [];
  for (const item of items) {
    const page = resolveConfiguredSidebarPage(item, maps);
    const childHtml = renderConfiguredSidebarItems(item.children, maps, activeHref, docs);

    if (item.children.length > 0) {
      renderedItems.push(renderConfiguredSidebarSubgroup(item, childHtml, docs));
      continue;
    }

    const linkHtml = page
      ? renderSidebarLink(page, activeHref, docs, item)
      : renderExternalSidebarLink(item, activeHref, docs);
    if (linkHtml) renderedItems.push(linkHtml);
  }
  return renderedItems.join("\n");
}

function renderConfiguredSidebarSection(
  section: SidebarNavigationItem,
  maps: ReturnType<typeof createSidebarPageMaps>,
  activeHref: string,
  docs: FarmDocsResolvedConfig,
): string {
  const label = section.label || "Docs";
  const id = sidebarIdFor(label);
  const links = renderConfiguredSidebarItems(section.children, maps, activeHref, docs);
  return `<div class="sidebar-folder fd-sidebar-folder" data-state="open">
  <button class="text-fd-muted-foreground sidebar-folder-trigger fd-sidebar-folder-trigger" type="button" aria-controls="${escapeAttribute(id)}" aria-expanded="true">${renderSidebarLabel(docs, section.icon, label, "sidebar-folder-label")}</button>
  <div id="${escapeAttribute(id)}" class="overflow-hidden sidebar-folder-content fd-sidebar-folder-content" data-state="open">
${links}
  </div>
</div>`;
}

function renderAutoSidebarSectionItems(
  items: FarmDocsPage[],
  activeHref: string,
  docs: FarmDocsResolvedConfig,
): string {
  return [...items]
    .sort(compareSidebarPages)
    .map((item) => renderSidebarLink(item, activeHref, docs))
    .join("\n");
}

function renderPixelNavItems(
  pages: FarmDocsPage[],
  activeHref: string,
  docs: FarmDocsResolvedConfig,
): string {
  const configuredSidebar = getSidebarNavigation(docs);
  if (configuredSidebar.length > 0) {
    const maps = createSidebarPageMaps(pages);
    const renderedSections = configuredSidebar
      .map((section) => {
        if (section.children.length > 0) {
          return renderConfiguredSidebarSection(section, maps, activeHref, docs);
        }
        const page = resolveConfiguredSidebarPage(section, maps);
        return page
          ? renderSidebarLink(page, activeHref, docs, section)
          : renderExternalSidebarLink(section, activeHref, docs);
      })
      .filter(Boolean)
      .join("\n");

    return `<div class="sidebar-scroll overscroll-contain fd-sidebar-nav">
  <div class="sidebar-tree">
${renderedSections}
  </div>
</div>`;
  }

  const groups = new Map<string, FarmDocsPage[]>();
  for (const item of pages) {
    const group = item.slug === "" ? "Start" : getSidebarSection(item);
    const entries = groups.get(group) ?? [];
    entries.push(item);
    groups.set(group, entries);
  }

  const renderedSections = Array.from(groups.entries())
    .sort(([a], [b]) => {
      const aOrder = SIDEBAR_SECTION_ORDER.indexOf(a);
      const bOrder = SIDEBAR_SECTION_ORDER.indexOf(b);
      return (aOrder === -1 ? 100 : aOrder) - (bOrder === -1 ? 100 : bOrder) || a.localeCompare(b);
    })
    .map(([section, items]) => {
      const id = sidebarIdFor(section);
      const links = renderAutoSidebarSectionItems(items, activeHref, docs);
      return `<div class="sidebar-folder fd-sidebar-folder" data-state="open">
  <button class="text-fd-muted-foreground sidebar-folder-trigger fd-sidebar-folder-trigger" type="button" aria-controls="${escapeAttribute(id)}" aria-expanded="true">${renderSidebarLabel(docs, undefined, section, "sidebar-folder-label")}</button>
  <div id="${escapeAttribute(id)}" class="overflow-hidden sidebar-folder-content fd-sidebar-folder-content" data-state="open">
${links}
  </div>
</div>`;
    })
    .join("\n");

  return `<div class="sidebar-scroll overscroll-contain fd-sidebar-nav">
  <div class="sidebar-tree">
${renderedSections}
  </div>
</div>`;
}

function renderPixelPageNav(
  pages: FarmDocsPage[],
  activeHref: string,
  docs: FarmDocsResolvedConfig,
): string {
  const orderedPages = getOrderedSidebarPages(pages, docs);
  const activeIndex = orderedPages.findIndex((item) => item.href === activeHref);
  if (activeIndex === -1) return "";

  const previous = orderedPages[activeIndex - 1];
  const next = orderedPages[activeIndex + 1];
  if (!previous && !next) return "";

  const renderChevron = (direction: "prev" | "next") =>
    `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="${direction === "prev" ? "15 18 9 12 15 6" : "9 18 15 12 9 6"}" /></svg>`;
  const renderCard = (item: FarmDocsPage, direction: "prev" | "next") =>
    `<a class="fd-page-nav-card fd-page-nav-${direction}" href="${escapeAttribute(item.href)}">
  <span class="fd-page-nav-title fd-page-nav-title-${direction}">${direction === "prev" ? `${renderChevron(direction)}${escapeHtml(item.title)}` : `${escapeHtml(item.title)}${renderChevron(direction)}`}</span>
  <span class="fd-page-nav-description">${direction === "prev" ? "Previous Page" : "Next Page"}</span>
</a>`;

  return `<nav class="not-prose fd-page-nav" aria-label="Page navigation">
  ${previous ? renderCard(previous, "prev") : ""}
  ${next ? renderCard(next, "next") : ""}
</nav>`;
}

function titleizePathSegment(value: string): string {
  return value.replace(/[-_]+/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
}

function isBreadcrumbEnabled(docs: FarmDocsResolvedConfig): boolean {
  const breadcrumb = docs.config.breadcrumb;
  if (breadcrumb === false) return false;
  if (breadcrumb && typeof breadcrumb === "object" && "enabled" in breadcrumb) {
    return (breadcrumb as { enabled?: unknown }).enabled !== false;
  }
  return true;
}

function renderPixelBreadcrumb(page: LoadedFarmDocsPage, docs: FarmDocsResolvedConfig): string {
  if (!isBreadcrumbEnabled(docs)) return "";

  const segments = trimSlashes(page.slug).split("/").filter(Boolean);
  if (segments.length < 2) return "";

  const parentSegments = segments.slice(0, -1);
  const parentSegment = parentSegments[parentSegments.length - 1];
  const currentSegment = segments[segments.length - 1];
  const entry = normalizeEntry(docs.entry);
  const parentPath = parentSegments.join("/");
  const parentHref = entry === "/" ? `/${parentPath}` : `${entry}/${parentPath}`;

  return `<nav class="fd-breadcrumb" aria-label="Breadcrumb">
  <span class="fd-breadcrumb-item">
    <a class="fd-breadcrumb-parent fd-breadcrumb-link" href="${escapeAttribute(parentHref)}">${escapeHtml(titleizePathSegment(parentSegment))}</a>
  </span>
  <span class="fd-breadcrumb-item">
    <span class="fd-breadcrumb-sep">/</span>
    <span class="fd-breadcrumb-current">${escapeHtml(titleizePathSegment(currentSegment))}</span>
  </span>
</nav>`;
}

function renderDocsSearchTrigger(showIcon = true, className = ""): string {
  return `<button class="fd-docs-search-trigger ${className}" type="button" data-search-full="" aria-label="Search documentation" aria-haspopup="dialog" aria-keyshortcuts="Meta+K Control+K">
  ${showIcon ? '<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-4-4"></path></svg>' : ""}
  <kbd><span>⌘</span><span>K</span></kbd>
</button>`;
}

function renderDocsSearchMount(clientEntry: string): string {
  return `<div id="farm-docs-search-root" data-farm-docs-search-root data-api="/api/docs"></div>
  <script type="module" src="${escapeAttribute(clientEntry)}"></script>`;
}

function renderDocsSearchBootstrapScript(): string {
  return `<script>${generateFarmDocsSearchBootstrapRuntime()}</script>`;
}

function renderPixelToc(items: TocItem[]): string {
  if (items.length === 0) return '<p class="toc-empty">No sections</p>';
  return `<div class="toc-track fd-toc-list">
  <div class="toc-thumb" data-toc-thumb style="clip-path: polygon(0 0px, 100% 0px, 100% 32px, 0 32px);"></div>
  <div class="toc-links">
${items
  .map(
    (item) =>
      `<a class="toc-link fd-toc-link${items[0] === item ? " fd-toc-link-active" : ""}" data-active="${items[0] === item ? "true" : "false"}" data-toc-item data-depth="${item.level}" href="#${escapeAttribute(item.id)}">${escapeHtml(item.title)}</a>`,
  )
  .join("\n")}
  </div>
</div>`;
}

function renderDocsRuntimeScript(docs: FarmDocsResolvedConfig): string {
  const docsEntry = JSON.stringify(normalizeEntry(docs.entry));
  return `<script>(()=>{if(window.__farmDocsRuntime)return;window.__farmDocsRuntime=true;document.documentElement.dataset.farmDocsRuntime="true";document.documentElement.dataset.farmDocsRuntimeId=Math.random().toString(36).slice(2);const docsEntry=${docsEntry};let cleanupToc=()=>{};let closeMobileSidebar=()=>{};const normalizePath=(path)=>path.length>1?path.replace(/\\/+$/,""):path;const isDocsPath=(path)=>{const next=normalizePath(path);const entry=normalizePath(docsEntry);if(next.endsWith(".md"))return false;if(entry==="/")return true;return next===entry||next.startsWith(entry+"/")};const initToc=()=>{cleanupToc();const toc=document.getElementById("nd-toc");if(!toc){cleanupToc=()=>{};return}const links=Array.from(toc.querySelectorAll("[data-toc-item]"));const thumb=toc.querySelector("[data-toc-thumb]");const pairs=links.map((link)=>{let id=link.hash.slice(1);try{id=decodeURIComponent(id)}catch{}return{link,heading:document.getElementById(id)}}).filter((item)=>item.heading);const setActive=(active)=>{for(const {link} of pairs){const selected=link===active.link;link.dataset.active=selected?"true":"false";link.classList.toggle("fd-toc-link-active",selected)}if(!thumb)return;const styles=getComputedStyle(active.link);const top=active.link.offsetTop+parseFloat(styles.paddingTop||"0");const bottom=active.link.offsetTop+active.link.clientHeight-parseFloat(styles.paddingBottom||"0");thumb.style.clipPath="polygon(0 "+top+"px,100% "+top+"px,100% "+bottom+"px,0 "+bottom+"px)"};const update=()=>{if(pairs.length===0)return;const offset=Math.min(window.innerHeight*0.3,160);let active=pairs[0];for(const pair of pairs){if(pair.heading.getBoundingClientRect().top<=offset)active=pair;else break}setActive(active)};let frame=0;const schedule=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;update()})};const onHashChange=()=>setTimeout(schedule,0);window.addEventListener("scroll",schedule,{passive:true});window.addEventListener("resize",schedule);window.addEventListener("hashchange",onHashChange);cleanupToc=()=>{window.removeEventListener("scroll",schedule);window.removeEventListener("resize",schedule);window.removeEventListener("hashchange",onHashChange);if(frame)cancelAnimationFrame(frame);frame=0};update()};const getSidebar=()=>document.getElementById("nd-sidebar");const ensureActiveVisible=()=>{const sidebar=getSidebar();if(!sidebar)return;const active=sidebar.querySelector('a[data-active="true"]');if(!(active instanceof HTMLElement))return;const activeRect=active.getBoundingClientRect();const sidebarRect=sidebar.getBoundingClientRect();if(activeRect.top<sidebarRect.top||activeRect.bottom>sidebarRect.bottom)sidebar.scrollTop+=activeRect.top-sidebarRect.top-(sidebar.clientHeight-activeRect.height)/2};const setSidebarActive=(path)=>{const sidebar=getSidebar();if(!sidebar)return;const current=normalizePath(path);for(const link of Array.from(sidebar.querySelectorAll("a[href]"))){try{link.dataset.active=normalizePath(new URL(link.href,location.href).pathname)===current?"true":"false"}catch{}}ensureActiveVisible()};const initMobileSidebar=()=>{const layout=document.getElementById("nd-docs-layout");const sidebar=getSidebar();const toggle=document.querySelector("[data-sidebar-toggle]");const backdrop=document.querySelector("[data-sidebar-backdrop]");if(!layout||!sidebar||!(toggle instanceof HTMLButtonElement))return;const setOpen=(open)=>{layout.dataset.sidebarOpen=open?"true":"false";sidebar.classList.toggle("fd-sidebar-open",open);document.documentElement.dataset.farmDocsSidebar=open?"open":"closed";toggle.setAttribute("aria-expanded",open?"true":"false");toggle.setAttribute("aria-label",open?"Close menu":"Open menu")};const toggleOpen=()=>setOpen(layout.dataset.sidebarOpen!=="true");closeMobileSidebar=()=>setOpen(false);toggle.addEventListener("click",(event)=>{event.preventDefault();toggleOpen()});backdrop?.addEventListener("click",()=>closeMobileSidebar());document.addEventListener("keydown",(event)=>{if(event.key==="Escape")closeMobileSidebar()});sidebar.addEventListener("click",(event)=>{const target=event.target instanceof Element?event.target.closest("a[href]"):null;if(target)closeMobileSidebar()});closeMobileSidebar()};const initSidebarScroll=()=>{const sidebar=getSidebar();if(!sidebar)return;const key="farmdocs:sidebar-scroll:"+location.origin;const getStorage=()=>{try{return window.sessionStorage}catch{return null}};const readSaved=()=>{try{const raw=getStorage()?.getItem(key);if(!raw)return null;const parsed=JSON.parse(raw);return parsed&&typeof parsed==="object"?parsed:null}catch{return null}};const save=(path=location.pathname)=>{try{getStorage()?.setItem(key,JSON.stringify({path,scrollTop:sidebar.scrollTop}))}catch{}};const saved=readSaved();if(saved?.path===location.pathname&&Number.isFinite(Number(saved.scrollTop)))sidebar.scrollTop=Number(saved.scrollTop);ensureActiveVisible();save();sidebar.addEventListener("scroll",()=>save(),{passive:true});sidebar.addEventListener("click",(event)=>{const target=event.target instanceof Element?event.target.closest("a[href]"):null;if(!target)return;try{save(new URL(target.href,location.href).pathname)}catch{save()}});window.addEventListener("beforeunload",()=>save())};let navigateController=null;const getPageKey=(root)=>{const article=root.getElementById("nd-page");if(!article)return"";return article.querySelector("h1")?.textContent?.trim()||article.textContent?.replace(/\\s+/g," ").trim().slice(0,160)||""};const swapDocsPage=(html,url)=>{const nextDoc=new DOMParser().parseFromString(html,"text/html");const nextArticle=nextDoc.getElementById("nd-page");const currentArticle=document.getElementById("nd-page");if(!nextArticle||!currentArticle)return false;const nextKey=getPageKey(nextDoc);const importedArticle=document.importNode(nextArticle,true);currentArticle.replaceWith(importedArticle);const renderedArticle=document.getElementById("nd-page");if(!renderedArticle||renderedArticle===currentArticle||(nextKey&&getPageKey(document)!==nextKey))return false;const nextToc=nextDoc.getElementById("nd-toc");const currentToc=document.getElementById("nd-toc");if(nextToc&&currentToc)currentToc.replaceWith(document.importNode(nextToc,true));if(nextDoc.title)document.title=nextDoc.title;const nextDescription=nextDoc.querySelector('meta[name="description"]');const currentDescription=document.querySelector('meta[name="description"]');if(nextDescription&&currentDescription)currentDescription.setAttribute("content",nextDescription.getAttribute("content")||"");setSidebarActive(url.pathname);initToc();closeMobileSidebar();return true};const navigateDocs=async(url,{replace=false,scroll=true}={})=>{if(!isDocsPath(url.pathname))return false;if(navigateController)navigateController.abort();const controller=new AbortController();navigateController=controller;document.documentElement.dataset.farmDocsNavigating="true";try{const response=await fetch(url.href,{cache:"no-store",headers:{accept:"text/html","x-farm-docs-navigate":"1"},signal:controller.signal});if(!response.ok||!((response.headers.get("content-type")||"").includes("text/html")))return false;const html=await response.text();if(!swapDocsPage(html,url))return false;if(replace)history.replaceState({farmDocs:true},"",url.href);else history.pushState({farmDocs:true},"",url.href);if(scroll){if(url.hash){let id=url.hash.slice(1);try{id=decodeURIComponent(id)}catch{}document.getElementById(id)?.scrollIntoView({block:"start"})}else window.scrollTo({top:0,left:0})}return true}catch(error){if(error?.name==="AbortError")return true;return false}finally{if(navigateController===controller){delete document.documentElement.dataset.farmDocsNavigating;navigateController=null}}};const initClientNavigation=()=>{document.addEventListener("click",(event)=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const target=event.target instanceof Element?event.target.closest("a[href]"):null;if(!target||target.target||target.hasAttribute("download"))return;let url;try{url=new URL(target.href,location.href)}catch{return}if(url.origin!==location.origin||!isDocsPath(url.pathname))return;if(normalizePath(url.pathname)===normalizePath(location.pathname)&&url.hash)return;event.preventDefault();navigateDocs(url).then((handled)=>{if(!handled)location.href=url.href})});window.addEventListener("popstate",()=>{navigateDocs(new URL(location.href),{replace:true,scroll:false}).then((handled)=>{if(!handled)location.reload()})})};const init=()=>{initToc();initMobileSidebar();initSidebarScroll();initClientNavigation()};if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init()})();</script>`;
}

function renderDocsPageActionsRuntimeScript(): string {
  return `<script>(()=>{if(window.__farmDocsPageActionsRuntime)return;window.__farmDocsPageActionsRuntime=true;const readArticleText=()=>{const article=document.getElementById("nd-page");if(!article)return"";const clone=article.cloneNode(true);if(!(clone instanceof HTMLElement))return article.innerText||"";clone.querySelectorAll("[data-page-actions],.fd-page-footer,.fd-page-nav").forEach((node)=>node.remove());return clone.innerText||""};const withTitle=(content,format,includeTitle)=>{if(!includeTitle)return content;const title=document.querySelector("#nd-page h1")?.textContent?.trim()||document.title.trim();if(!title)return content;const trimmed=content.trimStart();if(trimmed.startsWith(title)||trimmed.startsWith("# "+title))return content;return format==="markdown"?"# "+title+"\\n\\n"+content:title+"\\n\\n"+content};const writeClipboard=async(text)=>{if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);return}catch{}}const textarea=document.createElement("textarea");textarea.value=text;textarea.setAttribute("readonly","");textarea.style.position="fixed";textarea.style.opacity="0";textarea.style.pointerEvents="none";document.body.appendChild(textarea);textarea.select();document.execCommand("copy");textarea.remove()};const markCopied=(button)=>{const label=button.querySelector("[data-page-action-label]");button.dataset.copied="true";button.setAttribute("aria-label",button.dataset.copiedLabel||"Copied!");button.title=button.dataset.copiedLabel||"Copied!";if(label)label.textContent=button.dataset.copiedLabel||"Copied!";const previous=Number(button.dataset.copyTimeout||0);if(previous)clearTimeout(previous);button.dataset.copyTimeout=String(setTimeout(()=>{button.dataset.copied="false";button.setAttribute("aria-label",button.dataset.copyLabel||"Copy page");button.title=button.dataset.copyLabel||"Copy page";if(label)label.textContent=button.dataset.copyLabel||"Copy page";button.dataset.copyTimeout="0"},4500))};document.addEventListener("click",async(event)=>{const target=event.target instanceof Element?event.target.closest('[data-page-action="copy-markdown"]'):null;if(!(target instanceof HTMLButtonElement))return;event.preventDefault();const format=target.dataset.copyMarkdownFormat==="text"?"text":"markdown";const includeTitle=target.dataset.copyMarkdownIncludeTitle==="true";let content="";target.disabled=true;try{if(format==="markdown"&&target.dataset.markdownUrl){try{const response=await fetch(target.dataset.markdownUrl,{headers:{Accept:"text/markdown"}});if(response.ok)content=await response.text()}catch{}}if(!content)content=readArticleText();content=withTitle(content,format,includeTitle);if(content.trim()){await writeClipboard(content);markCopied(target)}}finally{target.disabled=false}})})();</script>`;
}

function renderDocsHashRuntimeScript(): string {
  return `<script>(()=>{if(window.__farmDocsHashRuntime)return;window.__farmDocsHashRuntime=true;const scrollToHash=()=>{if(!location.hash)return;let id=location.hash.slice(1);try{id=decodeURIComponent(id)}catch{}document.getElementById(id)?.scrollIntoView({block:"start"})};const schedule=()=>requestAnimationFrame(()=>requestAnimationFrame(scrollToHash));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",schedule,{once:true});else schedule();window.addEventListener("load",schedule,{once:true});window.addEventListener("hashchange",schedule)})();</script>`;
}

function renderDocsRuntimeScripts(docs: FarmDocsResolvedConfig): string {
  return `${renderDocsRuntimeScript(docs)}
${renderDocsHashRuntimeScript()}
${renderDocsPageActionsRuntimeScript()}`;
}

function renderFarmDocsFontPreloads(fontAssets: readonly FarmDocsPublicFontAsset[]): string {
  return fontAssets
    .map(
      ({ url }) =>
        `<link rel="preload" href="${escapeAttribute(url)}" as="font" type="font/woff2" crossorigin>`,
    )
    .join("\n  ");
}

function renderFarmDocsFontPreloadHeader(fontAssets: readonly FarmDocsPublicFontAsset[]): string {
  return fontAssets
    .map(({ url }) => `<${url}>; rel=preload; as=font; type=font/woff2; crossorigin`)
    .join(", ");
}

function getFarmLayoutFontPreloads(layoutFonts?: FarmLayoutFonts) {
  const seen = new Set<string>();
  return [layoutFonts?.body, layoutFonts?.code].flatMap((font) =>
    (font?.preloads || []).filter(({ href }) => {
      if (seen.has(href)) return false;
      seen.add(href);
      return true;
    }),
  );
}

function renderFarmLayoutFontPreloadHeader(layoutFonts?: FarmLayoutFonts): string {
  return getFarmLayoutFontPreloads(layoutFonts)
    .map(({ href, type }) => `<${href}>; rel=preload; as=font; type=${type}; crossorigin`)
    .join(", ");
}

function renderPixelDocsHtml(
  page: LoadedFarmDocsPage,
  pages: FarmDocsPage[],
  docs: FarmDocsResolvedConfig,
  clientEntry: string,
  faviconHref: string,
  requestUrl: URL,
  fontAssets: readonly FarmDocsPublicFontAsset[],
  fontStylesheetHref?: string,
  globalStylesheetHref?: string,
): string {
  const navTitle =
    typeof docs.config.nav === "object" && docs.config.nav && "title" in docs.config.nav
      ? String((docs.config.nav as { title?: unknown }).title || "Docs")
      : "Docs";
  const description = page.description || docs.config.metadata?.description || "";
  const tocItems = extractTocItems(page.body, getThemeTocDepth(docs));
  const themeName = getThemeName(docs);
  const searchEnabled = isFarmDocsSearchEnabled(docs);
  const socialMetadata = isFarmDocsSocialImageEnabled(page, docs)
    ? renderFarmDocsSocialMetadata(
        createFarmDocsSocialImageDescriptor(page, docs, requestUrl),
        getFarmDocsCustomSocialImage(page),
      )
    : "";

  return `<!DOCTYPE html>
<html class="dark" lang="en" data-docs-theme="${escapeAttribute(themeName)}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="@farming-labs/docs via Farm.js">
  <title>${escapeHtml(page.title)}</title>
  ${renderFarmDocsFaviconLink(faviconHref)}
  ${renderFarmDocsFontPreloads(fontAssets)}
  ${fontStylesheetHref ? `<link rel="stylesheet" href="${escapeAttribute(fontStylesheetHref)}">` : ""}
  ${globalStylesheetHref ? `<link rel="stylesheet" href="${escapeAttribute(globalStylesheetHref)}">` : ""}
  ${description ? `<meta name="description" content="${escapeHtml(description)}">` : ""}
  ${socialMetadata}
  ${searchEnabled ? renderDocsSearchBootstrapScript() : ""}
</head>
<body>
  <div id="nd-docs-layout" class="fd-layout" data-fd-framework="farmjs">
    <header class="mobile-topbar fd-header" aria-label="Mobile docs navigation">
      <button class="fd-mobile-nav-btn fd-menu-btn" type="button" data-sidebar-toggle aria-controls="nd-sidebar" aria-expanded="false" aria-label="Open menu">
        <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><line x1="3" y1="6" x2="21" y2="6"></line><line x1="3" y1="12" x2="21" y2="12"></line><line x1="3" y1="18" x2="21" y2="18"></line></svg>
      </button>
      <a class="fd-header-title" href="/">${escapeHtml(navTitle)}</a>
      <div class="mobile-topbar-actions">
        ${searchEnabled ? renderDocsSearchTrigger(true, "fd-search-trigger-mobile") : ""}
        <a class="mobile-topbar-link" href="/llms.txt">llms.txt</a>
      </div>
    </header>
    <aside id="nd-sidebar" class="fd-sidebar">
      <div class="sidebar-brand fd-sidebar-header">
        <a class="fd-sidebar-title" href="/">${renderFarmDocsBrandMark()}${renderFarmDocsBrandTitle(navTitle)}</a>
        <span>/ docs</span>
      </div>
      ${searchEnabled ? `<div class="fd-sidebar-search">${renderDocsSearchTrigger(true, "fd-sidebar-search-btn")}</div>` : ""}
      ${renderPixelNavItems(pages, page.href, docs)}
    </aside>
    <div class="sidebar-backdrop fd-sidebar-overlay" data-sidebar-backdrop></div>
    <main class="fd-main">
      <div class="fd-page">
      <article id="nd-page" class="prose fd-page-article fd-page-body fd-docs-content">
        ${renderPixelBreadcrumb(page, docs)}
${renderMarkdownHtmlWithTitleMeta(page, docs)}
        ${renderPixelPageFooter(page, docs)}
        ${renderPixelPageNav(pages, page.href, docs)}
      </article>
      <nav id="nd-toc" class="fd-toc sticky top-(--fd-docs-row-1) h-[calc(var(--fd-docs-height)-var(--fd-docs-row-1))] flex flex-col [grid-area:toc] w-(--fd-toc-width) pt-12 pe-4 pb-2 max-xl:hidden" data-toc aria-labelledby="toc-title">
      <div class="fd-toc-inner">
        <h3 id="toc-title" class="fd-toc-title inline-flex items-center gap-1.5 text-sm text-fd-muted-foreground"><svg class="size-4" viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 7h16"></path><path d="M4 12h16"></path><path d="M4 17h16"></path></svg>On this page</h3>
        <div class="toc-scroll">
          ${renderPixelToc(tocItems)}
        </div>
      </div>
    </nav>
      </div>
    </main>
  </div>
  ${searchEnabled ? renderDocsSearchMount(clientEntry) : ""}
  ${renderDocsRuntimeScripts(docs)}
</body>
</html>`;
}

export function createFarmDocsHandler(
  docs: FarmDocsResolvedConfig | undefined,
  options: FarmDocsHandlerOptions,
) {
  const faviconHref = resolveFarmDocsFavicon(docs, options);
  const fontAssets =
    options.fontAssets ?? toFarmDocsPublicFontAssets(resolveFarmDocsFontAssets(options.root));
  const fallbackFontPreloadHeader = renderFarmDocsFontPreloadHeader(fontAssets);

  return async function handleFarmDocsRequest(request: Request): Promise<Response | null> {
    if (!docs?.enabled || (request.method !== "GET" && request.method !== "HEAD")) return null;

    const contentDir = resolveFarmDocsContentDir(docs, options);
    const requestUrl = new URL(request.url);
    const socialImageSlug = getFarmDocsSocialImageSlug(docs, requestUrl);
    if (socialImageSlug !== null) {
      const socialImagePage = loadFarmDocsPage(contentDir, docs, socialImageSlug);
      if (
        !socialImagePage ||
        !isFarmDocsSocialImageEnabled(socialImagePage, docs) ||
        getFarmDocsCustomSocialImage(socialImagePage)
      ) {
        return null;
      }

      const descriptor = createFarmDocsSocialImageDescriptor(socialImagePage, docs, requestUrl);
      if (requestUrl.pathname !== descriptor.imagePath) return null;

      const etag = `"${descriptor.hash}"`;
      const immutable = requestUrl.searchParams.get("v") === descriptor.hash;
      const headers = new Headers({
        "Content-Type": "image/svg+xml; charset=utf-8",
        "Cache-Control": immutable
          ? "public, max-age=31536000, immutable"
          : "public, max-age=0, must-revalidate",
        ETag: etag,
        "X-Content-Type-Options": "nosniff",
      });
      if (request.headers.get("if-none-match") === etag) {
        return new Response(null, { status: 304, headers });
      }
      if (request.method === "HEAD") return new Response(null, { status: 200, headers });

      return new Response(renderFarmDocsSocialImageSvg(descriptor), { status: 200, headers });
    }

    const publicResponse = createFarmDocsPublicResponse(contentDir, docs, request);
    if (publicResponse) return publicResponse;

    if (!isFarmDocsRequest(docs, request)) return null;

    const page = loadPage(contentDir, docs, request);
    if (!page) return null;

    if (shouldReturnMarkdown(request)) {
      const origin = new URL(request.url).origin;
      return new Response(
        renderDocsMarkdownDocument(toFarmDocsMarkdownPage(page), {
          origin,
          llms: docs.config.llmsTxt ?? true,
          sitemap: docs.config.sitemap,
        }),
        {
          status: 200,
          headers: {
            "Content-Type": "text/markdown; charset=utf-8",
            "Cache-Control": "public, max-age=60",
          },
        },
      );
    }

    const pathname = new URL(request.url).pathname;
    const layoutFonts = await options.resolveLayoutFonts?.(pathname);
    const usesLayoutFonts = Boolean(layoutFonts?.body || layoutFonts?.code);
    const activeFontAssets = usesLayoutFonts ? [] : fontAssets;
    const fontPreloadHeader = usesLayoutFonts
      ? renderFarmLayoutFontPreloadHeader(layoutFonts)
      : fallbackFontPreloadHeader;

    return new Response(
      renderPixelDocsHtml(
        page,
        discoverFarmDocsPages(contentDir, docs),
        docs,
        options.clientEntry || "/farm-client.js",
        faviconHref,
        requestUrl,
        activeFontAssets,
        usesLayoutFonts ? options.fontStylesheetHref : undefined,
        options.globalStylesheetHref,
      ),
      {
        status: 200,
        headers: {
          "Content-Type": "text/html; charset=utf-8",
          "Cache-Control": "public, s-maxage=60, stale-while-revalidate=300",
          ...(fontPreloadHeader ? { Link: fontPreloadHeader } : {}),
        },
      },
    );
  };
}
