/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_hello } from "../app/api/hello/route";
import type { POST as POST_hello } from "../app/api/hello/route";
import type { GET as GET_users } from "../app/api/users/route";
import type { POST as POST_users } from "../app/api/users/route";

// Type-only representation of your API routes
export type APIRouter = {
  hello: {
    get: typeof GET_hello;
    post: typeof POST_hello;
  };
  users: {
    get: typeof GET_users;
    post: typeof POST_users;
  };
};
