// Generated by Farm.js CLI. Review before committing.
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

// Farm.js generated from integration "billing" model "billingAccount"
export const billingBillingAccount = sqliteTable("billing_account", {
  id: text("id").primaryKey(),
  ownerId: text("owner_id").notNull(),
  ownerKind: text("owner_kind").notNull().default("user"),
  stripeCustomerId: text("stripe_customer_id").unique(),
  stripeSubscriptionId: text("stripe_subscription_id").unique(),
  planId: text("plan_id").notNull().default("free"),
  productId: text("product_id"),
  status: text("status").notNull().default("free"),
  currentPeriodEnd: integer("current_period_end", { mode: "timestamp_ms" }),
  cancelAtPeriodEnd: integer("cancel_at_period_end", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({
  ownerIdIdx: index("billing_account_owner_id_idx").on(table.ownerId),
  ownerKindIdx: index("billing_account_owner_kind_idx").on(table.ownerKind),
  billingAccountOwnerUnique: uniqueIndex("billing_account_owner_unique").on(table.ownerKind, table.ownerId),
}));
