/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { POST as POST_greeting } from "../app/api/greeting/route";

// Type-only representation of your API routes
export type APIRouter = {
  greeting: {
    post: typeof POST_greeting;
  };
};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/greeting",
    methods: ["POST"],
  },
] as const;
