/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 * Generated at: 2025-10-16T15:46:35.478Z
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_auth_login } from "../app/api/auth/login/route";
import type { POST as POST_auth_login } from "../app/api/auth/login/route";
import type { GET as GET_hello } from "../app/api/hello/route";
import type { POST as POST_hello } from "../app/api/hello/route";
import type { GET as GET_test } from "../app/api/test/route";
import type { GET as GET_users } from "../app/api/users/route";
import type { POST as POST_users } from "../app/api/users/route";

// Type-only representation of your API routes
export type APIRouter = {
  auth: {
    login: {
      get: typeof GET_auth_login;
      post: typeof POST_auth_login;
    };
  };
  hello: {
    get: typeof GET_hello;
    post: typeof POST_hello;
  };
  test: {
    get: typeof GET_test;
  };
  users: {
    get: typeof GET_users;
    post: typeof POST_users;
  };
};
