/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { PluginAPIRouter } from "@farm.js/core/api";
import type FarmPluginConfig0 from "../../layers/framework-features/farm.config";
import type FarmPluginConfig1 from "../../farm.config";
import type { GET as GET_auth_login } from "../app/api/auth/login/route";
import type { POST as POST_auth_login } from "../app/api/auth/login/route";
import type { GET as GET_hello } from "../app/api/hello/route";
import type { POST as POST_hello } from "../app/api/hello/route";
import type { GET as GET_integration_lab_server } from "../app/api/integration-lab/server/route";
import type { GET as GET_maintenance_cleanup } from "../app/api/maintenance/cleanup/route";
import type { GET as GET_slow } from "../app/api/slow/route";
import type { GET as GET_storage_demo } from "../app/api/storage-demo/route";
import type { POST as POST_storage_demo } from "../app/api/storage-demo/route";
import type { DELETE as DELETE_storage_demo } from "../app/api/storage-demo/route";
import type { GET as GET_test } from "../app/api/test/route";
import type { POST as POST_transport_lab } from "../app/api/transport-lab/route";
import type { GET as GET_users } from "../app/api/users/route";
import type { POST as POST_users } from "../app/api/users/route";
import type { DELETE as DELETE_users } from "../app/api/users/route";
import type { PATCH as PATCH_users } from "../app/api/users/route";

// Type-only representation of your API routes
export type APIRouter = PluginAPIRouter<typeof FarmPluginConfig0> & PluginAPIRouter<typeof FarmPluginConfig1> & {
  auth: {
    login: {
      get: typeof GET_auth_login;
      post: typeof POST_auth_login;
    };
  };
  hello: {
    get: typeof GET_hello;
    post: typeof POST_hello;
  };
  "integration-lab": {
    server: {
      get: typeof GET_integration_lab_server;
    };
  };
  maintenance: {
    cleanup: {
      get: typeof GET_maintenance_cleanup;
    };
  };
  slow: {
    get: typeof GET_slow;
  };
  "storage-demo": {
    get: typeof GET_storage_demo;
    post: typeof POST_storage_demo;
    delete: typeof DELETE_storage_demo;
  };
  test: {
    get: typeof GET_test;
  };
  "transport-lab": {
    post: typeof POST_transport_lab;
  };
  users: {
    get: typeof GET_users;
    post: typeof POST_users;
    delete: typeof DELETE_users;
    patch: typeof PATCH_users;
  };
};

// Pass this schema-free manifest to createAPIClient({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/auth/login",
    methods: ["GET", "POST"],
  },
  {
    path: "/api/hello",
    methods: ["GET", "POST"],
  },
  {
    path: "/api/integration-lab/server",
    methods: ["GET"],
  },
  {
    path: "/api/maintenance/cleanup",
    methods: ["GET"],
  },
  {
    path: "/api/projects/[projectId]/uploads/[uploadId]",
    methods: ["GET"],
  },
  {
    path: "/api/slow",
    methods: ["GET"],
  },
  {
    path: "/api/storage-demo",
    methods: ["DELETE", "GET", "POST"],
  },
  {
    path: "/api/test",
    methods: ["GET"],
  },
  {
    path: "/api/transport-lab",
    methods: ["POST"],
  },
  {
    path: "/api/users",
    methods: ["DELETE", "GET", "PATCH", "POST"],
  },
] as const;
