/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 * Generated at: 2026-07-17T19:04:11.039Z
 * 
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { GET as GET_auth_login } from "../app/api/auth/login/route";
import type { POST as POST_auth_login } from "../app/api/auth/login/route";
import type { GET as GET_hello } from "../app/api/hello/route";
import type { POST as POST_hello } from "../app/api/hello/route";
import type { GET as GET_integrationlab_server } from "../app/api/integration-lab/server/route";
import type { GET as GET_maintenance_cleanup } from "../app/api/maintenance/cleanup/route";
import type { GET as GET_slow } from "../app/api/slow/route";
import type { GET as GET_storagedemo } from "../app/api/storage-demo/route";
import type { POST as POST_storagedemo } from "../app/api/storage-demo/route";
import type { DELETE as DELETE_storagedemo } from "../app/api/storage-demo/route";
import type { GET as GET_test } from "../app/api/test/route";
import type { GET as GET_users } from "../app/api/users/route";
import type { POST as POST_users } from "../app/api/users/route";
import type { DELETE as DELETE_users } from "../app/api/users/route";
import type { PATCH as PATCH_users } from "../app/api/users/route";

// Type-only representation of your API routes
export type APIRouter = {
  auth: {
    login: {
      get: typeof GET_auth_login;
      post: typeof POST_auth_login;
    };
  };
  hello: {
    get: typeof GET_hello;
    post: typeof POST_hello;
  };
  "integration-lab": {
    server: {
      get: typeof GET_integrationlab_server;
    };
  };
  maintenance: {
    cleanup: {
      get: typeof GET_maintenance_cleanup;
    };
  };
  slow: {
    get: typeof GET_slow;
  };
  "storage-demo": {
    get: typeof GET_storagedemo;
    post: typeof POST_storagedemo;
    delete: typeof DELETE_storagedemo;
  };
  test: {
    get: typeof GET_test;
  };
  users: {
    get: typeof GET_users;
    post: typeof POST_users;
    delete: typeof DELETE_users;
    patch: typeof PATCH_users;
  };
};
