/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 * Generated at: 2026-04-22T20:10:04.816Z
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { POST as POST_waitlist } from "../app/api/waitlist/route";

// Type-only representation of your API routes
export type APIRouter = {
  waitlist: {
    post: typeof POST_waitlist;
  };
};
