/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * Server modules are imported only as types. Runtime data contains paths and methods only.
 */

import type { POST as POST_telemetry_dashboard_session } from "../app/api/telemetry/dashboard/session/route";
import type { POST as POST_telemetry_v1_events } from "../app/api/telemetry/v1/events/route";
import type { POST as POST_telemetry_v1_sites } from "../app/api/telemetry/v1/sites/route";
import type { POST as POST_waitlist } from "../app/api/waitlist/route";

// Type-only representation of your API routes
export type APIRouter = {
  telemetry: {
    dashboard: {
      session: {
        post: typeof POST_telemetry_dashboard_session;
      };
    };
    v1: {
      events: {
        post: typeof POST_telemetry_v1_events;
      };
      sites: {
        post: typeof POST_telemetry_v1_sites;
      };
    };
  };
  waitlist: {
    post: typeof POST_waitlist;
  };
};

// Pass this schema-free manifest to createApiClients({ routes: apiRoutes }).
export const apiRoutes = [
  {
    path: "/api/telemetry/dashboard/session",
    methods: ["POST"],
  },
  {
    path: "/api/telemetry/v1/events",
    methods: ["POST"],
  },
  {
    path: "/api/telemetry/v1/sites",
    methods: ["POST"],
  },
  {
    path: "/api/waitlist",
    methods: ["POST"],
  },
] as const;
