/**
 * Auto-generated API router types
 * This file is automatically generated - do not edit manually
 *
 * This file contains only TypeScript types for the API client.
 * Runtime imports are used only at the type level.
 */

import type { POST as POST_telemetry_dashboard_session } from "../app/api/telemetry/dashboard/session/route";
import type { POST as POST_telemetry_v1_events } from "../app/api/telemetry/v1/events/route";
import type { POST as POST_telemetry_v1_sites } from "../app/api/telemetry/v1/sites/route";
import type { POST as POST_waitlist } from "../app/api/waitlist/route";

// Type-only representation of your API routes
export type APIRouter = {
  telemetry: {
    dashboard: {
      session: {
        post: typeof POST_telemetry_dashboard_session;
      };
    };
    v1: {
      events: {
        post: typeof POST_telemetry_v1_events;
      };
      sites: {
        post: typeof POST_telemetry_v1_sites;
      };
    };
  };
  waitlist: {
    post: typeof POST_waitlist;
  };
};
